import Mathlib

/-!
# Challenge: the low individual degree test main theorem

Self-contained comparator challenge for `MIPStarRE.LDT.Test.mainFormal`, the
corrected source statement of `thm:main-formal` — the soundness theorem of the
quantum low individual degree test (Ji, Natarajan, Vidick, Wright, Yuen,
"Quantum soundness of the classical low individual degree test",
arXiv:2009.12982), the central technical ingredient of MIP* = RE.

This file imports **only Mathlib** and re-declares, verbatim and in dependency
order, every definition in the transitive closure of the statement of
`mainFormal`; the theorem itself is stated with `sorry`.  It is the entire
human audit surface: a reader who agrees that this file states the intended
theorem does not need to read anything else.  The
[comparator](https://github.com/leanprover/comparator) tool verifies
mechanically that the [MIPStarRE](https://github.com/LionSR/MIPStarRE)
library declares statements identical to these and proves the theorem using
no axioms beyond `propext`, `Quot.sound`, and `Classical.choice`.

Each declaration carries a provenance comment (`-- source: <file>:<lines>`)
pointing at its origin in the MIPStarRE library, where docstrings cite the
paper passages being encoded.  This file is generated by
`scripts/comparator/` in that repository; see the README alongside this file
for how to run the verification.
-/

open scoped BigOperators MatrixOrder Matrix ComplexOrder
namespace MIPStarRE.LDT

-- source: MIPStarRE/LDT/Basic/ParametersBase.lean:18-18  (MIPStarRE.LDT.Error)
abbrev Error := ℝ

-- source: MIPStarRE/LDT/Basic/ParametersBase.lean:32-45  (MIPStarRE.LDT.Parameters)
/-- Parameters for the `(m,q,d)` low individual degree test.

Besides the usual positivity assumptions, we bundle the paper-faithful witness
that `q = p^n` is a prime power. -/
structure Parameters where
  m : ℕ
  q : ℕ
  d : ℕ
  hm : 0 < m
  /-- Kept as a compatibility field so existing positivity proofs can continue
  to use `params.hq`; it is derivable from `hqPrimePower`. -/
  hq : 0 < q
  /-- Paper-faithful witness that `q` is a prime power. -/
  hqPrimePower : ∃ p n, Nat.Prime p ∧ 0 < n ∧ q = p ^ n
end MIPStarRE.LDT
namespace MIPStarRE.Quantum

-- source: MIPStarRE/Quantum/FiniteMatrix/Basic.lean:78-79  (MIPStarRE.Quantum.Op)
/-- Square complex matrices as the finite-dimensional operator algebra. -/
abbrev Op (d : Type*) := Matrix d d ℂ
end MIPStarRE.Quantum
namespace MIPStarRE.LDT

-- source: MIPStarRE/LDT/Basic/ParametersBase.lean:170-170  (MIPStarRE.LDT.Fq)
abbrev Fq (params : Parameters) := Fin params.q

-- source: MIPStarRE/LDT/Basic/ParametersBase.lean:171-171  (MIPStarRE.LDT.Point)
abbrev Point (params : Parameters) := Fin params.m → Fq params

-- source: MIPStarRE/LDT/Basic/ParametersBase.lean:174-175  (MIPStarRE.LDT.instInhabitedFinM)
instance {params : Parameters} : Inhabited (Fin params.m) :=
  ⟨⟨0, params.hm⟩⟩

-- source: MIPStarRE/LDT/Basic/ParametersBase.lean:177-178  (MIPStarRE.LDT.instInhabitedFq)
instance {params : Parameters} : Inhabited (Fq params) :=
  ⟨⟨0, params.hq⟩⟩

-- source: MIPStarRE/LDT/Basic/ParametersBase.lean:210-217  (MIPStarRE.LDT.FieldModel)
/-- A bundled field model for the paper's `F_q`, together with a coding equivalence
to the repository's finite carrier `Fin q`. -/
class FieldModel (q : ℕ) where
  K : Type*
  instField : Field K
  instFintype : Fintype K
  instDecidableEq : DecidableEq K
  equiv : K ≃ Fin q

-- source: MIPStarRE/LDT/Basic/ParametersBase.lean (attribute command)
attribute [instance_reducible, instance] FieldModel.instField FieldModel.instFintype
  FieldModel.instDecidableEq

-- source: MIPStarRE/LDT/Basic/ParametersBase.lean:277-277  (MIPStarRE.LDT.Scalar)
abbrev Scalar (params : Parameters) [FieldModel params.q] := FieldModel.K params.q

-- source: MIPStarRE/LDT/Basic/ParametersBase.lean:278-279  (MIPStarRE.LDT.PolynomialModel)
abbrev PolynomialModel (params : Parameters) [FieldModel params.q] :=
  MvPolynomial (Fin params.m) (Scalar params)

-- source: MIPStarRE/LDT/Basic/ParametersBase.lean:280-281  (MIPStarRE.LDT.LinePolynomialModel)
abbrev LinePolynomialModel (params : Parameters) [FieldModel params.q] :=
  _root_.Polynomial (Scalar params)

-- source: MIPStarRE/LDT/Basic/ParametersBase.lean:289-291  (MIPStarRE.LDT.decodeScalar)
/-- Interpret a coded coordinate in `Fin q` as a scalar in the chosen field model. -/
def decodeScalar {params : Parameters} [FieldModel params.q] (x : Fq params) : Scalar params :=
  (FieldModel.equiv (q := params.q)).symm x

-- source: MIPStarRE/LDT/Basic/ParametersBase.lean:293-295  (MIPStarRE.LDT.encodeScalar)
/-- Re-encode a field-model scalar as its canonical representative in `Fin q`. -/
def encodeScalar {params : Parameters} [FieldModel params.q] (x : Scalar params) : Fq params :=
  FieldModel.equiv (q := params.q) x

-- source: MIPStarRE/LDT/Basic/ParametersBase.lean:306-308  (MIPStarRE.LDT.zeroCoord)
/-- The zero coordinate. -/
def zeroCoord {params : Parameters} [FieldModel params.q] : Fq params :=
  encodeScalar 0

-- source: MIPStarRE/LDT/Basic/ParametersBase.lean:310-312  (MIPStarRE.LDT.addCoord)
/-- Coordinate addition transported through the `Fin q` coding. -/
def addCoord {params : Parameters} [FieldModel params.q] (x y : Fq params) : Fq params :=
  encodeScalar (decodeScalar x + decodeScalar y)

-- source: MIPStarRE/LDT/Basic/ParametersBase.lean:339-341  (MIPStarRE.LDT.mulCoord)
/-- Coordinate multiplication transported through the `Fin q` coding. -/
def mulCoord {params : Parameters} [FieldModel params.q] (x y : Fq params) : Fq params :=
  encodeScalar (decodeScalar x * decodeScalar y)

-- source: MIPStarRE/LDT/Basic/ParametersBase.lean:347-349  (MIPStarRE.LDT.addPoint)
/-- Pointwise addition in the coded ambient space. -/
def addPoint {params : Parameters} [FieldModel params.q] (u v : Point params) : Point params :=
  fun i => addCoord (u i) (v i)

-- source: MIPStarRE/LDT/Basic/ParametersBase.lean:351-354  (MIPStarRE.LDT.smulPoint)
/-- Scalar multiplication in the coded ambient space. -/
def smulPoint {params : Parameters} [FieldModel params.q] (t : Fq params) (u : Point params) :
    Point params :=
  fun i => mulCoord t (u i)

-- source: MIPStarRE/LDT/Basic/ParametersBase.lean:406-409  (MIPStarRE.LDT.decodePoint)
/-- Decode a coded point as a tuple of scalars in the chosen field model. -/
def decodePoint {params : Parameters} [FieldModel params.q] (u : Point params) :
    Fin params.m → Scalar params :=
  fun i => decodeScalar (u i)

-- source: MIPStarRE/LDT/Basic/ParametersBase.lean:411-414  (MIPStarRE.LDT.evalPolynomialModel)
/-- Evaluate a multivariate polynomial over the chosen field model on a coded point. -/
noncomputable def evalPolynomialModel (params : Parameters) [FieldModel params.q]
    (p : PolynomialModel params) (u : Point params) : Fq params :=
  encodeScalar (MvPolynomial.eval (decodePoint u) p)

-- source: MIPStarRE/LDT/Basic/ParametersBase.lean:416-419  (MIPStarRE.LDT.evalLinePolynomialModel)
/-- Evaluate a univariate polynomial over the chosen field model on a coded point. -/
noncomputable def evalLinePolynomialModel (params : Parameters) [FieldModel params.q]
    (p : LinePolynomialModel params) (t : Fq params) : Fq params :=
  encodeScalar (_root_.Polynomial.eval (decodeScalar t) p)

-- source: MIPStarRE/LDT/Basic/AxisParallelLine.lean:18-21  (MIPStarRE.LDT.AxisParallelLine)
/-- A genuinely axis-parallel affine line in `F_q^m`. -/
structure AxisParallelLine (params : Parameters) where
  base : Point params
  direction : Fin params.m
end MIPStarRE.LDT
namespace MIPStarRE.Quantum

-- elaboration context of MIPStarRE/Quantum/FiniteMatrix/NormalizedTrace.lean
section
open scoped Matrix.Norms.Elementwise
open WithLp
variable {d : Type*} [Fintype d]

-- source: MIPStarRE/Quantum/FiniteMatrix/NormalizedTrace.lean:20-22  (MIPStarRE.Quantum.normalizedTrace)
/-- The normalized trace `τ(A) = tr(A) / |d|`. -/
noncomputable def normalizedTrace (A : Op d) : ℂ :=
  A.trace / (Fintype.card d : ℂ)
end  -- module scope
end MIPStarRE.Quantum
namespace MIPStarRE.LDT
namespace AxisParallelLine

-- source: MIPStarRE/LDT/Basic/AxisParallelLine.lean:27-34  (MIPStarRE.LDT.AxisParallelLine.pointAt)
/-- The canonical affine parameterization `t ↦ base + t e_i`. -/
def pointAt {params : Parameters} [FieldModel params.q]
    (ℓ : AxisParallelLine params) : Fq params → Point params :=
  fun t i =>
    if i = ℓ.direction then
      addCoord (ℓ.base i) t
    else
      ℓ.base i

-- source: MIPStarRE/LDT/Basic/AxisParallelLine.lean:51-56  (MIPStarRE.LDT.AxisParallelLine.rebaseAt)
/-- Rebase an axis-parallel line so that the old point `ℓ.pointAt t`
becomes the new base point. -/
def rebaseAt {params : Parameters} [FieldModel params.q]
    (ℓ : AxisParallelLine params) (t : Fq params) : AxisParallelLine params where
  base := ℓ.pointAt t
  direction := ℓ.direction
end AxisParallelLine

-- source: MIPStarRE/LDT/Basic/DiagonalLine.lean:16-19  (MIPStarRE.LDT.DiagonalLine)
/-- A genuinely affine diagonal line in `F_q^m`. -/
structure DiagonalLine (params : Parameters) where
  base : Point params
  direction : Point params
namespace DiagonalLine

-- source: MIPStarRE/LDT/Basic/DiagonalLine.lean:25-28  (MIPStarRE.LDT.DiagonalLine.pointAt)
/-- The canonical affine parameterization `t ↦ base + t · direction`. -/
def pointAt {params : Parameters} [FieldModel params.q]
    (ℓ : DiagonalLine params) : Fq params → Point params :=
  fun t => addPoint ℓ.base (smulPoint t ℓ.direction)
end DiagonalLine
namespace Test

-- source: MIPStarRE/LDT/Test/MainTheorem/ScalarBounds/Definitions.lean:28-36  (MIPStarRE.LDT.Test.mainFormalError)
/-- The formal final error envelope for `thm:main-formal`.

The sharper pre-completion line-169 repair keeps the point-transport scale at
the original `1/40000` exponent used by the surrounding Step 8 cascade. -/
noncomputable def mainFormalError (params : Parameters) (k : ℕ) (eps : Error) : Error :=
  100000 * ((k : Error) ^ (2 : ℕ)) * ((params.m : Error) ^ (4 : ℕ)) *
    (Real.rpow eps (1 / (40000 : Error)) +
      Real.rpow (((params.d : Error) / (params.q : Error))) (1 / (40000 : Error)) +
      Real.exp (-((k : Error) / (2560000 * ((params.m : Error) ^ (2 : ℕ))))))
end Test
namespace DiagonalLine

-- source: MIPStarRE/LDT/Basic/DiagonalLine.lean:100-104  (MIPStarRE.LDT.DiagonalLine.rebaseAt)
/-- Rebase a diagonal line so that the old point `ℓ.pointAt t` becomes the new base point. -/
def rebaseAt {params : Parameters} [FieldModel params.q]
    (ℓ : DiagonalLine params) (t : Fq params) : DiagonalLine params where
  base := ℓ.pointAt t
  direction := ℓ.direction
end DiagonalLine

-- source: MIPStarRE/LDT/Basic/LinePolynomials.lean:33-41  (MIPStarRE.LDT.natDegree_comp_C_add_X_le)
/-- Composing with the degree-one translation `C a + X` preserves `natDegree`
bounds.  Shared degree bookkeeping for the `reparamAt` reparametrizations
below. -/
theorem natDegree_comp_C_add_X_le {params : Parameters} [FieldModel params.q]
    (p : LinePolynomialModel params) (a : Scalar params) {n : ℕ}
    (hp : p.natDegree ≤ n) :
    (p.comp (_root_.Polynomial.C a + _root_.Polynomial.X)).natDegree ≤ n :=
  le_trans (_root_.Polynomial.natDegree_comp_le)
    (by rw [add_comm, _root_.Polynomial.natDegree_X_add_C, Nat.mul_one]; exact hp)

-- source: MIPStarRE/LDT/Basic/LinePolynomials.lean:43-46  (MIPStarRE.LDT.AxisLinePolynomial)
/-- Axis-parallel line answers are genuine univariate degree-`d` polynomials. -/
structure AxisLinePolynomial (params : Parameters) [FieldModel params.q] where
  poly : LinePolynomialModel params
  degreeBounded : poly.natDegree ≤ params.d
namespace AxisLinePolynomial

-- source: MIPStarRE/LDT/Basic/LinePolynomials.lean:55-58  (MIPStarRE.LDT.AxisLinePolynomial.toFun)
/-- Evaluation of an axis-line answer on the line parameter. -/
noncomputable def toFun {params : Parameters} [FieldModel params.q]
    (f : AxisLinePolynomial params) : Fq params → Fq params :=
  evalLinePolynomialModel params f.poly

-- source: MIPStarRE/LDT/Basic/LinePolynomials.lean (elaboration context)
noncomputable instance {params : Parameters} [FieldModel params.q] :
    CoeFun (AxisLinePolynomial params) (fun _ => Fq params → Fq params) :=
  ⟨AxisLinePolynomial.toFun⟩

-- source: MIPStarRE/LDT/Basic/LinePolynomials.lean:86-93  (MIPStarRE.LDT.AxisLinePolynomial.ext)
@[ext] theorem ext {params : Parameters} [FieldModel params.q]
    {f g : AxisLinePolynomial params} (hpoly : f.poly = g.poly) : f = g := by
  cases f with
  | mk polyf hpolyf =>
      cases g with
      | mk polyg hpolyg =>
          cases hpoly
          congr

-- source: MIPStarRE/LDT/Basic/LinePolynomials.lean:95-99  (MIPStarRE.LDT.AxisLinePolynomial.reparamAt)
/-- Reparametrize an axis-line answer by translating the line parameter. -/
noncomputable def reparamAt {params : Parameters} [FieldModel params.q]
    (f : AxisLinePolynomial params) (t : Fq params) : AxisLinePolynomial params where
  poly := f.poly.comp (_root_.Polynomial.C (decodeScalar t) + _root_.Polynomial.X)
  degreeBounded := natDegree_comp_C_add_X_le f.poly (decodeScalar t) f.degreeBounded
end AxisLinePolynomial

-- source: MIPStarRE/LDT/Basic/LinePolynomials.lean:194-197  (MIPStarRE.LDT.DiagonalLinePolynomial)
/-- Diagonal-line answers are genuine univariate degree-`md` polynomials. -/
structure DiagonalLinePolynomial (params : Parameters) [FieldModel params.q] where
  poly : LinePolynomialModel params
  degreeBounded : poly.natDegree ≤ params.m * params.d
namespace DiagonalLinePolynomial

-- source: MIPStarRE/LDT/Basic/LinePolynomials.lean:206-209  (MIPStarRE.LDT.DiagonalLinePolynomial.toFun)
/-- Evaluation of a diagonal-line answer on the line parameter. -/
noncomputable def toFun {params : Parameters} [FieldModel params.q]
    (f : DiagonalLinePolynomial params) : Fq params → Fq params :=
  evalLinePolynomialModel params f.poly

-- source: MIPStarRE/LDT/Basic/LinePolynomials.lean (elaboration context)
noncomputable instance {params : Parameters} [FieldModel params.q] :
    CoeFun (DiagonalLinePolynomial params) (fun _ => Fq params → Fq params) :=
  ⟨DiagonalLinePolynomial.toFun⟩

-- source: MIPStarRE/LDT/Basic/LinePolynomials.lean:215-222  (MIPStarRE.LDT.DiagonalLinePolynomial.ext)
@[ext] theorem ext {params : Parameters} [FieldModel params.q]
    {f g : DiagonalLinePolynomial params} (hpoly : f.poly = g.poly) : f = g := by
  cases f with
  | mk polyf hpolyf =>
      cases g with
      | mk polyg hpolyg =>
          cases hpoly
          congr

-- source: MIPStarRE/LDT/Basic/LinePolynomials.lean:224-240  (MIPStarRE.LDT.DiagonalLinePolynomial.reparamAt)
/-- Reparametrize a diagonal-line answer by translating the line parameter.

Concretely, the underlying univariate polynomial `f.poly` (over `Scalar params` in
the chosen field model) is precomposed with `X + C (decodeScalar t)`, i.e. the
coefficients are shifted using genuine *field* addition on `Scalar params` — not
the `Fin q` arithmetic on `Fq params`. Transporting back through `encodeScalar`
gives the answer-level identity `reparamAt f t s = f (addCoord t s)` (see
`reparamAt_apply`), where `addCoord` is field addition lifted through the coding
`FieldModel.equiv`. Composition with a degree-one polynomial preserves the
`natDegree ≤ params.m * params.d` bound.

This is the answer-level geometric fact behind rebasing a diagonal line at
parameter `t`: the old parameter `addCoord t s` becomes the new parameter `s`. -/
noncomputable def reparamAt {params : Parameters} [FieldModel params.q]
    (f : DiagonalLinePolynomial params) (t : Fq params) : DiagonalLinePolynomial params where
  poly := f.poly.comp (_root_.Polynomial.C (decodeScalar t) + _root_.Polynomial.X)
  degreeBounded := natDegree_comp_C_add_X_le f.poly (decodeScalar t) f.degreeBounded
end DiagonalLinePolynomial

-- source: MIPStarRE/LDT/Basic/QuantumState.lean:14-27  (MIPStarRE.LDT.QuantumState)
/-- A PSD density matrix indexed by `ι`.

There is intentionally no global `Inhabited` instance: the zero matrix is PSD but
not a physical state of unit trace, so an ambient default would silently
trivialize later statements. Use `IsNormalized` to additionally require
`τ(ρ) = 1`.

This remains the ambient state space for the current LDT development: strategy
packages in `LDT/Test/StrategyCore.lean`, the SWAP-symmetry API `PermInvState`,
and the expectation-value lemmas in `LDT/Basic/OperatorExpectations.lean` are all
stated for arbitrary density matrices, not only pure states. -/
structure QuantumState (ι : Type*) [Fintype ι] [DecidableEq ι] where
  density : MIPStarRE.Quantum.Op ι := 0
  density_psd : 0 ≤ density := by positivity

-- source: MIPStarRE/LDT/Basic/LowDegreePolynomial.lean:17-20  (MIPStarRE.LDT.Polynomial)
/-- Global low-individual-degree polynomial outcomes. -/
structure Polynomial (params : Parameters) [FieldModel params.q] where
  poly : PolynomialModel params
  lowIndividualDegree : ∀ i, MvPolynomial.degreeOf i poly ≤ params.d

-- source: MIPStarRE/LDT/Basic/Distribution.lean:22-27  (MIPStarRE.LDT.Distribution)
/-- A finite-support weighted distribution with nonnegative real-valued weights. -/
structure Distribution (α : Type*) where
  support : Finset α := ∅
  weight : α → Error := fun _ => 0
  nonnegative : ∀ a, 0 ≤ weight a := by intro _; positivity
  outsideSupport : ∀ a, a ∉ support → weight a = 0 := by intro _ _; rfl

-- source: MIPStarRE/LDT/Basic/QuantumState.lean:29-32  (MIPStarRE.LDT.QuantumState.IsNormalized)
/-- Unit normalized trace for the concrete matrix carried by a state. -/
def QuantumState.IsNormalized {ι : Type*} [Fintype ι] [DecidableEq ι]
    (ψ : QuantumState ι) : Prop :=
  MIPStarRE.Quantum.normalizedTrace ψ.density = 1
namespace Polynomial

-- source: MIPStarRE/LDT/Basic/LowDegreePolynomial.lean:36-39  (MIPStarRE.LDT.Polynomial.toFun)
/-- Evaluation of the stored multivariate polynomial on a coded point. -/
noncomputable def toFun {params : Parameters} [FieldModel params.q] (g : Polynomial params) :
    Point params → Fq params :=
  evalPolynomialModel params g.poly

-- source: MIPStarRE/LDT/Basic/LowDegreePolynomial.lean (elaboration context)
noncomputable instance {params : Parameters} [FieldModel params.q] :
    CoeFun (Polynomial params) (fun _ => Point params → Fq params) :=
  ⟨Polynomial.toFun⟩
end Polynomial

-- source: MIPStarRE/LDT/Basic/QuantumState.lean:173-176  (MIPStarRE.LDT.ev)
/-- The expectation `Re τ(ψ X)`. Dimensions match by construction. -/
noncomputable def ev {ι : Type*} [Fintype ι] [DecidableEq ι]
    (ψ : QuantumState ι) (X : MIPStarRE.Quantum.Op ι) : Error :=
  Complex.re <| MIPStarRE.Quantum.normalizedTrace (ψ.density * X)

-- source: MIPStarRE/LDT/Basic/QuantumState.lean:185-189  (MIPStarRE.LDT.opTensor)
/-- Tensor product of two operators via Kronecker product. -/
abbrev opTensor {ι₁ ι₂ : Type*} [Fintype ι₁] [DecidableEq ι₁] [Fintype ι₂] [DecidableEq ι₂]
    (A : MIPStarRE.Quantum.Op ι₁) (B : MIPStarRE.Quantum.Op ι₂) :
    MIPStarRE.Quantum.Op (ι₁ × ι₂) :=
  Matrix.kronecker A B

-- source: MIPStarRE/LDT/Basic/Distribution.lean:218-220  (MIPStarRE.LDT.avgOver)
/-- Average a scalar function against the stored finite support of a distribution. -/
def avgOver {α : Type*} (𝒟 : Distribution α) (f : α → Error) : Error :=
  ∑ a ∈ 𝒟.support, 𝒟.weight a * f a
namespace Distribution

-- source: MIPStarRE/LDT/Basic/Distribution.lean:404-417  (MIPStarRE.LDT.Distribution.uniformOnFinset)
/-- The uniform distribution on a specified finite support.

The stored support is `s`, and the weight of a point is the elementary finite
uniform weight `1 / s.card` on `s` and `0` off `s`.  When the support is empty
this gives the zero sub-probability distribution, matching the convention used
for degenerate filtered supports in the LDT development. -/
noncomputable def uniformOnFinset {α : Type*} (s : Finset α) : Distribution α :=
  letI := Classical.decEq α
  { support := s
    weight := fun a => if a ∈ s then 1 / (s.card : Error) else 0
    nonnegative := fun _ => by
      split_ifs <;> positivity
    outsideSupport := fun _ ha => by
      simp [ha] }
end Distribution

-- source: MIPStarRE/LDT/Basic/Distribution.lean:479-482  (MIPStarRE.LDT.uniformDistribution)
/-- The uniform distribution on a nonempty finite type. -/
noncomputable def uniformDistribution (α : Type*)
    [Fintype α] [DecidableEq α] [Nonempty α] : Distribution α :=
  Distribution.uniformOnFinset Finset.univ

-- source: MIPStarRE/LDT/Basic/SubMeasurementCore.lean:13-23  (MIPStarRE.LDT.SubMeas)
/-- A paper-local submeasurement with outcomes in `α` and Hilbert space index `ι`.

There is intentionally no global `Inhabited` instance: the zero family satisfies
these raw axioms, but using it as an ambient default would silently turn later
arguments into vacuous submeasurement statements. -/
structure SubMeas (α : Type*) [Fintype α] (ι : Type*) [Fintype ι] [DecidableEq ι] where
  outcome : α → MIPStarRE.Quantum.Op ι := fun _ => 0
  total : MIPStarRE.Quantum.Op ι := 0
  outcome_pos : ∀ a, 0 ≤ outcome a
  sum_eq_total : ∑ a, outcome a = total
  total_le_one : total ≤ 1

-- source: MIPStarRE/LDT/Basic/SubMeasurementCore.lean:25-28  (MIPStarRE.LDT.Measurement)
/-- A paper-local measurement: a POVM whose PSD effects sum to the identity. -/
structure Measurement (α : Type*) (ι : Type*) [Fintype α] [Fintype ι] [DecidableEq ι]
    extends SubMeas α ι where
  total_eq_one : total = 1

-- source: MIPStarRE/LDT/Basic/ParametersFiniteAnswers.lean:28-39  (MIPStarRE.LDT.linePolynomial_coeff_fin_injective)
/-- A univariate polynomial of `natDegree ≤ n` is determined by its first
`n + 1` coefficients.  Shared injectivity fact behind the finite-answer-space
instances below. -/
theorem linePolynomial_coeff_fin_injective (params : Parameters) [FieldModel params.q]
    {n : ℕ} {p q : LinePolynomialModel params}
    (hp : p.natDegree ≤ n) (hq : q.natDegree ≤ n)
    (h : ∀ i : Fin (n + 1), p.coeff i = q.coeff i) : p = q := by
  ext k
  by_cases hk : k < n + 1
  · exact h ⟨k, hk⟩
  · rw [p.coeff_eq_zero_of_natDegree_lt (hp.trans_lt (by omega)),
      q.coeff_eq_zero_of_natDegree_lt (hq.trans_lt (by omega))]

-- source: MIPStarRE/LDT/Basic/ParametersFiniteAnswers.lean:41-49  (MIPStarRE.LDT.instFintypeAxisLinePolynomial)
/-- Axis-line polynomial answers form a finite type via their bounded coefficient vectors. -/
noncomputable instance (params : Parameters) [FieldModel params.q] :
    Fintype (AxisLinePolynomial params) := by
  classical
  exact Fintype.ofInjective
    (fun f : AxisLinePolynomial params => fun i : Fin (params.d + 1) => f.poly.coeff i)
    fun f g h => AxisLinePolynomial.ext
      (linePolynomial_coeff_fin_injective params f.degreeBounded g.degreeBounded
        fun i => congrFun h i)

-- source: MIPStarRE/LDT/Basic/ParametersFiniteAnswers.lean:51-60  (MIPStarRE.LDT.instFintypeDiagonalLinePolynomial)
/-- Diagonal-line polynomial answers form a finite type via their bounded coefficient vectors. -/
noncomputable instance (params : Parameters) [FieldModel params.q] :
    Fintype (DiagonalLinePolynomial params) := by
  classical
  exact Fintype.ofInjective
    (fun f : DiagonalLinePolynomial params =>
      fun i : Fin (params.m * params.d + 1) => f.poly.coeff i)
    fun f g h => DiagonalLinePolynomial.ext
      (linePolynomial_coeff_fin_injective params f.degreeBounded g.degreeBounded
        fun i => congrFun h i)

-- source: MIPStarRE/LDT/Basic/ParametersFiniteAnswers.lean:62-79  (MIPStarRE.LDT.instFintypePolynomial)
/-- Global low-individual-degree polynomial answers form a finite type, by
injecting into the finite space of degree-restricted multivariate polynomials. -/
noncomputable instance (params : Parameters) [FieldModel params.q] :
    Fintype (Polynomial params) := by
  classical
  letI : Finite (MvPolynomial.restrictDegree (Fin params.m) (Scalar params) params.d) :=
    Module.finite_of_finite (Scalar params)
  letI : Fintype (MvPolynomial.restrictDegree (Fin params.m) (Scalar params) params.d) :=
    Fintype.ofFinite _
  exact Fintype.ofInjective
    (fun g : Polynomial params =>
      (⟨g.poly, by
          rw [MvPolynomial.mem_restrictDegree_iff_sup]
          simpa [MvPolynomial.degreeOf_def] using g.lowIndividualDegree⟩ :
        MvPolynomial.restrictDegree (Fin params.m) (Scalar params) params.d))
    fun g g' h => by
      cases g; cases g'
      simpa using congrArg Subtype.val h

-- source: MIPStarRE/LDT/Basic/SubMeasurementCore.lean:73-76  (MIPStarRE.LDT.ProjMeas)
/-- A paper-local projective measurement (complete POVM + projective). -/
structure ProjMeas (α : Type*) (ι : Type*) [Fintype α] [Fintype ι] [DecidableEq ι]
    extends Measurement α ι where
  proj : ∀ a, outcome a * outcome a = outcome a

-- source: MIPStarRE/LDT/Basic/SubMeasurementFamilies.lean:16-19  (MIPStarRE.LDT.IdxSubMeas)
/-- Question-indexed family of submeasurements. -/
abbrev IdxSubMeas (Question Outcome : Type*) (ι : Type*)
    [Fintype Outcome] [Fintype ι] [DecidableEq ι] :=
  Question → SubMeas Outcome ι

-- source: MIPStarRE/LDT/Basic/SubMeasurementFamilies.lean:31-34  (MIPStarRE.LDT.IdxProjMeas)
/-- Question-indexed family of projective measurements. -/
abbrev IdxProjMeas (Question Outcome : Type*) (ι : Type*)
    [Fintype Outcome] [Fintype ι] [DecidableEq ι] :=
  Question → ProjMeas Outcome ι
namespace IdxProjMeas

-- source: MIPStarRE/LDT/Basic/SubMeasurementFamilies.lean:67-72  (MIPStarRE.LDT.IdxProjMeas.toIdxSubMeas)
/-- Forget both projectivity and completeness from an indexed projective measurement family. -/
def toIdxSubMeas {Question Outcome : Type*} {ι : Type*}
    [Fintype Outcome] [Fintype ι] [DecidableEq ι]
    (A : IdxProjMeas Question Outcome ι) :
    IdxSubMeas Question Outcome ι :=
  fun q => (A q).toSubMeas
end IdxProjMeas

-- source: MIPStarRE/LDT/Basic/SubMeasurementFamilies.lean:76-88  (MIPStarRE.LDT.postprocess)
open scoped Classical in
/-- Post-process the outcomes of a submeasurement. The processed operator at `b` is the
sum of the operators of all `a` with `f a = b`. -/
noncomputable def postprocess {α β : Type*} {ι : Type*} [Fintype ι] [DecidableEq ι]
    [Fintype α] [Fintype β]
    (A : SubMeas α ι) (f : α → β) :
    SubMeas β ι where
  outcome := fun b =>
    ∑ a ∈ Finset.univ.filter (fun a => f a = b), A.outcome a
  total := A.total
  outcome_pos := fun _ => Finset.sum_nonneg fun a _ => A.outcome_pos a
  sum_eq_total := (Finset.sum_fiberwise Finset.univ f A.outcome).trans A.sum_eq_total
  total_le_one := A.total_le_one

-- source: MIPStarRE/LDT/Basic/SubMeasurementFamilies.lean:420-424  (MIPStarRE.LDT.constSubMeasFamily)
/-- Constant indexed family taking the same submeasurement on every question. -/
def constSubMeasFamily {α : Type*} {ι : Type*} [Fintype α] [Fintype ι] [DecidableEq ι]
    (A : SubMeas α ι) :
    IdxSubMeas Unit α ι :=
  fun _ => A

-- source: MIPStarRE/LDT/Test/Defs.lean:18-22  (MIPStarRE.LDT.evaluateAt)
/-- Evaluate a polynomial-valued submeasurement at a point. -/
noncomputable def evaluateAt {ι : Type*} [Fintype ι] [DecidableEq ι]
    (params : Parameters) [FieldModel params.q] (u : Point params)
    (G : SubMeas (Polynomial params) ι) : SubMeas (Fq params) ι :=
  postprocess G (fun g => g u)

-- source: MIPStarRE/LDT/Test/Defs.lean:40-45  (MIPStarRE.LDT.polynomialEvaluationFamily)
/-- View a global polynomial submeasurement as a point-indexed answer family. -/
noncomputable def polynomialEvaluationFamily {ι : Type*} [Fintype ι] [DecidableEq ι]
    (params : Parameters) [FieldModel params.q]
    (G : SubMeas (Polynomial params) ι) :
    IdxSubMeas (Point params) (Fq params) ι :=
  fun u => evaluateAt params u G

-- source: MIPStarRE/LDT/Test/Defs.lean:175-182  (MIPStarRE.LDT.qBipartiteMatchMass)
/-- Bipartite matching mass `∑_a ⟨ψ, (A_a ⊗ B_a) ψ⟩`, with `A` on the left
register and `B` on the right register of a tensor-product state. -/
noncomputable def qBipartiteMatchMass {Outcome : Type*}
    {ιA ιB : Type*} [Fintype ιA] [DecidableEq ιA] [Fintype ιB] [DecidableEq ιB]
    [Fintype Outcome]
    (ψ : QuantumState (ιA × ιB))
    (A : SubMeas Outcome ιA) (B : SubMeas Outcome ιB) : Error :=
  ∑ a, ev ψ (opTensor (A.outcome a) (B.outcome a))

-- source: MIPStarRE/LDT/Test/Defs.lean:184-197  (MIPStarRE.LDT.qBipartiteConsDefect)
/-- Bipartite questionwise consistency defect.

In the paper (Definition 4.8), the consistency of `A` on `H_A` and `B` on
`H_B` for a shared state `|ψ⟩ ∈ H_A ⊗ H_B` is:
  `E_x ∑_{a≠b} ⟨ψ| A^x_a ⊗ B^x_b |ψ⟩ ≤ δ`
which equals
  `max 0 (⟨ψ| A_total ⊗ B_total |ψ⟩ − ∑_a ⟨ψ| A_a ⊗ B_a |ψ⟩)`. -/
noncomputable def qBipartiteConsDefect {Outcome : Type*}
    {ιA ιB : Type*} [Fintype ιA] [DecidableEq ιA] [Fintype ιB] [DecidableEq ιB]
    [Fintype Outcome]
    (ψ : QuantumState (ιA × ιB))
    (A : SubMeas Outcome ιA) (B : SubMeas Outcome ιB) : Error :=
  let totalOverlap := ev ψ (opTensor A.total B.total)
  max 0 (totalOverlap - qBipartiteMatchMass ψ A B)

-- source: MIPStarRE/LDT/Test/Defs.lean:199-206  (MIPStarRE.LDT.bipartiteConsError)
/-- Averaged bipartite off-diagonal mass for consistency statements. -/
noncomputable def bipartiteConsError {Question Outcome : Type*}
    {ιA ιB : Type*} [Fintype ιA] [DecidableEq ιA] [Fintype ιB] [DecidableEq ιB]
    [Fintype Outcome]
    (ψ : QuantumState (ιA × ιB)) (𝒟 : Distribution Question)
    (A : IdxSubMeas Question Outcome ιA)
    (B : IdxSubMeas Question Outcome ιB) : Error :=
  avgOver 𝒟 (fun q => qBipartiteConsDefect ψ (A q) (B q))

-- source: MIPStarRE/LDT/Test/Defs.lean:238-250  (MIPStarRE.LDT.ConsRel)
/-- Consistency relation (bipartite, paper Definition 4.8).

The state `ψ` lives on `H_A ⊗ H_B`, Alice's submeasurement `A` acts on
`H_A`, and Bob's submeasurement `B` acts on `H_B`. The relation encodes
  `E_{x ∼ D} ∑_{a≠b} ⟨ψ| A^x_a ⊗ B^x_b |ψ⟩ ≤ δ`. -/
structure ConsRel {Question Outcome : Type*}
    {ιA ιB : Type*} [Fintype ιA] [DecidableEq ιA] [Fintype ιB] [DecidableEq ιB]
    [Fintype Outcome]
    (ψ : QuantumState (ιA × ιB)) (𝒟 : Distribution Question)
    (A : IdxSubMeas Question Outcome ιA)
    (B : IdxSubMeas Question Outcome ιB)
    (δ : Error) : Prop where
  offDiagonalBound : bipartiteConsError ψ 𝒟 A B ≤ δ

-- source: MIPStarRE/LDT/Test/StrategyCore.lean:162-171  (MIPStarRE.LDT.AxisParallelMeasurementReparamInvariant)
/-- Direct outcome-level covariance for axis-parallel-line measurements.

Rebasing a line question by `t` and reparametrizing an outcome polynomial by
the same translation leaves the corresponding projector unchanged. -/
def AxisParallelMeasurementReparamInvariant (params : Parameters)
    [FieldModel params.q] {ι : Type*} [Fintype ι] [DecidableEq ι]
    (M : IdxProjMeas (AxisParallelLine params) (AxisLinePolynomial params) ι) : Prop :=
  ∀ (ℓ : AxisParallelLine params) (t : Fq params) (f : AxisLinePolynomial params),
    (M (ℓ.rebaseAt t)).outcome (AxisLinePolynomial.reparamAt f t) =
      (M ℓ).outcome f

-- source: MIPStarRE/LDT/Test/StrategyCore.lean:173-182  (MIPStarRE.LDT.DiagonalMeasurementReparamInvariant)
/-- Direct outcome-level covariance for diagonal-line measurements.

Rebasing a line question by `t` and reparametrizing an outcome polynomial by
the same translation leaves the corresponding projector unchanged. -/
def DiagonalMeasurementReparamInvariant (params : Parameters)
    [FieldModel params.q] {ι : Type*} [Fintype ι] [DecidableEq ι]
    (M : IdxProjMeas (DiagonalLine params) (DiagonalLinePolynomial params) ι) : Prop :=
  ∀ (ℓ : DiagonalLine params) (t : Fq params) (f : DiagonalLinePolynomial params),
    (M (ℓ.rebaseAt t)).outcome (DiagonalLinePolynomial.reparamAt f t) =
      (M ℓ).outcome f

-- source: MIPStarRE/LDT/Test/StrategyCore.lean:761-808  (MIPStarRE.LDT.ProjStrat)
/-- Paper-faithful two-space projective strategy data.

This matches the paper's `def:general-projective-strategy`
(`test_definition.tex`, lines 98--115): Alice's and Bob's measurements act on
separate local carriers `ιA` and `ιB`, and the bipartite state lives on
`ιA × ιB` without a built-in swap symmetry.

The `isNormalized` field records that the bipartite state's density operator
has normalized trace `1`.

The four covariance conditions express that the line-indexed projectors
descend from chosen affine parametrizations to geometric lines; transport and
zero-coordinate evaluation are equivalent consequences. -/
structure ProjStrat (params : Parameters) [FieldModel params.q]
    (ιA : Type*) [Fintype ιA] [DecidableEq ιA]
    (ιB : Type*) [Fintype ιB] [DecidableEq ιB] where
  /-- Bipartite state on the tensor product of Alice's and Bob's local carriers. -/
  state : QuantumState (ιA × ιB)
  /-- The bipartite state's density operator is trace-normalized. -/
  isNormalized : state.IsNormalized
  /-- Alice's point-measurement family, acting on `ιA`. -/
  pointMeasurementA : IdxProjMeas (Point params) (Fq params) ιA
  /-- Alice's axis-parallel-line measurement family, acting on `ιA`. -/
  axisParallelMeasurementA :
    IdxProjMeas (AxisParallelLine params) (AxisLinePolynomial params) ιA
  /-- Alice's axis-parallel measurement is covariant under line rebasing. -/
  axisParallelReparamInvariantA :
    AxisParallelMeasurementReparamInvariant params axisParallelMeasurementA
  /-- Alice's diagonal-line measurement family, acting on `ιA`. -/
  diagonalMeasurementA :
    IdxProjMeas (DiagonalLine params) (DiagonalLinePolynomial params) ιA
  /-- Alice's diagonal measurement is covariant under line rebasing. -/
  diagonalReparamInvariantA :
    DiagonalMeasurementReparamInvariant params diagonalMeasurementA
  /-- Bob's point-measurement family, acting on `ιB`. -/
  pointMeasurementB : IdxProjMeas (Point params) (Fq params) ιB
  /-- Bob's axis-parallel-line measurement family, acting on `ιB`. -/
  axisParallelMeasurementB :
    IdxProjMeas (AxisParallelLine params) (AxisLinePolynomial params) ιB
  /-- Bob's axis-parallel measurement is covariant under line rebasing. -/
  axisParallelReparamInvariantB :
    AxisParallelMeasurementReparamInvariant params axisParallelMeasurementB
  /-- Bob's diagonal-line measurement family, acting on `ιB`. -/
  diagonalMeasurementB :
    IdxProjMeas (DiagonalLine params) (DiagonalLinePolynomial params) ιB
  /-- Bob's diagonal measurement is covariant under line rebasing. -/
  diagonalReparamInvariantB :
    DiagonalMeasurementReparamInvariant params diagonalMeasurementB
namespace ProjStrat

-- elaboration context of MIPStarRE/LDT/Test/StrategyBiProj/Measurements.lean
section
open MIPStarRE.Quantum
variable {params : Parameters} [FieldModel params.q]
variable {ιA : Type*} [Fintype ιA] [DecidableEq ιA]
variable {ιB : Type*} [Fintype ιB] [DecidableEq ιB]

-- source: MIPStarRE/LDT/Test/StrategyBiProj/Measurements.lean:455-519  (MIPStarRE.LDT.ProjStrat.lowIndividualDegreeFailureProbability)
/-- Trace-based failure surrogate for the full low-individual-degree test for a
paper-faithful two-space projective strategy.

The three outer summands are respectively axis-parallel consistency, point
agreement, and restricted-diagonal consistency, with outer weight `1 / 3`.
Each line branch averages the two prover-role orderings with weight `1 / 2`, and
the restricted-diagonal branch also averages its restriction index with weight
`1 / m`.  Line answers are evaluated at `zeroCoord`, the parameter value of the
sampled base point. -/
noncomputable def lowIndividualDegreeFailureProbability
    (strategy : ProjStrat params ιA ιB) : Error :=
  let axisPointA : IdxSubMeas (Point params × Fin params.m) (Fq params) ιA :=
    fun s => (strategy.pointMeasurementA s.1).toSubMeas
  let axisPointB : IdxSubMeas (Point params × Fin params.m) (Fq params) ιB :=
    fun s => (strategy.pointMeasurementB s.1).toSubMeas
  let axisLineA : IdxSubMeas (Point params × Fin params.m) (Fq params) ιA :=
    fun s =>
      let ℓ : AxisParallelLine params := { base := s.1, direction := s.2 }
      postprocess ((strategy.axisParallelMeasurementA ℓ).toSubMeas) (· zeroCoord)
  let axisLineB : IdxSubMeas (Point params × Fin params.m) (Fq params) ιB :=
    fun s =>
      let ℓ : AxisParallelLine params := { base := s.1, direction := s.2 }
      postprocess ((strategy.axisParallelMeasurementB ℓ).toSubMeas) (· zeroCoord)
  let extendDirection (j : Fin params.m)
      (freeCoords : Fin (j.val + 1) → Fq params) : Point params :=
    fun k =>
      if h : k.val ≤ j.val then
        freeCoords ⟨k.val, Nat.lt_succ_of_le h⟩
      else zeroCoord
  let diagonalPointA (j : Fin params.m) :
      IdxSubMeas (Point params × (Fin (j.val + 1) → Fq params)) (Fq params) ιA :=
    fun s => (strategy.pointMeasurementA s.1).toSubMeas
  let diagonalPointB (j : Fin params.m) :
      IdxSubMeas (Point params × (Fin (j.val + 1) → Fq params)) (Fq params) ιB :=
    fun s => (strategy.pointMeasurementB s.1).toSubMeas
  let diagonalLineA (j : Fin params.m) :
      IdxSubMeas (Point params × (Fin (j.val + 1) → Fq params)) (Fq params) ιA :=
    fun s =>
      let ℓ : DiagonalLine params := { base := s.1, direction := extendDirection j s.2 }
      postprocess ((strategy.diagonalMeasurementA ℓ).toSubMeas) (· zeroCoord)
  let diagonalLineB (j : Fin params.m) :
      IdxSubMeas (Point params × (Fin (j.val + 1) → Fq params)) (Fq params) ιB :=
    fun s =>
      let ℓ : DiagonalLine params := { base := s.1, direction := extendDirection j s.2 }
      postprocess ((strategy.diagonalMeasurementB ℓ).toSubMeas) (· zeroCoord)
  ((bipartiteConsError strategy.state
        (@uniformDistribution (Point params × Fin params.m) _ _
          ⟨(fun _ => zeroCoord, default)⟩) axisLineA axisPointB +
      bipartiteConsError strategy.state
        (@uniformDistribution (Point params × Fin params.m) _ _
          ⟨(fun _ => zeroCoord, default)⟩) axisPointA axisLineB) / ((2 : ℕ) : Error) +
    bipartiteConsError strategy.state
      (@uniformDistribution (Point params) _ _ ⟨fun _ => zeroCoord⟩)
      (IdxProjMeas.toIdxSubMeas strategy.pointMeasurementA)
      (IdxProjMeas.toIdxSubMeas strategy.pointMeasurementB) +
    ((1 / (params.m : Error)) * ∑ j : Fin params.m,
        bipartiteConsError strategy.state
          (@uniformDistribution (Point params × (Fin (j.val + 1) → Fq params)) _ _
            ⟨(fun _ => zeroCoord, fun _ => zeroCoord)⟩)
          (diagonalLineA j) (diagonalPointB j) +
      (1 / (params.m : Error)) * ∑ j : Fin params.m,
        bipartiteConsError strategy.state
          (@uniformDistribution (Point params × (Fin (j.val + 1) → Fq params)) _ _
            ⟨(fun _ => zeroCoord, fun _ => zeroCoord)⟩)
          (diagonalPointA j) (diagonalLineB j)) / ((2 : ℕ) : Error)) / 3
end  -- module scope
end ProjStrat
end MIPStarRE.LDT

namespace MIPStarRE.LDT
namespace Test

-- source: MIPStarRE/LDT/Test/MainTheorem/MainFormal.lean:288-327  (MIPStarRE.LDT.Test.mainFormal)
/--
Corrected source statement of `thm:main-formal`.

Paper origin: `references/ldt-paper/test_definition.tex:180-202`.

This theorem records the two-space source theorem with the confirmed large-`k`
correction `k ≥ 400 m d`.  The paper prints the weaker hypothesis `k ≥ m d`;
the missing factor `400` is documented in
`docs/paper-gaps/issue-906-main-formal-k-bound.tex`.  The additional condition
`0 < k` corrects the zero-sampling boundary where the printed error collapses
to zero; this boundary is documented in
`docs/paper-gaps/issue-422-main-formal-zero-k-boundary.tex`. -/
theorem mainFormal
    (params : Parameters)
    [FieldModel params.q]
    {ιA ιB : Type*}
    [Fintype ιA] [DecidableEq ιA]
    [Fintype ιB] [DecidableEq ιB]
    (strategy : ProjStrat params ιA ιB)
    (eps : Error)
    (hpass : strategy.lowIndividualDegreeFailureProbability ≤ eps)
    (k : ℕ)
    (hk : 400 * params.m * params.d ≤ k)
    (hk0 : 0 < k) :
    ∃ G_A : ProjMeas (Polynomial params) ιA,
      ∃ G_B : ProjMeas (Polynomial params) ιB,
        ConsRel strategy.state (uniformDistribution (Point params))
            (IdxProjMeas.toIdxSubMeas strategy.pointMeasurementA)
            (polynomialEvaluationFamily params G_B.toSubMeas)
            (mainFormalError params k eps) ∧
          ConsRel strategy.state (uniformDistribution (Point params))
            (polynomialEvaluationFamily params G_A.toSubMeas)
            (IdxProjMeas.toIdxSubMeas strategy.pointMeasurementB)
            (mainFormalError params k eps) ∧
          ConsRel strategy.state (uniformDistribution Unit)
            (constSubMeasFamily G_A.toSubMeas)
            (constSubMeasFamily G_B.toSubMeas)
            (mainFormalError params k eps) := by
  sorry

end Test
end MIPStarRE.LDT
