/-
Copyright (c) 2026 Thomas Vidick. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Vidick
-/
module
public import MIPRE.Background.QLD.Combined
public import MIPRE.Foundations.Pasting

@[expose] public section

/-!
# Uniform averages and two order facts, shared by stages 4 and 5

The analysis of the Pauli basis test averages over uniform points and over the verifier's content,
and compares Born probabilities of nonnegative operators. The few facts of that kind that both
stage 4 (`lem:qld-global-dummy`, `-products`, `-linear`, `-separate`, `-complete`) and stage 5
(`lem:qld-helper` and after) use are collected here, so that stage 5 depends on stage 4 only
through the interface `MIPRE/Background/QLD/Simul.lean`:

* the uniform weights are nonnegative and sum to one (`uniform_nonneg`, `sum_uniform_eq_one`);
* the uniform content, read through its two points, is a pair of independent uniform points
  (`QLD.sum_content_blocks`);
* the Born probability is monotone in the second player's operator when the first player's is
  nonnegative (`bornProb_mono_right`), and a self-adjoint idempotent is nonnegative
  (`posSemidef_of_proj`).

## Stated in a bipartite model

Stated in a bipartite model (Phase 5 of `planning/mipco-track.md`). The two order facts were
statements about matrices with the Loewner order (`Matrix.PosSemidef`); here they are stated in a
bipartite model and in a star-ordered ring, whose order is the one generated by the elements
`z⋆ z` (`StarOrderedRing`). The two combinatorial facts are unchanged.
-/

noncomputable section

namespace MIPRE

open Finset

/-! ## Uniform weights -/

/-- The uniform weights sum to one. -/
theorem sum_uniform_eq_one (X : Type*) [Fintype X] [Nonempty X] : ∑ x, uniform X x = 1 := by
  simp only [uniform, Finset.sum_const, Finset.card_univ, nsmul_eq_mul]
  exact mul_inv_cancel₀ (Nat.cast_ne_zero.mpr Fintype.card_ne_zero)

/-- The uniform weights are nonnegative. -/
theorem uniform_nonneg (X : Type*) [Fintype X] (x : X) : 0 ≤ uniform X x :=
  inv_nonneg.mpr (Nat.cast_nonneg _)

/-! ## Two order facts -/

/-- **A self-adjoint idempotent is nonnegative**, in a star-ordered ring: it is `P⋆ P`. -/
theorem posSemidef_of_proj {R : Type*} [Ring R] [StarRing R] [PartialOrder R] [StarOrderedRing R]
    {P : R} (hsa : star P = P) (hidem : P * P = P) : 0 ≤ P := by
  have : P = star P * P := by rw [hsa, hidem]
  rw [this]
  exact star_mul_self_nonneg P

/-- **The Born probability is monotone in the second player's operator** when the first player's
is nonnegative. -/
theorem bornProb_mono_right {𝒞 𝒜 ℬ : Type*} [Ring 𝒞] [StarRing 𝒞] [Algebra ℂ 𝒞] [Ring 𝒜]
    [StarRing 𝒜] [Algebra ℂ 𝒜] [Ring ℬ] [StarRing ℬ] [Algebra ℂ ℬ] [PartialOrder 𝒜]
    [StarOrderedRing 𝒜] [PartialOrder ℬ] [StarOrderedRing ℬ] (M : BipartiteModel 𝒞 𝒜 ℬ)
    {X : 𝒜} (hX : 0 ≤ X) {Y Y' : ℬ} (h : Y ≤ Y') : M.bornProb X Y ≤ M.bornProb X Y' := by
  have h0 := M.bornProb_nonneg hX (sub_nonneg.mpr h)
  rw [M.bornProb_sub_right] at h0
  linarith

end MIPRE

namespace MIPRE.QLD

open Finset MIPRE.LIDT

/-! ## The verifier's content, read through its two points -/

section ContentBlocks

variable {F : Type*} [Field F] [Fintype F] [DecidableEq F] [Algebra (ZMod 2) F] {m : ℕ} [NeZero m]

/-- The uniform content, read through `(uX, uZ)`, is a pair of independent uniform points. -/
theorem sum_content_blocks (g : Point F m → Point F m → ℝ) :
    ∑ c : Content F m, (Fintype.card (Content F m) : ℝ)⁻¹ * g c.uX c.uZ
      = ∑ x, ∑ z, (uniform (Point F m) x * uniform (Point F m) z) * g x z := by
  have hq : (Fintype.card F : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr Fintype.card_ne_zero
  have hcard : (Fintype.card (Content F m) : ℝ)
      = (Fintype.card F : ℝ) ^ m * (Fintype.card F : ℝ) ^ m * Fintype.card F
        * (Fintype.card F : ℝ) ^ m * (Fintype.card F * Fintype.card F) := by
    rw [Fintype.card_congr contentEquiv]
    simp only [Fintype.card_prod, Fintype.card_fun, Fintype.card_fin]
    push_cast
    ring
  have hsplit : ∑ c : Content F m, g c.uX c.uZ
      = (Fintype.card F : ℝ) * (Fintype.card F : ℝ) ^ m * (Fintype.card F * Fintype.card F)
        * ∑ x, ∑ z, g x z := by
    rw [sum_content_split (fun c => g c.uX c.uZ)]
    simp only [Fintype.sum_prod_type, Finset.sum_const, Finset.card_univ, nsmul_eq_mul,
      Finset.mul_sum]
    refine Finset.sum_congr rfl fun x _ => Finset.sum_congr rfl fun z _ => ?_
    simp only [Fintype.card_prod, Fintype.card_fun, Fintype.card_fin]
    push_cast
    ring
  simp only [uniform, Fintype.card_fun, Fintype.card_fin, Nat.cast_pow, ← Finset.mul_sum]
  rw [hsplit, hcard]
  field_simp

end ContentBlocks

end MIPRE.QLD

end

end
