/-
Copyright (c) 2026 Thomas Vidick. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Vidick
-/
module
public import MIPRE.Foundations.ModelIso

@[expose] public section

/-!
# The commutant of a matrix amplification

The low-individual-degree hypothesis of Phase 5 of `planning/mipco-track.md`,
`LIDT.Simul.SoundCo`, is soundness in the model `S.toModel` of every commuting-operator strategy
`S`; the Pauli basis analysis needs it in the ancilla extensions `S.toModel.expand e`
(`MIPRE/Foundations/AncillaModel.lean`). This file shows that an extension by a unit vector of a
commuting-operator model *is* a commuting-operator model, up to isomorphism
(`BipartiteModel.Iso`, `MIPRE/Foundations/ModelIso.lean`), so that the hypothesis applies to it as
it stands (`LIDT.Simul.SoundCo.expand`, on the `Background` side).

The strategy is `S.expandStrategy e he`, on the space `H ⊗ ℂ^{α × β}` of the extension and in its
state. Only the second player's operators determine the model's algebras, and they are chosen so
that their commutant is exactly the first player's algebra of the extension: the operators
`1_α ⊗ 1_β ⊗ F^y_b` of `S`, the projections `1_α ⊗ |b⟩⟨b| ⊗ 1` onto the basis vectors of the
register `β`, and the projection `1_α ⊗ |u⟩⟨u| ⊗ 1` onto its uniform superposition `u`, each
measured as a two-outcome measurement. The first player asks one question and always gives the
same answer.

An operator `T` on `H ⊗ ℂ^ι` is the operator of the matrix of its compressions,
`T = toCLM (entries T)` (`OperatorMatrix.toCLM_entries`), so commuting with an operator matrix is
matrix algebra (`OperatorMatrix.commute_toCLM_iff`). Then:

* **the commutant of the second register's matrix units** is the first register's matrices
  (`eq_liftLeft_of_commute`), and symmetrically (`eq_liftRight_of_commute`): an `(α × β)`-matrix
  commuting with `1_α ⊗ E_{bb'}` for all `b, b'` is `X ⊗ 1_β`. The matrix units are in the algebra
  generated by the projections the second player measures, since
  `E_{bb'} = |β| E_{bb} |u⟩⟨u| E_{b'b'}` (`commute_liftRight_single_of_commute`);
* **commuting with an amplified operator** `f ⊗ 1` is commuting entrywise with `f`
  (`commute_diagonal_const_iff`). Together, an operator commuting with `f ⊗ 1` for `f ∈ s` and with
  the register's matrix units is `X ⊗ 1` with the entries of `X` in the commutant of `s`
  (`OperatorMatrix.exists_eq_toCLM_liftLeft`, and `OperatorMatrix.exists_eq_toCLM_liftRight` for
  the other register).

So the first player's algebra of the strategy is the image of `M_α(𝒜)`, for `𝒜 = S.aliceAlg`
(`CommutingOperatorStrategy.expandAliceEquiv`). That image contains `M_α(ℂ) ⊗ 1` and `𝒜 ⊗ 1`, so
the same two facts, for the first register, make its commutant the image of `M_β(𝒜')`, and
`𝒜' = S.bobAlg` by definition (`CommutingOperatorStrategy.expandBobEquiv`). Both equivalences are
the representations of the extension, so the identity of the space is an isomorphism of bipartite
models `S.toModel.expand e ≅ (S.expandStrategy e he).toModel`
(`CommutingOperatorStrategy.expandIso`).

`expandStrategy` is not reducible, so that the instances stated for every commuting-operator
strategy, the order of its algebras among them, are found for it; the proofs read it through its
reducible twin `expandStrategyAux`, whose space is seen to be `H ⊗ ℂ^{α × β}` with that space's
own instances.
-/

namespace MIPRE

open scoped InnerProductSpace
open Matrix

/-! ## The entries of an operator on an amplification -/

namespace OperatorMatrix

variable {ι H : Type*} [Fintype ι] [DecidableEq ι] [NormedAddCommGroup H] [InnerProductSpace ℂ H]

/-- **The entries of an operator on the amplification**: the entry `(i, j)` is the compression
`ξ ↦ (T (ξ ⊗ e_j))_i` of `T` from the `j`-th copy of `H` to the `i`-th. -/
noncomputable def entries (T : Ampl ι H →L[ℂ] Ampl ι H) : Matrix ι ι (H →L[ℂ] H) :=
  of fun i j => PiLp.proj 2 (fun _ : ι => H) i ∘L T ∘L emb j

omit [Fintype ι] in
@[simp]
theorem entries_apply (T : Ampl ι H →L[ℂ] Ampl ι H) (i j : ι) (ξ : H) :
    entries T i j ξ = T (emb j ξ) i :=
  rfl

/-- A vector of the amplification is the sum of its coordinates, embedded. -/
theorem sum_emb (f : Ampl ι H) : ∑ j, emb j (f j) = f := by
  ext i
  rw [WithLp.ofLp_sum, Finset.sum_apply, Finset.sum_eq_single i]
  · exact emb_apply_self i (f i)
  · intro j _ hj
    exact emb_apply_of_ne (Ne.symm hj) _
  · intro h
    exact absurd (Finset.mem_univ i) h

/-- **An operator is the operator of its entries.** -/
theorem toCLM_entries (T : Ampl ι H →L[ℂ] Ampl ι H) : toCLM (entries T) = T := by
  ext f i
  rw [toCLM_apply]
  simp only [entries_apply]
  have h := congrArg (fun g : Ampl ι H => g i) (congrArg T (sum_emb f))
  simp only [map_sum, WithLp.ofLp_sum, Finset.sum_apply] at h
  exact h

/-- **The entries of the operator of a matrix are the matrix.** -/
theorem entries_toCLM (M : Matrix ι ι (H →L[ℂ] H)) : entries (toCLM M) = M := by
  ext i j ξ
  rw [entries_apply, toCLM_apply, Finset.sum_eq_single j]
  · rw [emb_apply_self]
  · intro k _ hk
    rw [emb_apply_of_ne hk, map_zero]
  · intro h
    exact absurd (Finset.mem_univ j) h

theorem toCLM_injective : Function.Injective (toCLM : Matrix ι ι (H →L[ℂ] H) → _) :=
  Function.LeftInverse.injective entries_toCLM

/-- **An operator commutes with the operator of a matrix exactly when its entries do.** -/
theorem commute_toCLM_iff (T : Ampl ι H →L[ℂ] Ampl ι H) (Z : Matrix ι ι (H →L[ℂ] H)) :
    Commute T (toCLM Z) ↔ Commute (entries T) Z := by
  conv_lhs => rw [← toCLM_entries T]
  rw [Commute, SemiconjBy, ← toCLM_mul, ← toCLM_mul, toCLM_injective.eq_iff]
  rfl

end OperatorMatrix

/-! ## Matrices commuting with a register -/

section Register

variable {R α β : Type*} [Ring R] [Fintype α] [DecidableEq α] [Fintype β] [DecidableEq β]

/-- **A matrix commutes with a constant diagonal matrix exactly when its entries commute with the
constant.** -/
theorem commute_diagonal_const_iff {ι : Type*} [Fintype ι] [DecidableEq ι] (T : Matrix ι ι R)
    (f : R) : Commute T (diagonal fun _ : ι => f) ↔ ∀ i j, Commute (T i j) f := by
  refine ⟨fun h i j => ?_, fun h => ?_⟩
  · have := congrFun (congrFun h.eq i) j
    rwa [mul_diagonal, diagonal_mul] at this
  · ext i j
    rw [mul_diagonal, diagonal_mul]
    exact (h i j).eq

variable [StarRing R] [Algebra ℂ R]

/-- A constant diagonal matrix of the first register acts on the pair as the constant diagonal. -/
theorem liftLeft_diagonal_const (c : R) :
    liftLeft (β := β) (diagonal fun _ : α => c) = diagonal fun _ : α × β => c := by
  ext p q
  rw [liftLeft_apply, diagonal_apply, diagonal_apply]
  by_cases h2 : p.2 = q.2
  · rw [ite_eq_left h2]
    by_cases h1 : p.1 = q.1
    · rw [ite_eq_left h1, ite_eq_left (Prod.ext h1 h2)]
    · rw [ite_eq_right h1, ite_eq_right fun h => h1 (congrArg Prod.fst h)]
  · rw [ite_eq_right h2, ite_eq_right fun h => h2 (congrArg Prod.snd h)]

/-- A constant diagonal matrix of the second register acts on the pair as the constant diagonal. -/
theorem liftRight_diagonal_const (c : R) :
    liftRight (α := α) (diagonal fun _ : β => c) = diagonal fun _ : α × β => c := by
  ext p q
  rw [liftRight_apply, diagonal_apply, diagonal_apply]
  by_cases h1 : p.1 = q.1
  · rw [ite_eq_left h1]
    by_cases h2 : p.2 = q.2
    · rw [ite_eq_left h2, ite_eq_left (Prod.ext h1 h2)]
    · rw [ite_eq_right h2, ite_eq_right fun h => h2 (congrArg Prod.snd h)]
  · rw [ite_eq_right h1, ite_eq_right fun h => h1 (congrArg Prod.fst h)]

/-- **The two registers' matrices commute when their entries do.** -/
theorem commute_liftLeft_liftRight (X : Matrix α α R) (Y : Matrix β β R)
    (h : ∀ a a' b b', Commute (X a a') (Y b b')) :
    Commute (liftLeft (β := β) X) (liftRight (α := α) Y) := by
  show _ * _ = _ * _
  ext p q
  rw [liftLeft_mul_liftRight, liftRight_mul_liftLeft]
  exact (h _ _ _ _).eq

theorem mul_liftRight_single_apply (T : Matrix (α × β) (α × β) R) (b b' : β) (p q : α × β) :
    (T * liftRight (α := α) (single b b' (1 : R))) p q =
      if q.2 = b' then T p (q.1, b) else 0 := by
  rw [mul_apply, Finset.sum_eq_single (q.1, b)]
  · rw [liftRight_apply, ite_eq_left rfl, single_apply]
    by_cases h : q.2 = b'
    · rw [ite_eq_left ⟨rfl, h.symm⟩, ite_eq_left h, mul_one]
    · rw [ite_eq_right (fun h' => h h'.2.symm), ite_eq_right h, mul_zero]
  · intro r _ hr
    rw [liftRight_apply]
    by_cases h1 : r.1 = q.1
    · rw [ite_eq_left h1, single_apply, ite_eq_right (fun h' => hr (Prod.ext h1 h'.1.symm)),
        mul_zero]
    · rw [ite_eq_right h1, mul_zero]
  · intro h
    exact absurd (Finset.mem_univ _) h

theorem liftRight_single_mul_apply (T : Matrix (α × β) (α × β) R) (b b' : β) (p q : α × β) :
    (liftRight (α := α) (single b b' (1 : R)) * T) p q =
      if p.2 = b then T (p.1, b') q else 0 := by
  rw [mul_apply, Finset.sum_eq_single (p.1, b')]
  · rw [liftRight_apply, ite_eq_left rfl, single_apply]
    by_cases h : p.2 = b
    · rw [ite_eq_left ⟨h.symm, rfl⟩, ite_eq_left h, one_mul]
    · rw [ite_eq_right (fun h' => h h'.1.symm), ite_eq_right h, zero_mul]
  · intro r _ hr
    rw [liftRight_apply]
    by_cases h1 : p.1 = r.1
    · rw [ite_eq_left h1, single_apply,
        ite_eq_right (fun h' => hr (Prod.ext h1.symm h'.2.symm)), zero_mul]
    · rw [ite_eq_right h1, zero_mul]
  · intro h
    exact absurd (Finset.mem_univ _) h

theorem mul_liftLeft_single_apply (T : Matrix (α × β) (α × β) R) (a a' : α) (p q : α × β) :
    (T * liftLeft (β := β) (single a a' (1 : R))) p q =
      if q.1 = a' then T p (a, q.2) else 0 := by
  rw [mul_apply, Finset.sum_eq_single (a, q.2)]
  · rw [liftLeft_apply, ite_eq_left rfl, single_apply]
    by_cases h : q.1 = a'
    · rw [ite_eq_left ⟨rfl, h.symm⟩, ite_eq_left h, mul_one]
    · rw [ite_eq_right (fun h' => h h'.2.symm), ite_eq_right h, mul_zero]
  · intro r _ hr
    rw [liftLeft_apply]
    by_cases h2 : r.2 = q.2
    · rw [ite_eq_left h2, single_apply, ite_eq_right (fun h' => hr (Prod.ext h'.1.symm h2)),
        mul_zero]
    · rw [ite_eq_right h2, mul_zero]
  · intro h
    exact absurd (Finset.mem_univ _) h

theorem liftLeft_single_mul_apply (T : Matrix (α × β) (α × β) R) (a a' : α) (p q : α × β) :
    (liftLeft (β := β) (single a a' (1 : R)) * T) p q =
      if p.1 = a then T (a', p.2) q else 0 := by
  rw [mul_apply, Finset.sum_eq_single (a', p.2)]
  · rw [liftLeft_apply, ite_eq_left rfl, single_apply]
    by_cases h : p.1 = a
    · rw [ite_eq_left ⟨h.symm, rfl⟩, ite_eq_left h, one_mul]
    · rw [ite_eq_right (fun h' => h h'.1.symm), ite_eq_right h, zero_mul]
  · intro r _ hr
    rw [liftLeft_apply]
    by_cases h2 : p.2 = r.2
    · rw [ite_eq_left h2, single_apply,
        ite_eq_right (fun h' => hr (Prod.ext h'.2.symm h2.symm)), zero_mul]
    · rw [ite_eq_right h2, zero_mul]
  · intro h
    exact absurd (Finset.mem_univ _) h

/-- **The commutant of the second register's matrix units is the first register's matrices**: a
matrix commuting with every `1_α ⊗ E_{bb'}` is `X ⊗ 1_β`, with `X` its block at any `b₀`. -/
theorem eq_liftLeft_of_commute {T : Matrix (α × β) (α × β) R}
    (hT : ∀ b b', Commute T (liftRight (α := α) (single b b' (1 : R)))) (b₀ : β) :
    T = liftLeft (of fun a a' => T (a, b₀) (a', b₀)) := by
  ext ⟨a, b⟩ ⟨a', b'⟩
  rw [liftLeft_apply]
  by_cases h : b = b'
  · subst h
    have key := congrFun (congrFun (hT b₀ b).eq (a, b₀)) (a', b)
    rw [mul_liftRight_single_apply, liftRight_single_mul_apply, ite_eq_left rfl,
      ite_eq_left rfl] at key
    rw [ite_eq_left rfl, of_apply, key]
  · have key := congrFun (congrFun (hT b' b').eq (a, b)) (a', b')
    rw [mul_liftRight_single_apply, liftRight_single_mul_apply, ite_eq_left rfl,
      ite_eq_right h] at key
    rw [ite_eq_right h]
    exact key

/-- **The commutant of the first register's matrix units is the second register's matrices**: a
matrix commuting with every `E_{aa'} ⊗ 1_β` is `1_α ⊗ Y`, with `Y` its block at any `a₀`. -/
theorem eq_liftRight_of_commute {T : Matrix (α × β) (α × β) R}
    (hT : ∀ a a', Commute T (liftLeft (β := β) (single a a' (1 : R)))) (a₀ : α) :
    T = liftRight (of fun b b' => T (a₀, b) (a₀, b')) := by
  ext ⟨a, b⟩ ⟨a', b'⟩
  rw [liftRight_apply]
  by_cases h : a = a'
  · subst h
    have key := congrFun (congrFun (hT a₀ a).eq (a₀, b)) (a, b')
    rw [mul_liftLeft_single_apply, liftLeft_single_mul_apply, ite_eq_left rfl,
      ite_eq_left rfl] at key
    rw [ite_eq_left rfl, of_apply, key]
  · have key := congrFun (congrFun (hT a' a').eq (a, b)) (a', b')
    rw [mul_liftLeft_single_apply, liftLeft_single_mul_apply, ite_eq_left rfl,
      ite_eq_right h] at key
    rw [ite_eq_right h]
    exact key

end Register

/-! ## The projections of a register that generate its matrices -/

section Uniform

variable (β : Type*) [Fintype β] [DecidableEq β]

/-- The projection `|u⟩⟨u|` onto the uniform superposition `u = |β|^{-1/2} ∑_b |b⟩` of a
register: every entry is `1 / |β|`. -/
noncomputable def uniformProj : Matrix β β ℂ :=
  of fun _ _ => (Fintype.card β : ℂ)⁻¹

omit [DecidableEq β] in
theorem isStarProjection_uniformProj : IsStarProjection (uniformProj β) := by
  refine ⟨?_, ?_⟩
  · rcases isEmpty_or_nonempty β with hβ | hβ
    · exact Subsingleton.elim _ _
    · have hn : (Fintype.card β : ℂ) ≠ 0 := Nat.cast_ne_zero.2 Fintype.card_ne_zero
      rw [IsIdempotentElem]
      ext b b'
      simp only [uniformProj, mul_apply, of_apply, Finset.sum_const, Finset.card_univ,
        nsmul_eq_mul]
      field_simp
  · rw [IsSelfAdjoint, star_eq_conjTranspose]
    ext b b'
    simp [uniformProj]

variable {β}

theorem isStarProjection_single_one (b : β) : IsStarProjection (single b b (1 : ℂ)) := by
  refine ⟨?_, ?_⟩
  · rw [IsIdempotentElem, single_mul_single_same, one_mul]
  · rw [IsSelfAdjoint, star_eq_conjTranspose, conjTranspose_single, star_one]

/-- **A matrix unit from the diagonal projections and the uniform one**:
`E_{bb'} = |β| E_{bb} |u⟩⟨u| E_{b'b'}`. -/
theorem single_eq_smul_mul_uniformProj_mul (b b' : β) :
    single b b' (1 : ℂ) =
      (Fintype.card β : ℂ) • (single b b 1 * uniformProj β * single b' b' 1) := by
  have : Nonempty β := ⟨b⟩
  have hn : (Fintype.card β : ℂ) ≠ 0 := Nat.cast_ne_zero.2 Fintype.card_ne_zero
  rw [single_mul_mul_single, smul_single, uniformProj, of_apply, one_mul, mul_one, smul_eq_mul,
    mul_inv_cancel₀ hn]

variable {R α : Type*} [Ring R] [StarRing R] [Algebra ℂ R] [Fintype α] [DecidableEq α]

/-- **Commuting with the diagonal and the uniform projections of the second register is commuting
with its matrix units.** -/
theorem commute_liftRight_single_of_commute {Z : Matrix (α × β) (α × β) R}
    (hdiag : ∀ b, Commute Z (liftRight (α := α) ((single b b (1 : ℂ)).map (algebraMap ℂ R))))
    (hunif : Commute Z (liftRight (α := α) ((uniformProj β).map (algebraMap ℂ R))))
    (b b' : β) : Commute Z (liftRight (α := α) (single b b' (1 : R))) := by
  let ρ : Matrix β β ℂ →ₐ[ℂ] Matrix (α × β) (α × β) R :=
    (liftRight (α := α) (β := β) (R := R)).toAlgHom.comp (Algebra.ofId ℂ R).mapMatrix
  have hρ : ∀ P, ρ P = liftRight (α := α) (P.map (algebraMap ℂ R)) := fun P => rfl
  have h1 : liftRight (α := α) (single b b' (1 : R)) = ρ (single b b' 1) := by
    rw [hρ, map_single, map_one]
  rw [h1, single_eq_smul_mul_uniformProj_mul, map_smul, map_mul, map_mul, hρ, hρ, hρ]
  exact (((hdiag b).mul_right hunif).mul_right (hdiag b')).smul_right _

end Uniform

/-! ## The commutant of an amplification, as operators -/

namespace OperatorMatrix

variable {H α β : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
  [Fintype α] [DecidableEq α] [Fintype β] [DecidableEq β]

/-- **The two registers' operators commute when their entries do.** -/
theorem commute_toCLM_liftLeft_liftRight (X : Matrix α α (H →L[ℂ] H))
    (Y : Matrix β β (H →L[ℂ] H)) (h : ∀ a a' b b', Commute (X a a') (Y b b')) :
    Commute (toCLM (liftLeft (β := β) X)) (toCLM (liftRight (α := α) Y)) := by
  rw [Commute, SemiconjBy, ← toCLM_mul, ← toCLM_mul, (commute_liftLeft_liftRight X Y h).eq]

/-- **An operator commuting with the second register and with an amplified set is a matrix of the
first register over the commutant of the set**: if `T` on `H ⊗ ℂ^{α × β}` commutes with `f ⊗ 1`
for every `f ∈ s` and with `1 ⊗ 1_α ⊗ E_{bb'}` for all `b, b'`, then `T = X ⊗ 1_β` with every
entry of `X` commuting with `s`. -/
theorem exists_eq_toCLM_liftLeft [Nonempty β] {s : Set (H →L[ℂ] H)}
    {T : Ampl (α × β) H →L[ℂ] Ampl (α × β) H}
    (hs : ∀ f ∈ s, Commute T (toCLM (diagonal fun _ : α × β => f)))
    (hreg : ∀ b b', Commute T (toCLM (liftRight (α := α) (single b b' (1 : H →L[ℂ] H))))) :
    ∃ X : Matrix α α (H →L[ℂ] H), (∀ a a', ∀ f ∈ s, Commute (X a a') f) ∧
      T = toCLM (liftLeft X) := by
  obtain ⟨b₀⟩ := ‹Nonempty β›
  have hT : ∀ b b', Commute (entries T) (liftRight (α := α) (single b b' (1 : H →L[ℂ] H))) :=
    fun b b' => (commute_toCLM_iff T _).1 (hreg b b')
  have hX := eq_liftLeft_of_commute hT b₀
  refine ⟨of fun a a' => entries T (a, b₀) (a', b₀), fun a a' f hf => ?_, ?_⟩
  · exact (commute_diagonal_const_iff (entries T) f).1
      ((commute_toCLM_iff T (diagonal fun _ : α × β => f)).1 (hs f hf)) (a, b₀) (a', b₀)
  · rw [← hX, toCLM_entries]

/-- **An operator commuting with the first register and with an amplified set is a matrix of the
second register over the commutant of the set**: the mirror of `exists_eq_toCLM_liftLeft`. -/
theorem exists_eq_toCLM_liftRight [Nonempty α] {s : Set (H →L[ℂ] H)}
    {T : Ampl (α × β) H →L[ℂ] Ampl (α × β) H}
    (hs : ∀ f ∈ s, Commute T (toCLM (diagonal fun _ : α × β => f)))
    (hreg : ∀ a a', Commute T (toCLM (liftLeft (β := β) (single a a' (1 : H →L[ℂ] H))))) :
    ∃ Y : Matrix β β (H →L[ℂ] H), (∀ b b', ∀ f ∈ s, Commute (Y b b') f) ∧
      T = toCLM (liftRight Y) := by
  obtain ⟨a₀⟩ := ‹Nonempty α›
  have hT : ∀ a a', Commute (entries T) (liftLeft (β := β) (single a a' (1 : H →L[ℂ] H))) :=
    fun a a' => (commute_toCLM_iff T _).1 (hreg a a')
  have hY := eq_liftRight_of_commute hT a₀
  refine ⟨of fun b b' => entries T (a₀, b) (a₀, b'), fun b b' f hf => ?_, ?_⟩
  · exact (commute_diagonal_const_iff (entries T) f).1
      ((commute_toCLM_iff T (diagonal fun _ : α × β => f)).1 (hs f hf)) (a₀, b) (a₀, b')
  · rw [← hY, toCLM_entries]

/-- The first register's matrices act injectively, when the second register is not empty. -/
theorem toCLM_liftLeft_injective [Nonempty β] :
    Function.Injective fun X : Matrix α α (H →L[ℂ] H) => toCLM (liftLeft (β := β) X) := by
  obtain ⟨b₀⟩ := ‹Nonempty β›
  intro X X' h
  have h' : liftLeft (β := β) X = liftLeft X' := toCLM_injective h
  refine Matrix.ext fun a a' => ?_
  have := congrFun (congrFun h' (a, b₀)) (a', b₀)
  rwa [liftLeft_apply, liftLeft_apply, ite_eq_left rfl, ite_eq_left rfl] at this

/-- The second register's matrices act injectively, when the first register is not empty. -/
theorem toCLM_liftRight_injective [Nonempty α] :
    Function.Injective fun Y : Matrix β β (H →L[ℂ] H) => toCLM (liftRight (α := α) Y) := by
  obtain ⟨a₀⟩ := ‹Nonempty α›
  intro Y Y' h
  have h' : liftRight (α := α) Y = liftRight Y' := toCLM_injective h
  refine Matrix.ext fun b b' => ?_
  have := congrFun (congrFun h' (a₀, b)) (a₀, b')
  rwa [liftRight_apply, liftRight_apply, ite_eq_left rfl, ite_eq_left rfl] at this

end OperatorMatrix

/-- An element commuting with a star-closed set lies in its commutant. -/
theorem mem_centralizer_of_forall_commute {A : Type*} [Ring A] [StarRing A] [Algebra ℂ A]
    [StarModule ℂ A] {s : Set A} (hs : ∀ f ∈ s, star f ∈ s) {x : A}
    (hx : ∀ f ∈ s, Commute x f) : x ∈ StarSubalgebra.centralizer ℂ s := by
  rw [StarSubalgebra.mem_centralizer_iff]
  exact fun g hg => ⟨(hx g hg).eq.symm, (hx _ (hs g hg)).eq.symm⟩

/-- A unit vector of `ℂ^{α × β}` has both registers nonempty. -/
theorem nonempty_of_norm_evec_eq_one {α β : Type*} [Fintype α] [Fintype β] {e : α × β → ℂ}
    (he : ‖evec e‖ = 1) : Nonempty α ∧ Nonempty β := by
  have hne : Nonempty (α × β) := by
    by_contra h
    rw [not_nonempty_iff] at h
    have h2 := norm_evec_sq e
    rw [he, dotProduct, Finset.univ_eq_empty, Finset.sum_empty] at h2
    norm_num at h2
  exact ⟨⟨hne.some.1⟩, ⟨hne.some.2⟩⟩

/-- The two-outcome measurement `{P, 1 - P}` of an element `P`, the outcome `true` for `P`. -/
def twoOutcome {R : Type*} [Ring R] (P : R) (t : Bool) : R :=
  if t then P else 1 - P

theorem isStarProjection_twoOutcome {R : Type*} [Ring R] [StarRing R] {P : R}
    (hP : IsStarProjection P) (t : Bool) : IsStarProjection (twoOutcome P t) := by
  cases t
  · exact hP.one_sub
  · exact hP

theorem sum_twoOutcome {R : Type*} [Ring R] (P : R) : ∑ t, twoOutcome P t = 1 := by
  rw [Fintype.sum_bool]
  simp [twoOutcome]

/-! ## The strategy of an ancilla extension -/

namespace CommutingOperatorStrategy

open OperatorMatrix

variable {X Y A B : Type*} [Fintype X] [Fintype Y] [Fintype A] [Fintype B]
variable {α β : Type} [Fintype α] [DecidableEq α] [Fintype β] [DecidableEq β]

/-- The projections of the register `β` that the second player of an extension measures: `none`
the projection onto the uniform superposition, `some b` the projection onto the basis vector
`b`. -/
noncomputable def expandRegProj : Option β → Matrix β β ℂ
  | none => uniformProj β
  | some b => single b b 1

theorem isStarProjection_expandRegProj (g : Option β) : IsStarProjection (expandRegProj g) := by
  cases g with
  | none => exact isStarProjection_uniformProj β
  | some b => exact isStarProjection_single_one b

/-- **The second player's operators of the ancilla strategy**, as matrices over `B(H)` on the
register `β` (the first register acting trivially): to a question `y` of `S`, the amplified
`S.F y b`; to a question `g` about the register, the two-outcome measurement of
`expandRegProj g`. -/
noncomputable def expandBobMat (S : CommutingOperatorStrategy X Y A B) :
    Y ⊕ Option β → B ⊕ Bool → Matrix β β (S.H →L[ℂ] S.H)
  | .inl y, .inl b => scalar β (S.F y b)
  | .inr g, .inr t =>
    mapMatrixStarAlgHom (StarAlgHom.ofId ℂ (S.H →L[ℂ] S.H)) (twoOutcome (expandRegProj g) t)
  | .inl _, .inr _ => 0
  | .inr _, .inl _ => 0

variable (S : CommutingOperatorStrategy X Y A B)

theorem expandBobMat_inl_inl (y : Y) (b : B) :
    S.expandBobMat (β := β) (.inl y) (.inl b) = diagonal fun _ => S.F y b :=
  rfl

theorem expandBobMat_inr_inr (g : Option β) (t : Bool) :
    S.expandBobMat (.inr g) (.inr t) =
      (twoOutcome (expandRegProj g) t).map (algebraMap ℂ (S.H →L[ℂ] S.H)) :=
  rfl

theorem expandBobMat_inl_inr (y : Y) (t : Bool) :
    S.expandBobMat (β := β) (.inl y) (.inr t) = 0 :=
  rfl

theorem expandBobMat_inr_inl (g : Option β) (b : B) : S.expandBobMat (.inr g) (.inl b) = 0 :=
  rfl

/-- The entries of the second player's operators commute with the first player's algebra. -/
theorem commute_expandBobMat_apply {x : S.H →L[ℂ] S.H} (hx : x ∈ S.aliceAlg)
    (y : Y ⊕ Option β) (b : B ⊕ Bool) (b₁ b₂ : β) : Commute x (S.expandBobMat y b b₁ b₂) := by
  match y, b with
  | .inl y, .inl b =>
    rw [expandBobMat_inl_inl, diagonal_apply]
    split_ifs
    · exact ((StarSubalgebra.mem_centralizer_iff ℂ).1 hx _ ⟨(y, b), rfl⟩).1.symm
    · exact Commute.zero_right x
  | .inr g, .inr t =>
    rw [expandBobMat_inr_inr, map_apply]
    exact Algebra.commute_algebraMap_right _ x
  | .inl _, .inr _ => exact Commute.zero_right x
  | .inr _, .inl _ => exact Commute.zero_right x

theorem isPositive_toCLM_liftRight_expandBobMat (y : Y ⊕ Option β) (b : B ⊕ Bool) :
    (toCLM (liftRight (α := α) (S.expandBobMat y b))).IsPositive := by
  match y, b with
  | .inl y, .inl b =>
    rw [expandBobMat_inl_inl, liftRight_diagonal_const]
    exact isPositive_toCLM_diagonal (S.F_pos y b)
  | .inr g, .inr t =>
    exact isPositive_toCLM_of_isStarProjection
      ((isStarProjection_twoOutcome (isStarProjection_expandRegProj g) t).map
        ((liftRight (α := α) (β := β) (R := S.H →L[ℂ] S.H)).comp
          (mapMatrixStarAlgHom (StarAlgHom.ofId ℂ (S.H →L[ℂ] S.H)))))
  | .inl y, .inr t =>
    rw [expandBobMat_inl_inr, map_zero, toCLM_zero]
    exact ContinuousLinearMap.isPositive_zero
  | .inr g, .inl b =>
    rw [expandBobMat_inr_inl, map_zero, toCLM_zero]
    exact ContinuousLinearMap.isPositive_zero

theorem sum_expandBobMat (y : Y ⊕ Option β) : ∑ b, S.expandBobMat y b = 1 := by
  rw [Fintype.sum_sum_type]
  cases y with
  | inl y =>
    simp only [expandBobMat, Finset.sum_const_zero, add_zero]
    rw [← map_sum, S.F_sum, map_one]
  | inr g =>
    simp only [expandBobMat, Finset.sum_const_zero, zero_add]
    rw [← map_sum, sum_twoOutcome, map_one]

theorem sum_toCLM_liftRight_expandBobMat (y : Y ⊕ Option β) :
    ∑ b, toCLM (liftRight (α := α) (S.expandBobMat y b)) = 1 := by
  have h : ∀ Z : Matrix β β (S.H →L[ℂ] S.H), toCLM (liftRight (α := α) Z) =
      ((toCLMStarAlgHom (ι := α × β) (H := S.H)).comp
        (liftRight (α := α) (β := β) (R := S.H →L[ℂ] S.H))) Z := fun _ => rfl
  simp_rw [h]
  rw [← map_sum, sum_expandBobMat, map_one]

/-- `expandStrategy`, reducibly: the proofs below read its space as `H ⊗ ℂ^{α × β}` with that
space's own instances, which is what lets its operators be compared with operator matrices.
`expandStrategy` itself is not reducible, so that instances stated for every commuting-operator
strategy (the order of its algebras, for example) are found for it. -/
noncomputable abbrev expandStrategyAux (e : α × β → ℂ) (he : ‖evec e‖ = 1) :
    CommutingOperatorStrategy Unit (Y ⊕ Option β) Unit (B ⊕ Bool) where
  H := Ampl (α × β) S.H
  ψ := WithLp.toLp 2 fun p => e p • S.ψ
  ψ_norm := (S.toModel.norm_expand_state e).trans (by rw [S.toModel_ψ_norm, he, mul_one])
  E _ _ := 1
  F y b := toCLM (liftRight (α := α) (S.expandBobMat y b))
  E_pos _ _ := ContinuousLinearMap.isPositive_one
  F_pos := S.isPositive_toCLM_liftRight_expandBobMat
  E_sum _ := by rw [Fintype.sum_unique]
  F_sum := S.sum_toCLM_liftRight_expandBobMat
  commutes _ _ _ _ := Commute.one_left _

/-- **The commuting-operator strategy of an ancilla extension** of `S` by registers `α`, `β` in
the unit state `e`: the space `H ⊗ ℂ^{α × β}` and the state `ψ ⊗ e` of `S.toModel.expand e`; the
first player asks one question and always gives the same answer, with the operator `1`; the second
player answers a question `y` of `S` with the operators `1_α ⊗ 1_β ⊗ F^y_b`, and a question
`g : Option β` about the register with the two-outcome measurement of `expandRegProj g`. -/
noncomputable def expandStrategy (e : α × β → ℂ) (he : ‖evec e‖ = 1) :
    CommutingOperatorStrategy Unit (Y ⊕ Option β) Unit (B ⊕ Bool) :=
  S.expandStrategyAux e he

/-- The first player's matrices of an extension, as operators on `H ⊗ ℂ^{α × β}`: `X ⊗ 1_β`. -/
noncomputable def expandAliceRep :
    Matrix α α S.aliceAlg →⋆ₐ[ℂ] (Ampl (α × β) S.H →L[ℂ] Ampl (α × β) S.H) :=
  toCLMStarAlgHom.comp (liftLeft.comp (mapMatrixStarAlgHom S.aliceAlg.subtype))

/-- The second player's matrices of an extension, as operators on `H ⊗ ℂ^{α × β}`: `1_α ⊗ Y`. -/
noncomputable def expandBobRep :
    Matrix β β S.bobAlg →⋆ₐ[ℂ] (Ampl (α × β) S.H →L[ℂ] Ampl (α × β) S.H) :=
  toCLMStarAlgHom.comp (liftRight.comp (mapMatrixStarAlgHom S.bobAlg.subtype))

theorem expandAliceRep_apply (X : Matrix α α S.aliceAlg) :
    S.expandAliceRep (β := β) X = toCLM (liftLeft (X.map S.aliceAlg.subtype)) :=
  rfl

theorem expandBobRep_apply (Y : Matrix β β S.bobAlg) :
    S.expandBobRep (α := α) Y = toCLM (liftRight (Y.map S.bobAlg.subtype)) :=
  rfl

variable (e : α × β → ℂ) (he : ‖evec e‖ = 1)

/-- **`expandAliceRep` is the first player's representation of the extension.** -/
theorem expandAliceRep_eq (X : Matrix α α S.aliceAlg) :
    S.expandAliceRep X = (S.toModel.expand e).π ((S.toModel.expand e).πA X) :=
  rfl

/-- **`expandBobRep` is the second player's representation of the extension.** -/
theorem expandBobRep_eq (Y : Matrix β β S.bobAlg) :
    S.expandBobRep Y = (S.toModel.expand e).π ((S.toModel.expand e).πB Y) :=
  rfl

/-- The first player's operators of the extension are in the first player's algebra of the
strategy: they commute with the second player's operators. -/
theorem expandAliceRep_mem (X : Matrix α α S.aliceAlg) :
    S.expandAliceRep X ∈ (S.expandStrategy e he).aliceAlg := by
  show S.expandAliceRep X ∈ (S.expandStrategyAux e he).aliceAlg
  refine mem_centralizer_of_forall_commute ?_ ?_
  · rintro _ ⟨⟨y, b⟩, rfl⟩
    exact ⟨(y, b), ((S.expandStrategyAux e he).F_pos y b).isSelfAdjoint.star_eq.symm⟩
  · rintro _ ⟨⟨y, b⟩, rfl⟩
    exact commute_toCLM_liftLeft_liftRight (X.map S.aliceAlg.subtype) (S.expandBobMat y b)
      fun a a' b₁ b₂ => S.commute_expandBobMat_apply (X a a').2 y b b₁ b₂

/-- **The first player's algebra of the strategy is the first player's algebra of the
extension**: every operator commuting with the second player's operators is `X ⊗ 1_β` for a matrix
`X` over the commutant of `S`'s second player. -/
theorem exists_expandAliceRep_eq {T : Ampl (α × β) S.H →L[ℂ] Ampl (α × β) S.H}
    (hT : T ∈ (S.expandStrategy e he).aliceAlg) : ∃ X, S.expandAliceRep X = T := by
  change T ∈ (S.expandStrategyAux e he).aliceAlg at hT
  have := (nonempty_of_norm_evec_eq_one he).2
  have hc : ∀ y b, Commute T (toCLM (liftRight (α := α) (S.expandBobMat y b))) := fun y b =>
    ((StarSubalgebra.mem_centralizer_iff ℂ).1 hT _ ⟨(y, b), rfl⟩).1.symm
  have hs : ∀ f ∈ Set.range fun p : Y × B => S.F p.1 p.2,
      Commute T (toCLM (diagonal fun _ : α × β => f)) := by
    rintro _ ⟨⟨y, b⟩, rfl⟩
    have h := hc (.inl y) (.inl b)
    rwa [expandBobMat_inl_inl, liftRight_diagonal_const] at h
  have hreg : ∀ b b', Commute T (toCLM (liftRight (α := α) (single b b' (1 : S.H →L[ℂ] S.H)))) := by
    intro b b'
    rw [commute_toCLM_iff]
    refine commute_liftRight_single_of_commute (fun b₁ => ?_) ?_ b b'
    · have h := hc (.inr (some b₁)) (.inr true)
      rwa [expandBobMat_inr_inr, commute_toCLM_iff] at h
    · have h := hc (.inr none) (.inr true)
      rwa [expandBobMat_inr_inr, commute_toCLM_iff] at h
  obtain ⟨X₀, hX₀, rfl⟩ := exists_eq_toCLM_liftLeft hs hreg
  refine ⟨of fun a a' => ⟨X₀ a a', mem_centralizer_of_forall_commute ?_ (hX₀ a a')⟩, rfl⟩
  rintro _ ⟨p, rfl⟩
  exact ⟨p, (S.F_pos p.1 p.2).isSelfAdjoint.star_eq.symm⟩

/-- The first player's representation of the extension, into the first player's algebra of the
strategy. (The representation is first read on the strategy's space, where the algebra lives, so
that the restriction of its codomain is between subalgebras of one type.) -/
noncomputable def expandAliceHom :
    Matrix α α S.aliceAlg →⋆ₐ[ℂ] (S.expandStrategy e he).aliceAlg :=
  StarAlgHom.codRestrict (S.expandAliceRep : Matrix α α S.aliceAlg →⋆ₐ[ℂ]
      ((S.expandStrategy e he).H →L[ℂ] (S.expandStrategy e he).H))
    (S.expandStrategy e he).aliceAlg (S.expandAliceRep_mem e he)

theorem expandAliceHom_bijective : Function.Bijective (S.expandAliceHom e he) := by
  have := (nonempty_of_norm_evec_eq_one he).2
  refine ⟨fun X X' h => ?_, fun T => ?_⟩
  · exact Matrix.map_injective Subtype.val_injective
      (toCLM_liftLeft_injective (congrArg Subtype.val h))
  · obtain ⟨X, hX⟩ := S.exists_expandAliceRep_eq e he T.2
    exact ⟨X, Subtype.ext hX⟩

/-- **The first player's algebra of the strategy is the matrix algebra `M_α(𝒜)`** over the first
player's algebra `𝒜` of `S`, by the representation of the extension. -/
noncomputable def expandAliceEquiv :
    Matrix α α S.aliceAlg ≃⋆ₐ[ℂ] (S.expandStrategy e he).aliceAlg :=
  StarAlgEquiv.ofBijective (S.expandAliceHom e he) (S.expandAliceHom_bijective e he)

theorem coe_expandAliceEquiv (X : Matrix α α S.aliceAlg) :
    (S.expandAliceEquiv e he X : (S.expandStrategy e he).H →L[ℂ] (S.expandStrategy e he).H) =
      S.expandAliceRep X :=
  rfl

/-- The second player's operators of the extension are in the second player's algebra of the
strategy: they commute with its first player's algebra, which is the first player's algebra of
the extension. -/
theorem expandBobRep_mem (Y : Matrix β β S.bobAlg) :
    S.expandBobRep Y ∈ (S.expandStrategy e he).bobAlg := by
  show S.expandBobRep Y ∈ (S.expandStrategyAux e he).bobAlg
  refine mem_centralizer_of_forall_commute (fun g hg => star_mem hg) fun g hg => ?_
  obtain ⟨X, rfl⟩ := S.exists_expandAliceRep_eq e he hg
  exact (commute_toCLM_liftLeft_liftRight (X.map S.aliceAlg.subtype) (Y.map S.bobAlg.subtype)
    fun a a' b b' => S.commute_of_mem (X a a').2 (Y b b').2).symm

/-- **The second player's algebra of the strategy is the second player's algebra of the
extension**: every operator commuting with the first player's algebra of the strategy is `1_α ⊗ Y`
for a matrix `Y` over the commutant of `S.aliceAlg`, which is `S.bobAlg`. -/
theorem exists_expandBobRep_eq {T : Ampl (α × β) S.H →L[ℂ] Ampl (α × β) S.H}
    (hT : T ∈ (S.expandStrategy e he).bobAlg) : ∃ Y, S.expandBobRep Y = T := by
  change T ∈ (S.expandStrategyAux e he).bobAlg at hT
  have := (nonempty_of_norm_evec_eq_one he).1
  have hc : ∀ X : Matrix α α S.aliceAlg, Commute T (S.expandAliceRep X) := fun X =>
    ((StarSubalgebra.mem_centralizer_iff ℂ).1 hT _ (S.expandAliceRep_mem e he X)).1.symm
  have hs : ∀ f ∈ (S.aliceAlg : Set (S.H →L[ℂ] S.H)),
      Commute T (toCLM (diagonal fun _ : α × β => f)) := by
    intro f hf
    have h := hc (diagonal fun _ => ⟨f, hf⟩)
    rwa [expandAliceRep_apply, diagonal_map (map_zero _), liftLeft_diagonal_const] at h
  have hreg : ∀ a a', Commute T (toCLM (liftLeft (β := β) (single a a' (1 : S.H →L[ℂ] S.H)))) := by
    intro a a'
    have h := hc (single a a' 1)
    rwa [expandAliceRep_apply, map_single, map_one] at h
  obtain ⟨Y₀, hY₀, rfl⟩ := exists_eq_toCLM_liftRight hs hreg
  exact ⟨of fun b b' => ⟨Y₀ b b', mem_centralizer_of_forall_commute
    (fun f hf => star_mem hf) (hY₀ b b')⟩, rfl⟩

/-- The second player's representation of the extension, into the second player's algebra of the
strategy. -/
noncomputable def expandBobHom :
    Matrix β β S.bobAlg →⋆ₐ[ℂ] (S.expandStrategy e he).bobAlg :=
  StarAlgHom.codRestrict (S.expandBobRep : Matrix β β S.bobAlg →⋆ₐ[ℂ]
      ((S.expandStrategy e he).H →L[ℂ] (S.expandStrategy e he).H))
    (S.expandStrategy e he).bobAlg (S.expandBobRep_mem e he)

theorem expandBobHom_bijective : Function.Bijective (S.expandBobHom e he) := by
  have := (nonempty_of_norm_evec_eq_one he).1
  refine ⟨fun Y Y' h => ?_, fun T => ?_⟩
  · exact Matrix.map_injective Subtype.val_injective
      (toCLM_liftRight_injective (congrArg Subtype.val h))
  · obtain ⟨Y, hY⟩ := S.exists_expandBobRep_eq e he T.2
    exact ⟨Y, Subtype.ext hY⟩

/-- **The second player's algebra of the strategy is the matrix algebra `M_β(ℬ)`** over the second
player's algebra `ℬ` of `S`, by the representation of the extension. -/
noncomputable def expandBobEquiv :
    Matrix β β S.bobAlg ≃⋆ₐ[ℂ] (S.expandStrategy e he).bobAlg :=
  StarAlgEquiv.ofBijective (S.expandBobHom e he) (S.expandBobHom_bijective e he)

theorem coe_expandBobEquiv (Y : Matrix β β S.bobAlg) :
    (S.expandBobEquiv e he Y : (S.expandStrategy e he).H →L[ℂ] (S.expandStrategy e he).H) =
      S.expandBobRep Y :=
  rfl

/-- **The first player's algebra of the strategy**, as a set: the operators `X ⊗ 1_β` for the
matrices `X` over `S.aliceAlg`. -/
theorem mem_expandStrategy_aliceAlg_iff {T : Ampl (α × β) S.H →L[ℂ] Ampl (α × β) S.H} :
    T ∈ (S.expandStrategy e he).aliceAlg ↔ ∃ X, S.expandAliceRep X = T :=
  ⟨S.exists_expandAliceRep_eq e he, fun ⟨X, hX⟩ => hX ▸ S.expandAliceRep_mem e he X⟩

/-- **The second player's algebra of the strategy**, as a set: the operators `1_α ⊗ Y` for the
matrices `Y` over `S.bobAlg`. -/
theorem mem_expandStrategy_bobAlg_iff {T : Ampl (α × β) S.H →L[ℂ] Ampl (α × β) S.H} :
    T ∈ (S.expandStrategy e he).bobAlg ↔ ∃ Y, S.expandBobRep Y = T :=
  ⟨S.exists_expandBobRep_eq e he, fun ⟨Y, hY⟩ => hY ▸ S.expandBobRep_mem e he Y⟩

/-! ## The extension of a commuting-operator model is a commuting-operator model -/

/-- **The ancilla extension of a commuting-operator model is the model of a commuting-operator
strategy**, `S.toModel.expand e ≅ (S.expandStrategy e he).toModel`: the identity of the space
`H ⊗ ℂ^{α × β}`, which carries the state to itself, with the equivalences `expandAliceEquiv` and
`expandBobEquiv` of the players' algebras. -/
noncomputable def expandIso :
    BipartiteModel.Iso (S.toModel.expand e) (S.expandStrategy e he).toModel where
  W := LinearIsometryEquiv.refl ℂ (Ampl (α × β) S.H)
  ΦA := S.expandAliceEquiv e he
  ΦB := S.expandBobEquiv e he
  intertwineA _ _ := rfl
  intertwineB _ _ := rfl
  W_ψ := rfl

@[simp]
theorem expandIso_W (v : (S.toModel.expand e).H) : (S.expandIso e he).W v = v :=
  rfl

@[simp]
theorem expandIso_ΦA (X : Matrix α α S.aliceAlg) :
    ((S.expandIso e he).ΦA X : (S.expandStrategy e he).H →L[ℂ] (S.expandStrategy e he).H) =
      S.expandAliceRep X :=
  rfl

@[simp]
theorem expandIso_ΦB (Y : Matrix β β S.bobAlg) :
    ((S.expandIso e he).ΦB Y : (S.expandStrategy e he).H →L[ℂ] (S.expandStrategy e he).H) =
      S.expandBobRep Y :=
  rfl

end CommutingOperatorStrategy

end MIPRE

end
