/-
Copyright (c) 2026 Thomas Vidick. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Vidick
-/
module
public import Mathlib.Algebra.Star.Subalgebra
public import MIPRE.Foundations.CommutingOperator
public import MIPRE.Foundations.OpBound
public import MIPRE.Tactics

@[expose] public section

/-!
# The bipartite model: a state and two commuting representations

The stage analyses of compression are bipartite and vector-state: a unit vector, the first
player's operators and the second player's, the two families commuting, and never a trace
(`reports/co-generalization-audit.md`). Their common generalization, the model of Phase 1 of
`planning/mipco-track.md`, is a **bipartite model** (`BipartiteModel`): a complex Hilbert
space `H` with a state `ψ`, and two `⋆`-algebras `𝒜` (the first player's) and `ℬ` (the
second player's), represented on `H` by `⋆`-homomorphisms `πA` and `πB` whose images commute.
That `ψ` is a unit vector is a hypothesis of the results that need it, as in the matrix
calculus, so that every matrix quantity is the model's quantity in the tensor-product model
with no side condition.

The players' operators are elements of `𝒜` and of `ℬ` rather than of `H →L[ℂ] H`. So a
product, a sum or an adjoint of one player's operators is again one of that player's, and it
commutes with the other player's for free: this is what the matrix analyses get from writing
the two players' operators on the two factors of a tensor product, and what lets them be read
in this model unchanged. There are two instances.

* **The tensor-product model** `BipartiteModel.tensor ψ`: `𝒜 = M_{dA}(ℂ)`, `ℬ = M_{dB}(ℂ)`,
  `H = ℂ^{dA × dB}`, `πA X = X ⊗ 1` and `πB Y = 1 ⊗ Y`, the embeddings `aOp` and `bOp` of
  `MIPRE/Foundations/OpBound.lean` read as operators. The matrix calculus is the state calculus
  of `MIPRE/Foundations/OpCalculus.lean` in this model (`snorm_tensor`, `qform_tensor`).
* **The commuting-operator model** `CommutingOperatorStrategy.toModel S`: the strategy's space
  and state, with `𝒜` and `ℬ` the `⋆`-subalgebras generated by the two players' operators,
  which commute because their generators do (`CommutingOperatorStrategy.commute_of_mem`). The
  players' operators are elements of these algebras (`E_mem_aliceAlg`, `F_mem_bobAlg`), and by
  `thm:co-value-projective` a strategy may be taken projective.
-/

namespace MIPRE

open scoped InnerProductSpace

universe u v w

/-- **A bipartite model**: a complex Hilbert space with a state, and two `⋆`-algebras, the
first player's and the second player's, represented on it by commuting `⋆`-homomorphisms. -/
structure BipartiteModel (𝒜 : Type v) (ℬ : Type w) [Ring 𝒜] [StarRing 𝒜] [Algebra ℂ 𝒜]
    [Ring ℬ] [StarRing ℬ] [Algebra ℂ ℬ] where
  /-- The Hilbert space. -/
  H : Type u
  [normedAddCommGroup : NormedAddCommGroup H]
  [innerProductSpace : InnerProductSpace ℂ H]
  [completeSpace : CompleteSpace H]
  /-- The state. -/
  ψ : H
  /-- The first player's algebra, represented on `H`. -/
  πA : 𝒜 →⋆ₐ[ℂ] (H →L[ℂ] H)
  /-- The second player's algebra, represented on `H`. -/
  πB : ℬ →⋆ₐ[ℂ] (H →L[ℂ] H)
  /-- The two representations commute. -/
  commute : ∀ a b, Commute (πA a) (πB b)

attribute [instance] BipartiteModel.normedAddCommGroup BipartiteModel.innerProductSpace
  BipartiteModel.completeSpace

namespace BipartiteModel

variable {𝒜 : Type v} {ℬ : Type w} [Ring 𝒜] [StarRing 𝒜] [Algebra ℂ 𝒜] [Ring ℬ] [StarRing ℬ]
  [Algebra ℂ ℬ]

/-- The model with the two players exchanged. -/
def swap (M : BipartiteModel.{u} 𝒜 ℬ) : BipartiteModel.{u} ℬ 𝒜 where
  H := M.H
  ψ := M.ψ
  πA := M.πB
  πB := M.πA
  commute b a := (M.commute a b).symm

@[simp]
theorem swap_πA (M : BipartiteModel.{u} 𝒜 ℬ) : M.swap.πA = M.πB := rfl

@[simp]
theorem swap_πB (M : BipartiteModel.{u} 𝒜 ℬ) : M.swap.πB = M.πA := rfl

@[simp]
theorem swap_swap (M : BipartiteModel.{u} 𝒜 ℬ) : M.swap.swap = M := rfl

/-- A self-adjoint idempotent of the first player's algebra acts as an orthogonal projection,
which is bounded by one. -/
theorem bnd_πA_of_isStarProjection (M : BipartiteModel.{u} 𝒜 ℬ) {p : 𝒜}
    (hp : IsStarProjection p) : Op.Bnd (M.πA p) 1 :=
  Op.bnd_one_of_isStarProjection (hp.map M.πA)

/-- A self-adjoint idempotent of the second player's algebra acts as an orthogonal projection,
which is bounded by one. -/
theorem bnd_πB_of_isStarProjection (M : BipartiteModel.{u} 𝒜 ℬ) {q : ℬ}
    (hq : IsStarProjection q) : Op.Bnd (M.πB q) 1 :=
  Op.bnd_one_of_isStarProjection (hq.map M.πB)

/-! ## The tensor-product model -/

section Tensor

variable {dA dB : Type} [Fintype dA] [DecidableEq dA] [Fintype dB] [DecidableEq dB]

/-- `X ↦ X ⊗ 1`, the first factor's matrices acting on the product, as a `⋆`-algebra
homomorphism. -/
noncomputable def aOpStarAlgHom : Matrix dA dA ℂ →⋆ₐ[ℂ] Matrix (dA × dB) (dA × dB) ℂ where
  toFun := aOp
  map_one' := aOp_one
  map_mul' := aOp_mul
  map_zero' := Matrix.zero_kronecker _
  map_add' := aOp_add
  commutes' c := by
    rw [Algebra.algebraMap_eq_smul_one, aOp_smul, aOp_one, ← Algebra.algebraMap_eq_smul_one]
  map_star' X := by
    rw [Matrix.star_eq_conjTranspose, Matrix.star_eq_conjTranspose, aOp_conjTranspose]

/-- `Y ↦ 1 ⊗ Y`, the second factor's matrices acting on the product, as a `⋆`-algebra
homomorphism. -/
noncomputable def bOpStarAlgHom : Matrix dB dB ℂ →⋆ₐ[ℂ] Matrix (dA × dB) (dA × dB) ℂ where
  toFun := bOp
  map_one' := bOp_one
  map_mul' := bOp_mul
  map_zero' := Matrix.kronecker_zero _
  map_add' := bOp_add
  commutes' c := by
    rw [Algebra.algebraMap_eq_smul_one, bOp_smul, bOp_one, ← Algebra.algebraMap_eq_smul_one]
  map_star' Y := by
    rw [Matrix.star_eq_conjTranspose, Matrix.star_eq_conjTranspose, bOp_conjTranspose]

@[simp]
theorem aOpStarAlgHom_apply (X : Matrix dA dA ℂ) :
    (aOpStarAlgHom (dB := dB)) X = aOp X := rfl

@[simp]
theorem bOpStarAlgHom_apply (Y : Matrix dB dB ℂ) :
    (bOpStarAlgHom (dA := dA)) Y = bOp Y := rfl

/-- **The tensor-product model** of a vector `ψ` on `ℂ^{dA × dB}`: the first player's
matrices act as `X ⊗ 1`, the second player's as `1 ⊗ Y`. -/
noncomputable def tensor (ψ : dA × dB → ℂ) :
    BipartiteModel.{0} (Matrix dA dA ℂ) (Matrix dB dB ℂ) where
  H := EuclideanSpace ℂ (dA × dB)
  ψ := evec ψ
  πA := (Matrix.toEuclideanCLM (n := dA × dB) (𝕜 := ℂ)).toStarAlgHom.comp aOpStarAlgHom
  πB := (Matrix.toEuclideanCLM (n := dA × dB) (𝕜 := ℂ)).toStarAlgHom.comp bOpStarAlgHom
  commute X Y := by
    show Matrix.toEuclideanCLM (n := dA × dB) (𝕜 := ℂ) (aOp X) *
        Matrix.toEuclideanCLM (n := dA × dB) (𝕜 := ℂ) (bOp Y) =
      Matrix.toEuclideanCLM (n := dA × dB) (𝕜 := ℂ) (bOp Y) *
        Matrix.toEuclideanCLM (n := dA × dB) (𝕜 := ℂ) (aOp X)
    rw [← map_mul, ← map_mul, aOp_mul_bOp]

variable (ψ : dA × dB → ℂ)

theorem tensor_ψ : (tensor ψ).ψ = evec ψ := rfl

@[simp]
theorem tensor_πA (X : Matrix dA dA ℂ) :
    (tensor ψ).πA X = Matrix.toEuclideanCLM (n := dA × dB) (𝕜 := ℂ) (aOp X) := rfl

@[simp]
theorem tensor_πB (Y : Matrix dB dB ℂ) :
    (tensor ψ).πB Y = Matrix.toEuclideanCLM (n := dA × dB) (𝕜 := ℂ) (bOp Y) := rfl

/-- **The matrix state norm is the state norm of the tensor-product model.** -/
theorem snorm_tensor (T : Matrix (dA × dB) (dA × dB) ℂ) :
    Op.snorm (tensor ψ).ψ (Matrix.toEuclideanCLM (n := dA × dB) (𝕜 := ℂ) T) = snorm ψ T :=
  rfl

/-- **The matrix quadratic form is the quadratic form of the tensor-product model.** -/
theorem qform_tensor (T : Matrix (dA × dB) (dA × dB) ℂ) :
    Op.qform (tensor ψ).ψ (Matrix.toEuclideanCLM (n := dA × dB) (𝕜 := ℂ) T) = qform ψ T :=
  (qform_eq_op ψ T).symm

end Tensor

end BipartiteModel

/-! ## The commuting-operator model -/

namespace CommutingOperatorStrategy

variable {X Y A B : Type*} [Fintype X] [Fintype Y] [Fintype A] [Fintype B]

/-- The first player's algebra: the `⋆`-subalgebra generated by the first player's
operators. -/
noncomputable def aliceAlg (S : CommutingOperatorStrategy X Y A B) :
    StarSubalgebra ℂ (S.H →L[ℂ] S.H) :=
  StarAlgebra.adjoin ℂ (Set.range fun p : X × A => S.E p.1 p.2)

/-- The second player's algebra: the `⋆`-subalgebra generated by the second player's
operators. -/
noncomputable def bobAlg (S : CommutingOperatorStrategy X Y A B) :
    StarSubalgebra ℂ (S.H →L[ℂ] S.H) :=
  StarAlgebra.adjoin ℂ (Set.range fun p : Y × B => S.F p.1 p.2)

theorem E_mem_aliceAlg (S : CommutingOperatorStrategy X Y A B) (x : X) (a : A) :
    S.E x a ∈ S.aliceAlg :=
  StarAlgebra.subset_adjoin ℂ _ ⟨(x, a), rfl⟩

theorem F_mem_bobAlg (S : CommutingOperatorStrategy X Y A B) (y : Y) (b : B) :
    S.F y b ∈ S.bobAlg :=
  StarAlgebra.subset_adjoin ℂ _ ⟨(y, b), rfl⟩

/-- The second player's algebra commutes with the first player's operators. -/
theorem bobAlg_le_centralizer (S : CommutingOperatorStrategy X Y A B) :
    S.bobAlg ≤ StarSubalgebra.centralizer ℂ (Set.range fun p : X × A => S.E p.1 p.2) := by
  refine StarAlgebra.adjoin_le ?_
  rintro _ ⟨⟨y, b⟩, rfl⟩
  rw [SetLike.mem_coe, StarSubalgebra.mem_centralizer_iff]
  rintro _ ⟨⟨x, a⟩, rfl⟩
  rw [(S.E_pos x a).isSelfAdjoint.star_eq]
  exact ⟨(S.commutes x y a b).eq, (S.commutes x y a b).eq⟩

/-- **The two players' algebras commute**, because their generators do. -/
theorem commute_of_mem (S : CommutingOperatorStrategy X Y A B) {a b : S.H →L[ℂ] S.H}
    (ha : a ∈ S.aliceAlg) (hb : b ∈ S.bobAlg) : Commute a b := by
  have hA : S.aliceAlg ≤ StarSubalgebra.centralizer ℂ (S.bobAlg : Set (S.H →L[ℂ] S.H)) := by
    refine StarAlgebra.adjoin_le ?_
    rintro _ ⟨⟨x, a⟩, rfl⟩
    rw [SetLike.mem_coe, StarSubalgebra.mem_centralizer_iff]
    intro g hg
    have h1 := (StarSubalgebra.mem_centralizer_iff ℂ).1 (S.bobAlg_le_centralizer hg)
    have h2 := (StarSubalgebra.mem_centralizer_iff ℂ).1
      (S.bobAlg_le_centralizer (star_mem hg))
    exact ⟨(h1 _ ⟨(x, a), rfl⟩).1.symm, (h2 _ ⟨(x, a), rfl⟩).1.symm⟩
  exact (((StarSubalgebra.mem_centralizer_iff ℂ).1 (hA ha)) b hb).1.symm

/-- **The commuting-operator model of a strategy**: its space and state, with the
`⋆`-subalgebras generated by the two players' operators. -/
noncomputable def toModel (S : CommutingOperatorStrategy X Y A B) :
    BipartiteModel.{0} S.aliceAlg S.bobAlg where
  H := S.H
  ψ := S.ψ
  πA := S.aliceAlg.subtype
  πB := S.bobAlg.subtype
  commute a b := S.commute_of_mem a.2 b.2

theorem toModel_ψ_norm (S : CommutingOperatorStrategy X Y A B) : ‖S.toModel.ψ‖ = 1 :=
  S.ψ_norm

@[simp]
theorem toModel_πA (S : CommutingOperatorStrategy X Y A B) (a : S.aliceAlg) :
    S.toModel.πA a = (a : S.H →L[ℂ] S.H) := rfl

@[simp]
theorem toModel_πB (S : CommutingOperatorStrategy X Y A B) (b : S.bobAlg) :
    S.toModel.πB b = (b : S.H →L[ℂ] S.H) := rfl

/-- **The correlation of a strategy is the quadratic form of its model** at the product of the
two players' operators. -/
theorem correlation_eq_qform (S : CommutingOperatorStrategy X Y A B) (x : X) (y : Y) (a : A)
    (b : B) :
    S.correlation x y a b = Op.qform S.toModel.ψ
      (S.toModel.πA ⟨S.E x a, S.E_mem_aliceAlg x a⟩ *
        S.toModel.πB ⟨S.F y b, S.F_mem_bobAlg y b⟩) :=
  rfl

end CommutingOperatorStrategy

end MIPRE

end
