/-
Copyright (c) 2026 Thomas Vidick. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Vidick
-/
import Mathlib.Analysis.InnerProductSpace.Positive
import MIPRE.Foundations.Games

/-!
# Bipartite commuting-operator strategies and the commuting-operator value

A commuting-operator strategy for a (not necessarily synchronous) game
(blueprint `def:co-strategy-bipartite`): a complex Hilbert space `H`, a unit vector `ψ`,
and POVM families `E x` (first player) and `F y` (second player) of positive operators
summing to one, with every `E x a` commuting with every `F y b`. Its value in a game and
the commuting-operator value `valco(G)` of the game (blueprint `def:co-value-bipartite`)
are the usual ones.

This is the two-prover picture of the commuting-operator model. The synchronous,
tracial commuting strategies of `MIPRE.Foundations.Games` (`CommutingStrategy`,
`commValue`) are the picture used by the compression pipeline; the two agree, for
synchronous games whose questions carry proportional weight on the diagonal, only up to the
rounding of almost-synchronous correlations (blueprint `thm:almost-sync`), which is why both
are defined. Without that weight they can differ by a constant (blueprint
`rem:almost-sync-hypothesis`). The definitions mirror
those of the vendored development `MIPRE/Background/Repetition/CommutingRepetition/`
field by field, so that its theorems transfer by a field-by-field identification.

The Hilbert space lives in universe `0`; by restriction to the separable subspace
cyclically generated by `ψ` under the finitely many effects this loses no generality.
-/

namespace MIPRE

open scoped BigOperators InnerProductSpace

/-- A commuting-operator strategy over question alphabets `X`, `Y` and answer alphabets
`A`, `B` (blueprint `def:co-strategy-bipartite`). -/
structure CommutingOperatorStrategy (X Y A B : Type*)
    [Fintype X] [Fintype Y] [Fintype A] [Fintype B] where
  /-- The Hilbert space. -/
  H : Type
  [normedAddCommGroup : NormedAddCommGroup H]
  [innerProductSpace : InnerProductSpace ℂ H]
  [completeSpace : CompleteSpace H]
  /-- The shared state. -/
  ψ : H
  /-- The shared state is a unit vector. -/
  ψ_norm : ‖ψ‖ = 1
  /-- The first player's measurement operators. -/
  E : X → A → H →L[ℂ] H
  /-- The second player's measurement operators. -/
  F : Y → B → H →L[ℂ] H
  /-- The first player's operators are positive. -/
  E_pos : ∀ x a, (E x a).IsPositive
  /-- The second player's operators are positive. -/
  F_pos : ∀ y b, (F y b).IsPositive
  /-- The first player's operators form a POVM for each question. -/
  E_sum : ∀ x, ∑ a, E x a = 1
  /-- The second player's operators form a POVM for each question. -/
  F_sum : ∀ y, ∑ b, F y b = 1
  /-- The two players' operators commute. -/
  commutes : ∀ x y a b, Commute (E x a) (F y b)

attribute [instance] CommutingOperatorStrategy.normedAddCommGroup
  CommutingOperatorStrategy.innerProductSpace CommutingOperatorStrategy.completeSpace

variable {X Y A B : Type*} [Fintype X] [Fintype Y] [Fintype A] [Fintype B]

namespace CommutingOperatorStrategy

/-- The probability that the players answer `(a, b)` to the questions `(x, y)`:
`⟨ψ| E^x_a F^y_b |ψ⟩`, a real number since the commuting product of two positive
operators is self-adjoint; we take the real part so that the definition carries no proof
obligations. -/
noncomputable def correlation (S : CommutingOperatorStrategy X Y A B)
    (x : X) (y : Y) (a : A) (b : B) : ℝ :=
  (⟪S.ψ, S.E x a (S.F y b S.ψ)⟫_ℂ).re

/-- The value of a commuting-operator strategy in the game `G`. -/
noncomputable def value (G : Game X Y A B) (S : CommutingOperatorStrategy X Y A B) : ℝ :=
  ∑ x, ∑ y, ∑ a, ∑ b,
    G.μ x y * (if G.D x y a b then 1 else 0) * S.correlation x y a b

end CommutingOperatorStrategy

/-- The commuting-operator value `valco(G)` of a game (blueprint
`def:co-value-bipartite`): the supremum of strategy values over all commuting-operator
strategies. -/
noncomputable def commutingOperatorValue (G : Game X Y A B) : ℝ :=
  ⨆ S : CommutingOperatorStrategy X Y A B, S.value G

end MIPRE
