/-
Copyright (c) 2026 Thomas Vidick. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Vidick
-/
import Mathlib.Analysis.CStarAlgebra.Classes
import Mathlib.Analysis.Matrix.Order
import Mathlib.Data.ENat.Lattice
import Mathlib.LinearAlgebra.Matrix.Kronecker

/-!
# Games, strategies, and values

This file contains the definitions of blueprint Section 2.1 ("Games, strategies, and
values") of the MIP* = RE formalization project: two-player one-round nonlocal games, the
three classes of strategies (tensor-product, synchronous, and commuting), the associated
values, and the entanglement requirement.

The matrix-based definitions (`POVM`, `SynchronousGame`, `SyncStrategy` and the
synchronous value) agree with those of `MIPRE.HaltingGameValue`, which is kept
self-contained; that file is the source for the copied code.

## Main definitions

- `MIPRE.Game`: two-player one-round games (blueprint `def:game`).
- `MIPRE.SynchronousGame`: synchronous games, with the interpretation
  `MIPRE.SynchronousGame.toGame` (blueprint `def:sync-game`).
- `MIPRE.POVM`: positive operator-valued measures, following the QuantumLib
  (Lean-QuantumInfo) definition.
- `MIPRE.TensorProductStrategy`: finite-dimensional tensor-product strategies
  (blueprint `def:tensor-strategy`).
- `MIPRE.quantumValue`: the quantum value `val*` of a game (blueprint `def:q-value`).
- `MIPRE.SyncStrategy`: synchronous strategies (blueprint `def:sync-strategy`).
- `MIPRE.SyncStrategy.IsPCC`: PCC (projective, consistent, and commuting) strategies
  (blueprint `def:pcc`).
- `MIPRE.syncValue`: the synchronous value of a synchronous game (blueprint
  `def:sync-value`).
- `MIPRE.CommutingStrategy`: commuting strategies, given by a unital C*-algebra with a
  tracial state (blueprint `def:commuting-strategy`).
- `MIPRE.commValue`: the commuting value of a synchronous game (blueprint
  `def:commuting-value`).
- `MIPRE.entRequirement`: the entanglement requirement `Ent(G, ν)` (blueprint `def:ent`).

## Main statements

- `MIPRE.syncValue_le_quantumValue`: the synchronous value lower-bounds the quantum value
  (blueprint `lem:sync-le-valstar`).
- `MIPRE.syncValue_le_commValue`: the synchronous value lower-bounds the commuting value
  (blueprint `lem:sync-le-valco`).

## Implementation notes

- Question distributions are bare real-valued functions with nonnegativity and
  normalization fields, rather than `PMF` (which is `ℝ≥0∞`-valued and would force
  coercions in the value definitions).
- Outcome probabilities are nonnegative reals, but proving so requires positivity
  arguments; as in `MIPRE.HaltingGameValue`, each value takes the real part `.re` of the
  relevant complex quantity so that the definitions carry no proof obligations.
- The algebra of a `CommutingStrategy` lives in universe `0`. This loses no generality:
  for a finite game, the GNS representation of the (separable) C*-subalgebra generated by
  the finitely many measurement operators realizes the same correlation, and it lives in
  universe `0`.
- `POVM` matches the QuantumLib (Lean-QuantumInfo) definition
  (`QuantumInfo.Finite.POVM`), with `selfAdjoint (Matrix d d ℂ)` spelled out for its
  definitionally equal `HermitianMat d ℂ`, so that the strategy layer can be upstreamed.

## References

- Ji, Natarajan, Vidick, Wright, Yuen, *MIP\* = RE*, arXiv:2001.04383.
-/

namespace MIPRE

/- The partial order on `ℂ` (for positivity of tracial states) and the Loewner order on
matrices (`0 ≤ A ↔ A.PosSemidef`, for POVM elements) are scoped. -/
open ComplexOrder Kronecker Matrix
open scoped MatrixOrder

/-! ## Games -/

/-- A two-player one-round game (blueprint `def:game`): finite question alphabets `X`,
`Y`, finite answer alphabets `A`, `B`, a probability distribution `μ` on `X × Y`, and a
decision predicate `D` (`true` = accept). -/
structure Game (X Y A B : Type*) [Fintype X] [Fintype Y] [Fintype A] [Fintype B] where
  /-- The probability that the players are asked the question pair `(x, y)`. -/
  μ : X → Y → ℝ
  /-- Question probabilities are nonnegative. -/
  μ_nonneg : ∀ x y, 0 ≤ μ x y
  /-- Question probabilities sum to one. -/
  μ_sum_one : ∑ x, ∑ y, μ x y = 1
  /-- The decision predicate: `D x y a b = true` means the answers `(a, b)` to the
  questions `(x, y)` are accepted. -/
  D : X → Y → A → B → Bool

/-- A synchronous game (blueprint `def:sync-game`): both players receive questions from
the same alphabet and answer from the same alphabet; on equal questions, unequal answers
always lose. -/
structure SynchronousGame (X A : Type*) [Fintype X] [Fintype A] [DecidableEq A] where
  /-- The probability that the players are asked the question pair `(x, y)`. -/
  μ : X → X → ℝ
  /-- Question probabilities are nonnegative. -/
  μ_nonneg : ∀ x y, 0 ≤ μ x y
  /-- Question probabilities sum to one. -/
  μ_sum_one : ∑ x, ∑ y, μ x y = 1
  /-- The decision predicate: `D x y a b = true` means the answers `(a, b)` to the
  questions `(x, y)` are accepted. -/
  D : X → X → A → A → Bool
  /-- Unequal answers to equal questions are rejected. -/
  synchronous : ∀ x a b, a ≠ b → D x x a b = false

variable {X Y A B : Type*} [Fintype X] [Fintype Y] [Fintype A] [Fintype B]

/-- A synchronous game is in particular a game, with `Y = X` and `B = A`. -/
def SynchronousGame.toGame [DecidableEq A] (G : SynchronousGame X A) : Game X X A A where
  μ := G.μ
  μ_nonneg := G.μ_nonneg
  μ_sum_one := G.μ_sum_one
  D := G.D

/-! ## POVMs -/

/-- A POVM is a (finite) collection of PSD matrices on the same Hilbert space that sum
to the identity. Here `X` indexes the matrices, and `d` is the space dimension.

This is the QuantumLib (Lean-QuantumInfo) definition of `POVM`, with
`selfAdjoint (Matrix d d ℂ)` spelled out for its definitionally equal
`HermitianMat d ℂ`; `0 ≤ mats x` is the Loewner order, i.e. positive
semidefiniteness. -/
structure POVM (X : Type*) (d : Type*) [Fintype X] [Fintype d] [DecidableEq d] where
  /-- The measurement operators, one for each outcome. -/
  mats : X → selfAdjoint (Matrix d d ℂ)
  /-- Each measurement operator is positive semidefinite. -/
  nonneg : ∀ x, 0 ≤ mats x
  /-- The measurement operators sum to the identity. -/
  normalized : ∑ x, mats x = 1

/-! ## Tensor-product strategies and the quantum value -/

/-- A tensor-product strategy for a game `G` (blueprint `def:tensor-strategy`):
finite-dimensional Hilbert spaces `ℂ^dA` and `ℂ^dB`, a unit vector `ψ` in their tensor
product — realized as `Fin dA × Fin dB → ℂ` — and POVMs `{A^x_a}` on `ℂ^dA` and
`{B^y_b}` on `ℂ^dB`. Outcome probabilities are computed using the Born rule (see
`TensorProductStrategy.value`). -/
structure TensorProductStrategy (G : Game X Y A B) where
  /-- The dimension of the first player's Hilbert space. -/
  dA : ℕ
  /-- The dimension of the second player's Hilbert space. -/
  dB : ℕ
  /-- The shared state, a vector in the tensor product `ℂ^dA ⊗ ℂ^dB = ℂ^(dA × dB)`. -/
  ψ : Fin dA × Fin dB → ℂ
  /-- The shared state is a unit vector. (In particular `dA` and `dB` are positive,
  since a zero-dimensional space contains no unit vector.) -/
  ψ_unit : star ψ ⬝ᵥ ψ = 1
  /-- The first player's POVMs, one for each question `x`. -/
  povmA : X → POVM A (Fin dA)
  /-- The second player's POVMs, one for each question `y`. -/
  povmB : Y → POVM B (Fin dB)

/-- The value of a tensor-product strategy in `G` (blueprint `def:q-value`): the players
answer questions `(x, y)` with `(a, b)` with the Born-rule probability
`⟨ψ| A^x_a ⊗ B^y_b |ψ⟩`, the tensor product being realized by the Kronecker product.
The probability is a nonnegative real; we take the real part so that the definition
typechecks with no proof obligations. -/
noncomputable def TensorProductStrategy.value {G : Game X Y A B}
    (S : TensorProductStrategy G) : ℝ :=
  ∑ x, ∑ y, ∑ a, ∑ b,
    G.μ x y * (if G.D x y a b then 1 else 0) *
      (star S.ψ ⬝ᵥ ((((S.povmA x).mats a).val ⊗ₖ ((S.povmB y).mats b).val) *ᵥ S.ψ)).re

/-- The quantum value `val*(G)` of a game (blueprint `def:q-value`): the supremum of
strategy values over all tensor-product strategies. -/
noncomputable def quantumValue (G : Game X Y A B) : ℝ :=
  ⨆ S : TensorProductStrategy G, S.value

/-! ## Synchronous strategies and the synchronous value -/

variable [DecidableEq A]

/-- A synchronous strategy for a synchronous game (blueprint `def:sync-strategy`): a
finite-dimensional strategy with a single question-indexed projective measurement family.
The operators act on `ℂ^d` (`d > 0`); each measurement operator is idempotent, hence
(being positive semidefinite) an orthogonal projection. Measurements for different
questions need not commute. There is no state vector: outcome probabilities are computed
with the dimension-normalized trace `τ(M) = Tr(M)/d` (see `SyncStrategy.value`). -/
structure SyncStrategy (G : SynchronousGame X A) where
  /-- The dimension of the Hilbert space. -/
  d : ℕ
  /-- The dimension is positive. -/
  d_pos : 0 < d
  /-- The measurements, one POVM for each question. -/
  povm : X → POVM A (Fin d)
  /-- Each measurement operator is idempotent, so the POVMs are projective (PVMs). -/
  projective : ∀ x a,
    ((povm x).mats a).val * ((povm x).mats a).val = ((povm x).mats a).val

/-- A synchronous strategy is *PCC* (*projective, consistent, and commuting*, following
JNVWY Section 5.2; blueprint `def:pcc`) if the measurement operators associated with any
pair of questions asked with positive probability commute. Projectivity is part of
`SyncStrategy`, and consistency is automatic for synchronous strategies, so only the
commutation condition remains. -/
def SyncStrategy.IsPCC {G : SynchronousGame X A} (S : SyncStrategy G) : Prop :=
  ∀ x y, 0 < G.μ x y → ∀ a b,
    ((S.povm x).mats a).val * ((S.povm y).mats b).val =
      ((S.povm y).mats b).val * ((S.povm x).mats a).val

/-- The value of a synchronous strategy in `G` (blueprint `def:sync-value`): the players
answer questions `(x, y)` with `(a, b)` with probability `τ(M^x_a M^y_b) = Tr(M^x_a
M^y_b)/d`. For positive semidefinite matrices this trace is a nonnegative real; we take
the real part so that the definition typechecks with no proof obligations. -/
noncomputable def SyncStrategy.value {G : SynchronousGame X A} (S : SyncStrategy G) : ℝ :=
  ∑ x, ∑ y, ∑ a, ∑ b,
    G.μ x y * (if G.D x y a b then 1 else 0) *
      ((((S.povm x).mats a).val * ((S.povm y).mats b).val).trace.re / (S.d : ℝ))

/-- The synchronous value of a synchronous game (blueprint `def:sync-value`): the
supremum of strategy values over all synchronous strategies. -/
noncomputable def syncValue (G : SynchronousGame X A) : ℝ :=
  ⨆ S : SyncStrategy G, S.value

/-! ## Commuting strategies and the commuting value -/

/-- A commuting strategy for a synchronous game (blueprint `def:commuting-strategy`): a
unital C*-algebra `alg` with a tracial state `τ` — a positive linear functional with
`τ(1) = 1` and `τ(mn) = τ(nm)` — together with a family of projective measurements
`{M^x_a}` in `alg`, one for each question `x`: each `M^x_a` is a self-adjoint idempotent
and `∑ₐ M^x_a = 1`. Outcome probabilities are computed with `τ` (see
`CommutingStrategy.value`).

The algebra lives in universe `0`; by the GNS representation this loses no generality
(see the module docstring). -/
structure CommutingStrategy (G : SynchronousGame X A) where
  /-- The underlying unital C*-algebra. -/
  alg : Type
  /-- The C*-algebra structure. -/
  [cstarAlgebra : CStarAlgebra alg]
  /-- The tracial state, as a linear functional. -/
  τ : alg →ₗ[ℂ] ℂ
  /-- The functional `τ` is positive. -/
  τ_nonneg : ∀ m : alg, 0 ≤ τ (star m * m)
  /-- The functional `τ` is unital. -/
  τ_one : τ 1 = 1
  /-- The functional `τ` is tracial. -/
  τ_mul_comm : ∀ m n : alg, τ (m * n) = τ (n * m)
  /-- The measurement operators, indexed by questions and answers. -/
  M : X → A → alg
  /-- Each measurement operator is self-adjoint. -/
  selfAdjoint : ∀ x a, star (M x a) = M x a
  /-- Each measurement operator is idempotent, hence a projection. -/
  projective : ∀ x a, M x a * M x a = M x a
  /-- For each question, the measurement operators sum to one. -/
  normalized : ∀ x, ∑ a, M x a = 1

attribute [instance] CommutingStrategy.cstarAlgebra

/-- The value of a commuting strategy in `G` (blueprint `def:commuting-value`): the
players answer questions `(x, y)` with `(a, b)` with probability `τ(M^x_a M^y_b)`, a
nonnegative real since `τ(M^x_a M^y_b) = τ(M^x_a M^y_b M^x_a)`; we take the real part so
that the definition typechecks with no proof obligations. -/
noncomputable def CommutingStrategy.value {G : SynchronousGame X A}
    (S : CommutingStrategy G) : ℝ :=
  ∑ x, ∑ y, ∑ a, ∑ b,
    G.μ x y * (if G.D x y a b then 1 else 0) * (S.τ (S.M x a * S.M y b)).re

/-- The commuting value of a synchronous game (blueprint `def:commuting-value`): the
supremum of strategy values over all commuting strategies. -/
noncomputable def commValue (G : SynchronousGame X A) : ℝ :=
  ⨆ S : CommutingStrategy G, S.value

/-! ## Entanglement requirement -/

/-- The entanglement requirement `Ent(G, ν)` (blueprint `def:ent`): the least `d` such
that there exists a synchronous strategy with dimension at most `d` achieving value at
least `ν` in `G`, and `∞` if no synchronous strategy achieves `ν`. It is realized as the
infimum in `ℕ∞` of the dimensions of the achieving strategies, which takes the value
`⊤ = ∞` when there are none. -/
noncomputable def entRequirement (G : SynchronousGame X A) (ν : ℝ) : ℕ∞ :=
  ⨅ S : {S : SyncStrategy G // ν ≤ S.value}, (S.val.d : ℕ∞)

/-! ## Relationship lemmas -/

/-- The synchronous value lower-bounds the quantum value (blueprint
`lem:sync-le-valstar`): a synchronous strategy `{M^x_a}` on `ℂ^d` yields the
tensor-product strategy `A^x_a = M^x_a`, `B^y_b = (M^y_b)ᵀ`,
`ψ = d^{-1/2} ∑ᵢ |i⟩|i⟩` with the same value. -/
theorem syncValue_le_quantumValue (G : SynchronousGame X A) :
    syncValue G ≤ quantumValue G.toGame :=
  sorry

/-- The synchronous value lower-bounds the commuting value (blueprint
`lem:sync-le-valco`): a synchronous strategy on `ℂ^d` is a commuting strategy with
`alg = ℂ^{d × d}` and `τ = Tr/d`, with the same value. -/
theorem syncValue_le_commValue (G : SynchronousGame X A) :
    syncValue G ≤ commValue G :=
  sorry

end MIPRE
