/-
Copyright (c) 2026 MIPRE contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import MIPRE.Foundations.GameAdapt

/-! # Games generated from finite uniform samples

Unlike `SeededGame`, the seed and the two question alphabets may differ.
This is needed for typed games, whose seed is an edge and a common vector.
-/

noncomputable section

namespace MIPRE

open Finset Classical

set_option linter.unusedSectionVars false

namespace SampledGame

variable {S X Y : Type*} [Fintype S] [Fintype X] [Fintype Y]

/-- Push forward the uniform law by the two question maps. -/
def dist (qA : S → X) (qB : S → Y) (x : X) (y : Y) : ℝ :=
  (Fintype.card S : ℝ)⁻¹ * ∑ s, if (qA s, qB s) = (x, y) then 1 else 0

/-- The sample law is the normalized cardinality of each question pair's fibre. -/
theorem dist_eq_card (qA : S → X) (qB : S → Y) (x : X) (y : Y) :
    dist qA qB x y = ((univ.filter fun s => qA s = x ∧ qB s = y).card : ℝ) / Fintype.card S := by
  simp only [dist, Prod.mk.injEq, ← Finset.sum_filter, Finset.sum_const, nsmul_eq_mul, mul_one]
  ring

/-- Averages over questions are averages over the common sample. -/
theorem sum_dist_mul (qA : S → X) (qB : S → Y) (f : X → Y → ℝ) :
    ∑ x, ∑ y, dist qA qB x y * f x y = (∑ s, f (qA s) (qB s)) / Fintype.card S := by
  rw [← Fintype.sum_prod_type' fun x y => dist qA qB x y * f x y]
  simp only [dist, mul_assoc, Finset.sum_mul, ← Finset.mul_sum]
  rw [Finset.sum_comm]
  have hs : ∀ s, (∑ p : X × Y, (if (qA s, qB s) = p then (1 : ℝ) else 0) * f p.1 p.2) =
      f (qA s) (qB s) := by
    intro s
    rw [Finset.sum_eq_single (qA s, qB s)]
    · simp
    · intro p _ hp
      simp [Ne.symm hp]
    · simp
  simp only [hs]
  ring

/-- A uniform sample law is nonnegative. -/
theorem dist_nonneg (qA : S → X) (qB : S → Y) (x : X) (y : Y) : 0 ≤ dist qA qB x y :=
  mul_nonneg (inv_nonneg.mpr (Nat.cast_nonneg _))
    (Finset.sum_nonneg fun _ _ => by split_ifs <;> norm_num)

/-- A nonempty sample space gives a probability distribution. -/
theorem sum_dist [Nonempty S] (qA : S → X) (qB : S → Y) : ∑ x, ∑ y, dist qA qB x y = 1 := by
  have h := sum_dist_mul qA qB (fun _ _ => 1)
  have hc : (Fintype.card S : ℝ) ≠ 0 := by exact_mod_cast Fintype.card_ne_zero
  simpa [hc] using h

/-- The finite game generated by the question maps and decision predicate. -/
def game [Nonempty S] {A B : Type*} [Fintype A] [Fintype B]
    (qA : S → X) (qB : S → Y) (D : X → Y → A → B → Bool) : Game X Y A B where
  μ := dist qA qB
  μ_nonneg := dist_nonneg qA qB
  μ_sum_one := sum_dist qA qB
  D := D

/-- The failure probability of a strategy is the uniform average of its conditional failures. -/
theorem one_sub_value [Nonempty S] {A B : Type*} [Fintype A] [Fintype B]
    (qA : S → X) (qB : S → Y) (D : X → Y → A → B → Bool)
    (R : TensorProductStrategy (game qA qB D)) :
    1 - R.value = (∑ s, R.failAt (qA s) (qB s)) / Fintype.card S := by
  rw [R.one_sub_value_eq_sum_failAt]
  exact sum_dist_mul qA qB R.failAt

end SampledGame
end MIPRE
