/-
Copyright (c) 2026 the commuting-repetition contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE. Vendored from
https://github.com/vidick/commuting-repetition (commit cfa2f1bf, 2026-09-11) by scripts/vendor-repetition.py;
do not edit by hand. Upstream path: lean/CommutingRepetition/Tracial/Density/StandardStrategy.lean
-/
/-
# The standard form of a commuting strategy (stage E7.2)

Given a commuting-operator strategy `S`, compress it to the separable subspace
`closure(C*(A,B)ψ)` (`Compress.lean`), let `N` be the von Neumann algebra generated by
Alice's effects — so Bob's effects lie in `N′` — and let `φ = ∑ₖ ⟪gₖ, · gₖ⟫` be the
faithful near-vector state of `GVec.lean`. The standard form of `(N, φ)`
(`VN/StandardFormOf.lean`) then carries:

* a cyclic separating unit vector `Ω = Ξ`,
* Alice's POVM `θ(E_a^x)` inside `M = sfAlg`,
* Bob's POVM `θ(F_b^y)` inside `M′` — the compression of `F ⊗ 1` commutes with the
  compression of `N ⊗ 1` (`VN/Cutdown.compressTo_commute_commutant`), so no
  Radon–Nikodym theorem is needed for Bob, and
* the correlation `re ⟪Ω, θ(E_a^x) θ(F_b^y) Ω⟫ = re φ(E_a^x F_b^y)`, which is
  `2ε/(1−ε)`-close to `p(a,b|x,y)` entrywise.

The output is packaged as `StdStrategy`, the input of the crossed-product stage. Proof-side.
-/
import Mathlib
import MIPRE.Background.Repetition.CommutingRepetition.Tracial.Density.GVec
import MIPRE.Background.Repetition.CommutingRepetition.Tracial.Density.Compress
import MIPRE.Background.Repetition.CommutingRepetition.VN.StandardFormOf
import MIPRE.Background.Repetition.CommutingRepetition.VN.Generated
import MIPRE.Background.Repetition.CommutingRepetition.Tracial.Density

-- Upstream builds with Lean's default `autoImplicit = true`; this repository turns it
-- off in `lakefile.toml`. Inserted by scripts/vendor-repetition.py.
set_option autoImplicit true

namespace CommutingRepetition

namespace Density

open scoped InnerProductSpace ComplexOrder
open VN TopologicalSpace

set_option linter.unusedSectionVars false

/-! ## `sfMap` beyond `N` -/

section SfExtra

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

theorem exists_sqrt_op {A : H →L[ℂ] H} (h0 : 0 ≤ A) :
    ∃ r : H →L[ℂ] H, IsSelfAdjoint r ∧ r * r = A := by
  refine ⟨cfc Real.sqrt A, cfc_predicate _ _, ?_⟩
  have hsa : IsSelfAdjoint A := IsSelfAdjoint.of_nonneg h0
  rw [← cfc_mul Real.sqrt Real.sqrt A Real.continuous_sqrt.continuousOn
    Real.continuous_sqrt.continuousOn]
  calc cfc (fun t : ℝ => Real.sqrt t * Real.sqrt t) A = cfc (fun t : ℝ => t) A :=
        cfc_congr fun t ht => Real.mul_self_sqrt (spectrum_nonneg_of_nonneg h0 ht)
    _ = A := cfc_id' ℝ A hsa

/-- POVM elements are contractions. -/
theorem norm_povm_le_one {ι : Type*} [Fintype ι] [DecidableEq ι] (E : ι → H →L[ℂ] H)
    (hpos : ∀ i, (E i).IsPositive) (hsum : ∑ i, E i = 1) (i : ι) : ‖E i‖ ≤ 1 := by
  have h0 : (0 : H →L[ℂ] H) ≤ E i := (ContinuousLinearMap.nonneg_iff_isPositive _).mpr (hpos i)
  have h1 : E i ≤ 1 := by
    rw [ContinuousLinearMap.le_def]
    rw [← Finset.add_sum_erase _ _ (Finset.mem_univ i)] at hsum
    rw [← hsum, add_sub_cancel_left]
    exact ContinuousLinearMap.isPositive_sum _ fun i' _ => hpos i'
  exact (CStarAlgebra.norm_le_one_iff_of_nonneg _ h0).mpr h1

variable (N : VonNeumannAlgebra H) (g : ℕ → H) (hg : Summable fun k => ‖g k‖ ^ 2)

theorem sfMap_zero : sfMap N g hg 0 = 0 := by
  rw [sfMap, ampl_zero, compressTo_zero]

theorem sfMap_finset_sum {ι : Type*} (s : Finset ι) (f : ι → H →L[ℂ] H) :
    sfMap N g hg (∑ i ∈ s, f i) = ∑ i ∈ s, sfMap N g hg (f i) := by
  classical
  induction s using Finset.induction with
  | empty => rw [Finset.sum_empty, Finset.sum_empty, sfMap_zero]
  | insert a s ha ih => rw [Finset.sum_insert ha, Finset.sum_insert ha, sfMap_add, ih]

theorem sfMap_nonneg {T : H →L[ℂ] H} (h0 : 0 ≤ T) : 0 ≤ sfMap N g hg T := by
  obtain ⟨r, hrsa, hr⟩ := exists_sqrt_op h0
  have e : ampl T = star (ampl r) * ampl r := by
    rw [← ampl_star, hrsa.star_eq, ← ampl_mul, hr]
  rw [sfMap, e]
  exact compressTo_star_mul_self_nonneg _ _

/-- `θ` is multiplicative when the *left* factor is in `N`, for an arbitrary right factor. -/
theorem sfMap_mul_left {x : H →L[ℂ] H} (hx : x ∈ N) (T : H →L[ℂ] H) :
    sfMap N g hg x * sfMap N g hg T = sfMap N g hg (x * T) := by
  have hP : (sfSpace N g hg).starProjection ∈ (amplAlg N).commutant :=
    starProjection_mem_commutant (sfSpace N g hg) (amplAlg N) (sfSpace_invariant N g hg)
  have hax : ampl x ∈ amplAlg N := ampl_mem_amplAlg N hx
  rw [sfMap, sfMap, sfMap, compressTo_mul_eq, ← commutant_mul_of_mem hax hP, mul_assoc,
    compressTo_starProjection_mul, ampl_mul]

theorem norm_sfVec_sq : ‖sfVec N g hg‖ ^ 2 = ∑' k, ‖g k‖ ^ 2 := by
  rw [show ‖sfVec N g hg‖ = ‖(sfVec N g hg : Hinf H)‖ from rfl, coe_sfVec, sfXi, norm_sq_eq_tsum]
  exact tsum_congr fun k => by rw [mkVec_apply]

variable (hfaith : ∀ x ∈ N, ∑' k, ⟪g k, (star x * x) (g k)⟫_ℂ = 0 → x = 0)

include hfaith in
/-- **Bob transports to the commutant**: the compression of `T ⊗ 1` for `T ∈ N′` commutes
with `M = sfAlg`. -/
theorem sfMap_mem_commutant {T : H →L[ℂ] H} (hT : T ∈ N.commutant) :
    sfMap N g hg T ∈ (sfAlg N g hg hfaith).commutant := by
  rw [VonNeumannAlgebra.mem_commutant_iff]
  intro S hS
  obtain ⟨x, hx, rfl⟩ := sfMap_surjective N g hg hfaith hS
  have hamplT : ampl T ∈ (amplAlg N).commutant := by
    rw [VonNeumannAlgebra.mem_commutant_iff]
    rintro _ ⟨z, hz, rfl⟩
    rw [← ampl_mul, ← ampl_mul, VonNeumannAlgebra.mem_commutant_iff.mp hT z hz]
  exact compressTo_commute_commutant (sfSpace N g hg) (amplAlg N) (sfSpace_invariant N g hg)
    (ampl_mem_amplAlg N hx) hamplT

end SfExtra

/-! ## Alice's algebra -/

section Alg

variable {X Y A B : Type} [Fintype X] [Fintype Y] [Fintype A] [Fintype B]
variable (S : CommutingStrategy.{0} X Y A B)

/-- Alice's effects, as a generating set. -/
def aliceSet : Set (S.H →L[ℂ] S.H) := {T | ∃ x a, T = S.E x a}

/-- Alice's von Neumann algebra. -/
noncomputable def aliceAlg : VonNeumannAlgebra S.H := wstar (aliceSet S)

theorem E_mem_aliceAlg (x : X) (a : A) : S.E x a ∈ aliceAlg S := subset_wstar ⟨x, a, rfl⟩

theorem F_mem_aliceAlg_commutant (y : Y) (b : B) : S.F y b ∈ (aliceAlg S).commutant := by
  rw [VonNeumannAlgebra.mem_commutant_iff]
  intro T hT
  refine (mem_wstar_iff.mp hT (S.F y b) ?_).symm
  rw [StarSubalgebra.mem_centralizer_iff]
  rintro _ ⟨x, a, rfl⟩
  have hc : S.E x a * S.F y b = S.F y b * S.E x a := S.commutes x y a b
  have hsa : star (S.E x a) = S.E x a := (S.E_pos x a).isSelfAdjoint.star_eq
  exact ⟨hc, by rw [hsa]; exact hc⟩

end Alg

/-! ## The packaged standard-form strategy -/

/-- A commuting strategy in standard form: a von Neumann algebra `M` with a cyclic separating
unit vector `Ω`, Alice's POVM inside `M` and Bob's POVM inside `M′`. -/
structure StdStrategy (X Y A B : Type) [Fintype X] [Fintype Y] [Fintype A] [Fintype B] where
  K : Type
  [nacg : NormedAddCommGroup K]
  [ips : InnerProductSpace ℂ K]
  [cspace : CompleteSpace K]
  M : VonNeumannAlgebra K
  Ω : K
  Ω_norm : ‖Ω‖ = 1
  sep : IsSeparating (M : Set (K →L[ℂ] K)) Ω
  cyc : IsCyclic (M : Set (K →L[ℂ] K)) Ω
  Aop : X → A → K →L[ℂ] K
  Aop_mem : ∀ x a, Aop x a ∈ M
  Aop_nonneg : ∀ x a, 0 ≤ Aop x a
  Aop_sum : ∀ x, ∑ a : A, Aop x a = 1
  Bop : Y → B → K →L[ℂ] K
  Bop_mem : ∀ y b, Bop y b ∈ M.commutant
  Bop_nonneg : ∀ y b, 0 ≤ Bop y b
  Bop_sum : ∀ y, ∑ b : B, Bop y b = 1

attribute [instance] StdStrategy.nacg StdStrategy.ips StdStrategy.cspace

namespace StdStrategy

variable {X Y A B : Type} [Fintype X] [Fintype Y] [Fintype A] [Fintype B]

/-- The correlation of a standard-form strategy. -/
noncomputable def corr (q : StdStrategy X Y A B) : Correlation X Y A B := fun x y a b =>
  (⟪q.Ω, q.Aop x a (q.Bop y b q.Ω)⟫_ℂ).re

end StdStrategy

/-! ## Construction -/

section Build

variable {X Y A B : Type} [Fintype X] [Fintype Y] [Fintype A] [Fintype B]

/-- The standard-form strategy attached to a separable commuting strategy and an `ε ∈ (0,1)`. -/
noncomputable def stdOf (S : CommutingStrategy.{0} X Y A B) [SeparableSpace S.H]
    [Nonempty S.H] {ε : ℝ} (hε0 : 0 < ε) (hε1 : ε < 1) : StdStrategy X Y A B :=
  let u := denseSeq S.H
  let g := gvec S.ψ u ε
  let hg := summable_norm_gvec_sq S.ψ u S.ψ_norm hε0 hε1
  let hfaith : ∀ x ∈ aliceAlg S, ∑' k, ⟪g k, (star x * x) (g k)⟫_ℂ = 0 → x = 0 :=
    fun x _ h => gvecState_faithful S.ψ u S.ψ_norm hε0 hε1 (denseRange_denseSeq S.H) x h
  { K := sfSpace (aliceAlg S) g hg
    M := sfAlg (aliceAlg S) g hg hfaith
    Ω := sfVec (aliceAlg S) g hg
    Ω_norm := by
      have h := norm_sfVec_sq (aliceAlg S) g hg
      rw [tsum_norm_gvec_sq S.ψ u S.ψ_norm hε0 hε1] at h
      nlinarith [norm_nonneg (sfVec (aliceAlg S) g hg), h]
    sep := sfVec_isSeparating (aliceAlg S) g hg hfaith
    cyc := sfVec_isCyclic (aliceAlg S) g hg hfaith
    Aop := fun x a => sfMap (aliceAlg S) g hg (S.E x a)
    Aop_mem := fun x a => sfMap_mem (aliceAlg S) g hg hfaith (E_mem_aliceAlg S x a)
    Aop_nonneg := fun x a => sfMap_nonneg (aliceAlg S) g hg
      ((ContinuousLinearMap.nonneg_iff_isPositive _).mpr (S.E_pos x a))
    Aop_sum := fun x => by
      rw [← sfMap_finset_sum (aliceAlg S) g hg, S.E_sum x, sfMap_one]
    Bop := fun y b => sfMap (aliceAlg S) g hg (S.F y b)
    Bop_mem := fun y b => sfMap_mem_commutant (aliceAlg S) g hg hfaith
      (F_mem_aliceAlg_commutant S y b)
    Bop_nonneg := fun y b => sfMap_nonneg (aliceAlg S) g hg
      ((ContinuousLinearMap.nonneg_iff_isPositive _).mpr (S.F_pos y b))
    Bop_sum := fun y => by
      rw [← sfMap_finset_sum (aliceAlg S) g hg, S.F_sum y, sfMap_one] }

theorem stdOf_corr (S : CommutingStrategy.{0} X Y A B) [SeparableSpace S.H] [Nonempty S.H]
    {ε : ℝ} (hε0 : 0 < ε) (hε1 : ε < 1) (x : X) (y : Y) (a : A) (b : B) :
    (stdOf S hε0 hε1).corr x y a b
      = (gvecState S.ψ (denseSeq S.H) ε (S.E x a * S.F y b)).re := by
  show (⟪sfVec _ _ _, sfMap _ _ _ (S.E x a) (sfMap _ _ _ (S.F y b) (sfVec _ _ _))⟫_ℂ).re = _
  rw [← mul_apply_eq_comp, sfMap_mul_left _ _ _ (E_mem_aliceAlg S x a), inner_sfVec_sfMap]
  rfl

end Build

end Density

end CommutingRepetition
