/-
Copyright (c) 2026 the commuting-repetition contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE. Vendored from
https://github.com/vidick/commuting-repetition (commit 8ff85e29, 2026-09-10) by scripts/vendor-repetition.py;
do not edit by hand. Upstream path: orthogonalization/Orthogonalization/Blocks/Corollaries.lean
-/
/-
# Tier T1b corollaries: Theorems 1.1 and 1.4 in finite dimension

Formalization of M. de la Salle, *Orthogonalization of Positive Operator Valued
Measures* (arXiv:2103.14126v2, `manuscript/arXiv2103.14126v2.tex`), tier T1b
(`PLAN.md` §3): the two Section 1 companions of Theorem 1.2 on a
finite-dimensional Hilbert space `H`.

* `povm_orthogonalization_hilbert_finDim` — **Theorem 1.1**
  (`thm:orthonormalization_Hilbert`) with the commutant clause: Theorem 1.2
  (`povm_orthogonalization_finDim_vn`, `Blocks/Main.lean`) applied to the von
  Neumann algebra `W*(a_i)` generated by the POVM and to the vector state
  `x ↦ ⟪ξ, x ξ⟫`; the projections lie in `W*(a_i)`, hence commute with every
  operator commuting with the `a_i`.
* `pvm_almost_commute_finDim` — **Theorem 1.4** (`thm:pvm_almost_commute`),
  following Section 5 of the paper: the compressed POVM `a_i = ∑_j q_j p_i q_j`,
  the identity `∑_{i,j} ‖p_i q_j − q_j p_i‖_φ² = ∑_i ‖p_i − a_i‖_φ² + (1 − φ(∑ a_i²))`,
  Theorem 1.2 in `W*(a_i)` (whose elements commute with the `q_j`), and the
  triangle inequality for `‖·‖_φ` — proved here for a state positive on `M`
  only, by the discriminant form of the Cauchy–Schwarz inequality — together
  with `(√D + √E)² ≤ 10 (D + E/9)`.

Both theorems are literal *instances* of the signed statements
`povm_orthogonalization_hilbert` and `pvm_almost_commute` of
`Orthogonalization/Basic.lean` with `[FiniteDimensional ℂ H]` added
(FIDELITY.md, "Instances of signed statements"); they carry no review row of
their own. The proof-side helpers live in the namespace
`Orthogonalization.Corollaries` and hold on any complete `H`.
-/
import Mathlib
import MIPRE.Background.Repetition.CommutingRepetition.VN.Generated
import MIPRE.Background.Orthonormalization.Orthogonalization.Basic
import MIPRE.Background.Orthonormalization.Orthogonalization.Positivity
import MIPRE.Background.Orthonormalization.Orthogonalization.PhiNorm
import MIPRE.Background.Orthonormalization.Orthogonalization.Blocks.StateOnM
import MIPRE.Background.Orthonormalization.Orthogonalization.Blocks.Bicommutant
import MIPRE.Background.Orthonormalization.Orthogonalization.Blocks.Main

-- Upstream builds with Lean's default `autoImplicit = true`; this repository turns it
-- off in `lakefile.toml`. Inserted by scripts/vendor-repetition.py.
set_option autoImplicit true

namespace Orthogonalization

open scoped BigOperators ComplexOrder InnerProductSpace

namespace Corollaries

section General

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-! ### Vector states -/

/-- The vector functional `x ↦ ⟪ξ, x ξ⟫`. -/
noncomputable def vecFunctional (ξ : H) : (H →L[ℂ] H) →ₗ[ℂ] ℂ where
  toFun x := ⟪ξ, x ξ⟫_ℂ
  map_add' x y := by simp
  map_smul' c x := by simp

omit [CompleteSpace H] in
theorem vecFunctional_apply (ξ : H) (x : H →L[ℂ] H) : vecFunctional ξ x = ⟪ξ, x ξ⟫_ℂ := rfl

/-- `⟪ξ, (b* b) ξ⟫ = ‖b ξ‖²`. -/
theorem vecFunctional_star_mul_self (ξ : H) (b : H →L[ℂ] H) :
    vecFunctional ξ (star b * b) = ((‖b ξ‖ ^ 2 : ℝ) : ℂ) := by
  rw [vecFunctional_apply, mul_apply_eq_comp, ContinuousLinearMap.star_eq_adjoint,
    ContinuousLinearMap.adjoint_inner_right, inner_self_eq_norm_sq_to_K]
  norm_cast

theorem re_vecFunctional_star_mul_self (ξ : H) (b : H →L[ℂ] H) :
    (vecFunctional ξ (star b * b)).re = ‖b ξ‖ ^ 2 := by
  rw [vecFunctional_star_mul_self, Complex.ofReal_re]

theorem vecFunctional_star_mul_self_nonneg (ξ : H) (b : H →L[ℂ] H) :
    0 ≤ vecFunctional ξ (star b * b) := by
  rw [vecFunctional_star_mul_self]
  exact Complex.zero_le_real.mpr (sq_nonneg _)

omit [CompleteSpace H] in
theorem vecFunctional_one (ξ : H) (hξ : ‖ξ‖ = 1) : vecFunctional ξ 1 = 1 := by
  rw [vecFunctional_apply, one_apply_eq_self, inner_self_eq_norm_sq_to_K, hξ]
  norm_num

/-- `⟪ξ, (∑ a_i²) ξ⟫ = ∑ ‖a_i ξ‖²` for self-adjoint `a_i`. -/
theorem re_vecFunctional_sum_mul_self {ι : Type*} [Fintype ι] (ξ : H) (a : ι → H →L[ℂ] H)
    (ha : ∀ i, IsSelfAdjoint (a i)) :
    (vecFunctional ξ (∑ i, a i * a i)).re = ∑ i, ‖a i ξ‖ ^ 2 := by
  rw [map_sum, Complex.re_sum]
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [← re_vecFunctional_star_mul_self ξ (a i), (ha i).star_eq]

/-- `⟪ξ, (∑ |a_i − p_i|²) ξ⟫ = ∑ ‖a_i ξ − p_i ξ‖²`. -/
theorem re_vecFunctional_sum_star_sub_mul_sub {ι : Type*} [Fintype ι] (ξ : H)
    (a p : ι → H →L[ℂ] H) :
    (vecFunctional ξ (∑ i, star (a i - p i) * (a i - p i))).re = ∑ i, ‖a i ξ - p i ξ‖ ^ 2 := by
  rw [map_sum, Complex.re_sum]
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [re_vecFunctional_star_mul_self, sub_apply]

/-- The vector state `x ↦ ⟪ξ, x ξ⟫` of a unit vector `ξ`, as a normal state of any von
Neumann algebra `M` (it is positive and normal on all of `B(H)`). -/
noncomputable def vecState (M : VonNeumannAlgebra H) (ξ : H) (hξ : ‖ξ‖ = 1) :
    NormalState M where
  toLinearMap := vecFunctional ξ
  map_one' := vecFunctional_one ξ hξ
  nonneg' := fun x _ => vecFunctional_star_mul_self_nonneg ξ x
  normal' := fun _ _ _ _ _ h =>
    ((continuous_const.inner continuous_id).tendsto _).comp (h.tendsto ξ)

theorem vecState_apply (M : VonNeumannAlgebra H) (ξ : H) (hξ : ‖ξ‖ = 1) (x : H →L[ℂ] H) :
    vecState M ξ hξ x = vecFunctional ξ x := rfl

/-! ### Restriction of a normal state to a smaller von Neumann algebra -/

/-- A normal state of `M` is a normal state of every von Neumann subalgebra `N ≤ M`
(same functional; DIFFERENCES.md D1). -/
def restrictState {M N : VonNeumannAlgebra H} (φ : NormalState M) (hNM : ∀ x ∈ N, x ∈ M) :
    NormalState N where
  toLinearMap := φ.toLinearMap
  map_one' := φ.map_one'
  nonneg' := fun x hx => φ.nonneg' x (hNM x hx)
  normal' := fun l T L hT hL h => φ.normal' l T L (fun k => hNM _ (hT k)) (hNM _ hL) h

theorem restrictState_apply {M N : VonNeumannAlgebra H} (φ : NormalState M)
    (hNM : ∀ x ∈ N, x ∈ M) (x : H →L[ℂ] H) : restrictState φ hNM x = φ x := rfl

/-! ### The seminorm of a normal state -/

variable {M : VonNeumannAlgebra H}

/-- `‖x‖_φ² ≥ 0` for `x ∈ M`. -/
theorem normSq_nonneg_of_mem (φ : NormalState M) {x : H →L[ℂ] H} (hx : x ∈ M) :
    0 ≤ φ.normSq x :=
  (Complex.nonneg_iff.mp (φ.nonneg' x hx)).1

/-- Real arithmetic behind the discriminant argument: if `0 ≤ s² A − s t B + t² D` for all
real `s, t`, with `A, D ≥ 0`, then `B ≤ 2 √A √D`. -/
theorem le_two_mul_sqrt_mul_sqrt {A B D : ℝ} (hA : 0 ≤ A) (hD : 0 ≤ D)
    (h : ∀ s t : ℝ, 0 ≤ s ^ 2 * A - s * t * B + t ^ 2 * D) :
    B ≤ 2 * (Real.sqrt A * Real.sqrt D) := by
  refine not_lt.mp fun hcon => ?_
  have hB : 0 < B := lt_of_le_of_lt (by positivity) hcon
  rcases hD.lt_or_eq with hDpos | hD0
  · -- `s = 2D`, `t = B`: `0 ≤ D (4 A D − B²)`, hence `B² ≤ 4 A D = (2 √A √D)²`.
    have h1 := h (2 * D) B
    have h2 : B ^ 2 ≤ 4 * (A * D) := by nlinarith [h1, hDpos]
    have hsq : (2 * (Real.sqrt A * Real.sqrt D)) ^ 2 = 4 * (A * D) := by
      rw [mul_pow, mul_pow, Real.sq_sqrt hA, Real.sq_sqrt hD]; ring
    have hc : 0 ≤ 2 * (Real.sqrt A * Real.sqrt D) := by positivity
    nlinarith [mul_pos (sub_pos.mpr hcon) (sub_pos.mpr hcon),
      mul_nonneg (sub_pos.mpr hcon).le hc, hsq, h2]
  · -- `D = 0`, `s = B`, `t = A + 1`: `0 ≤ −B²`.
    subst hD0
    have h1 := h B (A + 1)
    nlinarith [h1, mul_pos hB hB]

/-- **Cauchy–Schwarz (real form)** for a functional positive on `M`: for `x, y ∈ M`,
`Re φ(x* y) + Re φ(y* x) ≤ 2 ‖x‖_φ ‖y‖_φ`. -/
theorem re_add_re_le_of_mem {φ : (H →L[ℂ] H) →ₗ[ℂ] ℂ} (hφ : ∀ x ∈ M, 0 ≤ φ (star x * x))
    {x y : H →L[ℂ] H} (hx : x ∈ M) (hy : y ∈ M) :
    (φ (star x * y)).re + (φ (star y * x)).re
      ≤ 2 * (Real.sqrt (φ (star x * x)).re * Real.sqrt (φ (star y * y)).re) := by
  refine le_two_mul_sqrt_mul_sqrt (Complex.nonneg_iff.mp (hφ x hx)).1
    (Complex.nonneg_iff.mp (hφ y hy)).1 fun s t => ?_
  have hz : (s : ℂ) • x - (t : ℂ) • y ∈ M :=
    sub_mem (Blocks.smul_mem_vn M _ hx) (Blocks.smul_mem_vn M _ hy)
  -- expand `0 ≤ φ((s x − t y)* (s x − t y))` and take real parts
  have h0 := (Complex.nonneg_iff.mp (hφ _ hz)).1
  rw [star_sub, star_smul, star_smul, Complex.star_def, Complex.conj_ofReal,
    Complex.conj_ofReal] at h0
  simp only [sub_mul, mul_sub, smul_mul_assoc, mul_smul_comm, smul_sub, smul_smul, map_sub,
    map_smul, smul_eq_mul, Complex.sub_re, mul_assoc, Complex.re_ofReal_mul] at h0
  nlinarith [h0]

/-- **Triangle inequality (squared form)** for the seminorm of tuples, for a state positive
on `M` only: if all `b_i, c_i ∈ M`, then
`∑ ‖b_i + c_i‖_φ² ≤ (√(∑ ‖b_i‖_φ²) + √(∑ ‖c_i‖_φ²))²`. -/
theorem sum_re_add_le {φ : (H →L[ℂ] H) →ₗ[ℂ] ℂ} (hφ : ∀ x ∈ M, 0 ≤ φ (star x * x))
    {ι : Type*} [Fintype ι] (b c : ι → H →L[ℂ] H) (hb : ∀ i, b i ∈ M) (hc : ∀ i, c i ∈ M) :
    ∑ i, (φ (star (b i + c i) * (b i + c i))).re
      ≤ (Real.sqrt (∑ i, (φ (star (b i) * b i)).re)
          + Real.sqrt (∑ i, (φ (star (c i) * c i)).re)) ^ 2 := by
  have hFnn : ∀ i, 0 ≤ (φ (star (b i) * b i)).re := fun i =>
    (Complex.nonneg_iff.mp (hφ _ (hb i))).1
  have hGnn : ∀ i, 0 ≤ (φ (star (c i) * c i)).re := fun i =>
    (Complex.nonneg_iff.mp (hφ _ (hc i))).1
  -- Step 1: coordinatewise bound.
  have step1 : ∀ i ∈ (Finset.univ : Finset ι),
      (φ (star (b i + c i) * (b i + c i))).re
        ≤ (φ (star (b i) * b i)).re
          + 2 * (Real.sqrt ((φ (star (b i) * b i)).re) * Real.sqrt ((φ (star (c i) * c i)).re))
          + (φ (star (c i) * c i)).re := by
    intro i _
    have e := re_map_star_add_mul_add (φ := φ) b c i
    simp only [Pi.add_apply] at e
    rw [e]
    have := re_add_re_le_of_mem hφ (hb i) (hc i)
    linarith
  -- Step 2: sum the coordinatewise bounds.
  have step2 : ∑ i, (φ (star (b i + c i) * (b i + c i))).re
      ≤ ∑ i, (φ (star (b i) * b i)).re
        + 2 * (∑ i, Real.sqrt ((φ (star (b i) * b i)).re)
                      * Real.sqrt ((φ (star (c i) * c i)).re))
        + ∑ i, (φ (star (c i) * c i)).re := by
    calc ∑ i, (φ (star (b i + c i) * (b i + c i))).re
        ≤ ∑ i, ((φ (star (b i) * b i)).re
            + 2 * (Real.sqrt ((φ (star (b i) * b i)).re)
                    * Real.sqrt ((φ (star (c i) * c i)).re))
            + (φ (star (c i) * c i)).re) := Finset.sum_le_sum step1
      _ = _ := by rw [Finset.sum_add_distrib, Finset.sum_add_distrib, ← Finset.mul_sum]
  -- Step 3: discrete Cauchy–Schwarz on the cross term.
  have step3 : (∑ i, Real.sqrt ((φ (star (b i) * b i)).re)
                        * Real.sqrt ((φ (star (c i) * c i)).re))
      ≤ Real.sqrt (∑ i, (φ (star (b i) * b i)).re)
          * Real.sqrt (∑ i, (φ (star (c i) * c i)).re) :=
    Real.sum_sqrt_mul_sqrt_le Finset.univ hFnn hGnn
  have hBn : 0 ≤ ∑ i, (φ (star (b i) * b i)).re := Finset.sum_nonneg fun i _ => hFnn i
  have hCn : 0 ≤ ∑ i, (φ (star (c i) * c i)).re := Finset.sum_nonneg fun i _ => hGnn i
  nlinarith [step2, step3, Real.sq_sqrt hBn, Real.sq_sqrt hCn]

/-- The triangle inequality in the form used for Theorem 1.4:
`∑ ‖b_i + c_i‖_φ² ≤ (√(∑ ‖b_i‖_φ²) + √(∑ ‖c_i‖_φ²))²` for `b_i, c_i ∈ M`. -/
theorem sum_normSq_add_le (φ : NormalState M) {ι : Type*} [Fintype ι]
    (b c : ι → H →L[ℂ] H) (hb : ∀ i, b i ∈ M) (hc : ∀ i, c i ∈ M) :
    ∑ i, φ.normSq (b i + c i)
      ≤ (Real.sqrt (∑ i, φ.normSq (b i)) + Real.sqrt (∑ i, φ.normSq (c i))) ^ 2 :=
  sum_re_add_le φ.nonneg' b c hb hc

/-! ### PVMs: orthogonality and the compressed POVM `a_i = ∑_j q_j p_i q_j` -/

variable {ι κ : Type*} [Fintype ι] [Fintype κ] {p : ι → H →L[ℂ] H} {q : κ → H →L[ℂ] H}

/-- The projections of a PVM are pairwise orthogonal: `q_j q_k = 0` for `j ≠ k`. -/
theorem mul_eq_zero_of_ne (hq : IsPVM M q) {j k : κ} (hjk : j ≠ k) : q j * q k = 0 := by
  classical
  have hidem : ∀ l, q l * q l = q l := fun l => (hq.2.1 l).isIdempotentElem.eq
  have hstar : ∀ l, star (q l) = q l := fun l => (hq.2.1 l).isSelfAdjoint.star_eq
  -- each `q_k q_l q_k = (q_l q_k)* (q_l q_k)` is positive
  have hform : ∀ l, star (q l * q k) * (q l * q k) = q k * q l * q k := by
    intro l
    rw [star_mul, hstar, hstar, mul_assoc, ← mul_assoc (q l), hidem, ← mul_assoc]
  have hnn : ∀ l, 0 ≤ q k * q l * q k := fun l => hform l ▸ star_mul_self_nonneg (q l * q k)
  -- and they sum to `q_k`
  have hsum : ∑ l, q k * q l * q k = q k := by
    rw [← Finset.sum_mul, ← Finset.mul_sum, hq.2.2, mul_one, hidem]
  -- so the terms with `l ≠ k` sum to zero, hence vanish
  have hzero : ∑ l ∈ Finset.univ.erase k, q k * q l * q k = 0 := by
    have h := Finset.sum_erase_add Finset.univ (fun l => q k * q l * q k) (Finset.mem_univ k)
    rw [hsum, hidem k, hidem k] at h
    exact add_eq_right.mp h
  have hterm : q k * q j * q k = 0 :=
    (Finset.sum_eq_zero_iff_of_nonneg fun l _ => hnn l).mp hzero j
      (Finset.mem_erase.mpr ⟨hjk, Finset.mem_univ j⟩)
  rw [← hform] at hterm
  exact (CStarRing.star_mul_self_eq_zero_iff _).mp hterm

/-- The compressed POVM `a_i = ∑_j q_j p_i q_j` of Section 5 of the paper. -/
noncomputable def compress (p : ι → H →L[ℂ] H) (q : κ → H →L[ℂ] H) (i : ι) : H →L[ℂ] H :=
  ∑ j, q j * p i * q j

theorem compress_mem (hp : IsPVM M p) (hq : IsPVM M q) (i : ι) : compress p q i ∈ M :=
  sum_mem fun j _ => mul_mem (mul_mem (hq.1 j) (hp.1 i)) (hq.1 j)

theorem compress_star (hp : IsPVM M p) (hq : IsPVM M q) (i : ι) :
    star (compress p q i) = compress p q i := by
  have hps : star (p i) = p i := (hp.2.1 i).isSelfAdjoint.star_eq
  have hqs : ∀ j, star (q j) = q j := fun j => (hq.2.1 j).isSelfAdjoint.star_eq
  unfold compress
  simp only [star_sum, star_mul, hps, hqs, mul_assoc]

theorem compress_nonneg (hp : IsPVM M p) (hq : IsPVM M q) (i : ι) : 0 ≤ compress p q i := by
  have hps : star (p i) = p i := (hp.2.1 i).isSelfAdjoint.star_eq
  have hqs : ∀ j, star (q j) = q j := fun j => (hq.2.1 j).isSelfAdjoint.star_eq
  have hpi' : ∀ x, p i * (p i * x) = p i * x := fun x => by
    rw [← mul_assoc, (hp.2.1 i).isIdempotentElem.eq]
  refine Finset.sum_nonneg fun j _ => ?_
  have : star (p i * q j) * (p i * q j) = q j * p i * q j := by
    rw [star_mul, hqs, hps]
    simp only [mul_assoc, hpi']
  rw [← this]
  exact star_mul_self_nonneg _

theorem sum_compress (hp : IsPVM M p) (hq : IsPVM M q) : ∑ i, compress p q i = 1 := by
  have hqi : ∀ j, q j * q j = q j := fun j => (hq.2.1 j).isIdempotentElem.eq
  have h : ∀ j, ∑ i, q j * p i * q j = q j := fun j => by
    rw [← Finset.sum_mul, ← Finset.mul_sum, hp.2.2, mul_one, hqi]
  unfold compress
  rw [Finset.sum_comm]
  simp only [h]
  exact hq.2.2

theorem isPOVM_compress (hp : IsPVM M p) (hq : IsPVM M q) : IsPOVM M (compress p q) :=
  ⟨compress_mem hp hq, fun i =>
    (ContinuousLinearMap.nonneg_iff_isPositive _).mp (compress_nonneg hp hq i),
    sum_compress hp hq⟩

omit [Fintype ι] in
theorem mul_compress (hq : IsPVM M q) (i : ι) (k : κ) :
    q k * compress p q i = q k * p i * q k := by
  unfold compress
  rw [Finset.mul_sum, Finset.sum_eq_single k]
  · rw [← mul_assoc, ← mul_assoc, (hq.2.1 k).isIdempotentElem.eq]
  · intro j _ hjk
    rw [← mul_assoc, ← mul_assoc, mul_eq_zero_of_ne hq hjk.symm, zero_mul, zero_mul]
  · intro hk
    exact absurd (Finset.mem_univ k) hk

omit [Fintype ι] in
theorem compress_mul (hq : IsPVM M q) (i : ι) (k : κ) :
    compress p q i * q k = q k * p i * q k := by
  unfold compress
  rw [Finset.sum_mul, Finset.sum_eq_single k]
  · rw [mul_assoc, (hq.2.1 k).isIdempotentElem.eq]
  · intro j _ hjk
    rw [mul_assoc, mul_eq_zero_of_ne hq hjk, mul_zero]
  · intro hk
    exact absurd (Finset.mem_univ k) hk

omit [Fintype ι] in
/-- `a_i` commutes with every `q_k`. -/
theorem compress_comm (hq : IsPVM M q) (i : ι) (k : κ) : Commute (compress p q i) (q k) := by
  show compress p q i * q k = q k * compress p q i
  rw [compress_mul hq, mul_compress hq]

/-- `∑_j |p_i q_j − q_j p_i|² = a_i + p_i − a_i p_i − p_i a_i`. -/
theorem sum_star_sub_mul_sub (hp : IsPVM M p) (hq : IsPVM M q) (i : ι) :
    ∑ j, star (p i * q j - q j * p i) * (p i * q j - q j * p i)
      = compress p q i + p i - compress p q i * p i - p i * compress p q i := by
  have hps : star (p i) = p i := (hp.2.1 i).isSelfAdjoint.star_eq
  have hqs : ∀ j, star (q j) = q j := fun j => (hq.2.1 j).isSelfAdjoint.star_eq
  have hpi : p i * p i = p i := (hp.2.1 i).isIdempotentElem.eq
  have hpi' : ∀ x, p i * (p i * x) = p i * x := fun x => by rw [← mul_assoc, hpi]
  have hqj' : ∀ j x, q j * (q j * x) = q j * x := fun j x => by
    rw [← mul_assoc, (hq.2.1 j).isIdempotentElem.eq]
  have e : ∀ j, star (p i * q j - q j * p i) * (p i * q j - q j * p i)
      = q j * p i * q j - q j * p i * q j * p i - p i * (q j * p i * q j) + p i * q j * p i := by
    intro j
    rw [star_sub, star_mul, star_mul, hps, hqs]
    simp only [sub_mul, mul_sub, mul_assoc, hpi', hqj']
    abel
  have h2 : ∑ j, q j * p i * q j * p i = compress p q i * p i := by
    unfold compress; rw [Finset.sum_mul]
  have h3 : ∑ j, p i * (q j * p i * q j) = p i * compress p q i := by
    unfold compress; rw [Finset.mul_sum]
  have h4 : ∑ j, p i * q j * p i = p i := by
    rw [← Finset.sum_mul, ← Finset.mul_sum, hq.2.2, mul_one, hpi]
  rw [Finset.sum_congr rfl fun j _ => e j, Finset.sum_add_distrib, Finset.sum_sub_distrib,
    Finset.sum_sub_distrib, h2, h3, h4]
  unfold compress
  abel

/-- `|p_i − a_i|² = p_i − p_i a_i − a_i p_i + a_i²`. -/
theorem star_sub_compress_mul (hp : IsPVM M p) (hq : IsPVM M q) (i : ι) :
    star (p i - compress p q i) * (p i - compress p q i)
      = p i - p i * compress p q i - compress p q i * p i + compress p q i * compress p q i := by
  rw [star_sub, (hp.2.1 i).isSelfAdjoint.star_eq, compress_star hp hq i, sub_mul, mul_sub, mul_sub,
    (hp.2.1 i).isIdempotentElem.eq]
  abel

/-- The operator identity behind the display of Section 5:
`∑_{i,j} |p_i q_j − q_j p_i|² = ∑_i |p_i − a_i|² + (1 − ∑_i a_i²)`. -/
theorem key_identity (hp : IsPVM M p) (hq : IsPVM M q) :
    ∑ i, ∑ j, star (p i * q j - q j * p i) * (p i * q j - q j * p i)
      = ∑ i, star (p i - compress p q i) * (p i - compress p q i)
        + (1 - ∑ i, compress p q i * compress p q i) := by
  have e : ∀ i, ∑ j, star (p i * q j - q j * p i) * (p i * q j - q j * p i)
      = star (p i - compress p q i) * (p i - compress p q i)
        + (compress p q i - compress p q i * compress p q i) := by
    intro i
    rw [sum_star_sub_mul_sub hp hq i, star_sub_compress_mul hp hq i]
    abel
  rw [Finset.sum_congr rfl fun i _ => e i, Finset.sum_add_distrib, Finset.sum_sub_distrib,
    sum_compress hp hq]

end General

end Corollaries

open Corollaries

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [FiniteDimensional ℂ H]

/-- **Theorem 1.1** (`thm:orthonormalization_Hilbert`) in finite dimension, with the
commutant clause: the instance of the signed statement `povm_orthogonalization_hilbert`
with `[FiniteDimensional ℂ H]` added. Proof: Theorem 1.2 in the von Neumann algebra
`W*(a_i)` with the vector state `x ↦ ⟪ξ, x ξ⟫`; the projections lie in `W*(a_i)`, so they
commute with every `b` commuting with the `a_i` (bicommutant). -/
theorem povm_orthogonalization_hilbert_finDim {ι : Type*} [Fintype ι]
    (a : ι → H →L[ℂ] H) (ha : (∀ i, (a i).IsPositive) ∧ ∑ i, a i = 1)
    (ξ : H) (hξ : ‖ξ‖ = 1) (ε : ℝ) (hε : ε ∈ Set.Icc (0 : ℝ) 1)
    (h : 1 - ε < ∑ i, ‖a i ξ‖ ^ 2) :
    ∃ p : ι → H →L[ℂ] H, (∀ i, IsStarProjection (p i)) ∧ ∑ i, p i = 1 ∧
      (∑ i, ‖a i ξ - p i ξ‖ ^ 2 < 9 * ε) ∧
      ∀ b : H →L[ℂ] H, (∀ i, Commute b (a i)) → ∀ i, ∀ v : H, p i v = v → p i (b v) = b v := by
  -- the hypothesis `ε ∈ [0, 1]` of the paper is not needed for the proof
  have _ := hε
  set M := CommutingRepetition.VN.wstar (Set.range a)
  have hPOVM : IsPOVM M a :=
    ⟨fun i => CommutingRepetition.VN.subset_wstar (Set.mem_range_self i), ha.1, ha.2⟩
  have hsa : ∀ i, IsSelfAdjoint (a i) := fun i => (ha.1 i).isSelfAdjoint
  have hφ : 1 - ε < (vecState M ξ hξ (∑ i, a i * a i)).re := by
    rw [vecState_apply, re_vecFunctional_sum_mul_self ξ a hsa]
    exact h
  obtain ⟨p, hp, hbound⟩ := povm_orthogonalization_finDim_vn M (vecState M ξ hξ) a hPOVM ε hφ
  refine ⟨p, hp.2.1, hp.2.2, ?_, ?_⟩
  · rwa [vecState_apply, re_vecFunctional_sum_star_sub_mul_sub] at hbound
  · intro b hb i v hv
    have hbc : b ∈ StarSubalgebra.centralizer ℂ (Set.range a) := by
      rw [StarSubalgebra.mem_centralizer_iff ℂ]
      rintro _ ⟨i', rfl⟩
      exact ⟨(hb i').eq.symm, by rw [(hsa i').star_eq]; exact (hb i').eq.symm⟩
    have hcomm : b * p i = p i * b := CommutingRepetition.VN.mem_wstar_iff.mp (hp.1 i) b hbc
    calc p i (b v) = (p i * b) v := (mul_apply_eq_comp _ _ _).symm
      _ = (b * p i) v := by rw [hcomm]
      _ = b (p i v) := mul_apply_eq_comp _ _ _
      _ = b v := by rw [hv]

/-- **Theorem 1.4** (`thm:pvm_almost_commute`) in finite dimension: the instance of the
signed statement `pvm_almost_commute` with `[FiniteDimensional ℂ H]` added. Proof
(Section 5 of the paper): with `a_i = ∑_j q_j p_i q_j`,
`∑_{i,j} ‖p_i q_j − q_j p_i‖_φ² = ∑_i ‖p_i − a_i‖_φ² + (1 − φ(∑ a_i²))`; Theorem 1.2 in
`W*(a_i)` (whose elements commute with the `q_j`) gives a PVM `p'` with
`∑ ‖a_i − p'_i‖_φ² < 9 (ε − ∑ ‖p_i − a_i‖_φ²)`, and the triangle inequality together with
`(√D + √E)² ≤ 10 (D + E/9)` concludes. -/
theorem pvm_almost_commute_finDim (M : VonNeumannAlgebra H) (φ : NormalState M)
    {ι κ : Type*} [Fintype ι] [Fintype κ] (p : ι → H →L[ℂ] H) (q : κ → H →L[ℂ] H)
    (hp : IsPVM M p) (hq : IsPVM M q) (ε : ℝ)
    (h : ∑ i, ∑ j, φ.normSq (p i * q j - q j * p i) < ε) :
    ∃ p' : ι → H →L[ℂ] H, IsPVM M p' ∧ (∀ i j, Commute (p' i) (q j)) ∧
      ∑ i, φ.normSq (p i - p' i) < 10 * ε := by
  -- the compressed POVM `a_i = ∑_j q_j p_i q_j`
  obtain ⟨a, ha⟩ : ∃ a : ι → H →L[ℂ] H, a = compress p q := ⟨_, rfl⟩
  have haM : ∀ i, a i ∈ M := by rw [ha]; exact compress_mem hp hq
  have haPOVM : IsPOVM M a := by rw [ha]; exact isPOVM_compress hp hq
  have hastar : ∀ i, star (a i) = a i := by rw [ha]; exact compress_star hp hq
  have hacomm : ∀ i k, Commute (a i) (q k) := by rw [ha]; exact compress_comm hq
  have hkey := key_identity hp hq
  rw [← ha] at hkey
  -- `D = ∑ ‖p_i − a_i‖_φ²` and the identity of Section 5
  obtain ⟨D, hD⟩ : ∃ D : ℝ, D = ∑ i, φ.normSq (p i - a i) := ⟨_, rfl⟩
  have hDnn : 0 ≤ D := by
    rw [hD]
    exact Finset.sum_nonneg fun i _ => normSq_nonneg_of_mem φ (sub_mem (hp.1 i) (haM i))
  have hid : ∑ i, ∑ j, φ.normSq (p i * q j - q j * p i) = D + (1 - ∑ i, (φ (a i * a i)).re) := by
    have := congrArg (fun x => (φ.toLinearMap x).re) hkey
    simp only [map_sum, map_add, map_sub, φ.map_one', Complex.re_sum, Complex.add_re,
      Complex.sub_re, Complex.one_re] at this
    rw [hD]
    exact this
  have hS : 1 - (ε - D) < (φ (∑ i, a i * a i)).re := by
    rw [map_sum, Complex.re_sum]
    linarith [hid, h]
  -- Theorem 1.2 in the von Neumann algebra `N = W*(a_i)`, with `φ` restricted to `N`
  set N := CommutingRepetition.VN.wstar (Set.range a)
  have hNM : ∀ x ∈ N, x ∈ M := fun x hx =>
    CommutingRepetition.VN.wstar_le (Set.range_subset_iff.mpr haM) hx
  have haN : ∀ i, a i ∈ N := fun i => CommutingRepetition.VN.subset_wstar (Set.mem_range_self i)
  have haPOVM_N : IsPOVM N a := ⟨haN, haPOVM.2.1, haPOVM.2.2⟩
  obtain ⟨p', hp'N, hbound⟩ :=
    povm_orthogonalization_finDim_vn N (restrictState φ hNM) a haPOVM_N (ε - D) hS
  have hp'M : ∀ i, p' i ∈ M := fun i => hNM _ (hp'N.1 i)
  -- `E = ∑ ‖a_i − p'_i‖_φ² < 9 (ε − D)`
  obtain ⟨E, hE⟩ : ∃ E : ℝ, E = ∑ i, φ.normSq (a i - p' i) := ⟨_, rfl⟩
  have hEnn : 0 ≤ E := by
    rw [hE]
    exact Finset.sum_nonneg fun i _ => normSq_nonneg_of_mem φ (sub_mem (haM i) (hp'M i))
  have hE9 : E < 9 * (ε - D) := by
    rw [hE]
    refine lt_of_eq_of_lt ?_ hbound
    show ∑ i, (φ.toLinearMap (star (a i - p' i) * (a i - p' i))).re
      = (φ.toLinearMap (∑ i, star (a i - p' i) * (a i - p' i))).re
    rw [map_sum, Complex.re_sum]
  refine ⟨p', ⟨hp'M, hp'N.2.1, hp'N.2.2⟩, ?_, ?_⟩
  · -- `p'_i ∈ W*(a_i)` commutes with `q_j`, which commutes with every `a_i`
    intro i j
    have hqc : q j ∈ StarSubalgebra.centralizer ℂ (Set.range a) := by
      rw [StarSubalgebra.mem_centralizer_iff ℂ]
      rintro _ ⟨i', rfl⟩
      exact ⟨(hacomm i' j).eq, by rw [hastar]; exact (hacomm i' j).eq⟩
    exact (CommutingRepetition.VN.mem_wstar_iff.mp (hp'N.1 i) (q j) hqc).symm
  · -- the triangle inequality and `(√D + √E)² ≤ 10 (D + E/9) < 10 ε`
    have htri := sum_normSq_add_le φ (fun i => p i - a i) (fun i => a i - p' i)
      (fun i => sub_mem (hp.1 i) (haM i)) (fun i => sub_mem (haM i) (hp'M i))
    simp only [sub_add_sub_cancel] at htri
    rw [← hD, ← hE] at htri
    have hsq : (Real.sqrt D + Real.sqrt E) ^ 2 ≤ 10 * (D + E / 9) := by
      nlinarith [sq_nonneg (3 * Real.sqrt D - Real.sqrt E / 3), Real.sq_sqrt hDnn,
        Real.sq_sqrt hEnn]
    calc ∑ i, φ.normSq (p i - p' i) ≤ (Real.sqrt D + Real.sqrt E) ^ 2 := htri
      _ ≤ 10 * (D + E / 9) := hsq
      _ < 10 * ε := by linarith

end Orthogonalization
