/-
Copyright (c) 2026 MIPRE contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import MIPRE.Foundations.Introspection.FinalExtraction
import MIPRE.Foundations.Introspection.TypedPredicate
import MIPRE.Foundations.Introspection.TypeGraph
import MIPRE.Foundations.PerfectStrategy
import MIPRE.Foundations.GameDouble

/-! # The honest Introspect and Sample measurements

These are the concrete measurements from the completeness proof in
`introspection.tex`. Every answer label is retained. Their products vanish on
unrealizable pairs of question labels; source PCC is only used for labels
generated by a common seed.
-/

noncomputable section

namespace MIPRE.Introspection.Honest

open Finset Matrix Classical
open scoped Kronecker
set_option linter.unusedSectionVars false

variable {F ι A : Type*} [Field F] [Fintype F] [DecidableEq F]
  [Fintype ι] [DecidableEq ι] [Fintype A] [DecidableEq A] {ℓ : ℕ}

/-- The first bit selects Sample rather than Introspect; the second is the original role. -/
abbrev CoreType := Bool × Bool

def coreType {P : Type*} (t : CoreType) : QuestionType P ℓ :=
  .inr ((if t.1 then .sample else .introspect), t.2)

def displayed (L : Bool → CL.CLFun F ι ℓ) (t : CoreType) (z : ι → F) : ι → F :=
  if t.1 then z else (L t.2).eval z

def originalQuestion (L : Bool → CL.CLFun F ι ℓ) (t : CoreType) (y : ι → F) : ι → F :=
  if t.1 then (L t.2).eval y else y

@[simp] theorem originalQuestion_displayed (L : Bool → CL.CLFun F ι ℓ)
    (t : CoreType) (z : ι → F) : originalQuestion L t (displayed L t z) = (L t.2).eval z := by
  cases h : t.1 <;> simp [originalQuestion, displayed, h]

variable (L : Bool → CL.CLFun F ι ℓ) (D : (ι → F) → (ι → F) → A → A → Bool)

abbrev sourceGame := SampledGame.game (L false).eval (L true).eval D

theorem source_mu_pos (z : ι → F) :
    0 < (sourceGame L D).doubled.μ (false, (L false).eval z) (true, (L true).eval z) := by
  change 0 < SampledGame.dist (L false).eval (L true).eval ((L false).eval z) ((L true).eval z)
  rw [SampledGame.dist_eq_card, div_pos_iff_of_pos_right (by exact_mod_cast Fintype.card_pos)]
  simp only [Nat.cast_pos, Finset.card_pos, Finset.nonempty_def, Finset.mem_filter,
    Finset.mem_univ, true_and]
  exact ⟨z, rfl, rfl⟩

variable (R : SyncStrategy (sourceGame L D).doubled)

theorem source_isPVM (w : Bool) (y : ι → F) : IsPVM (R.P.M (w, y)) where
  isSelfAdjoint a := by rw [← Matrix.star_eq_conjTranspose]; exact R.P.selfAdjoint _ a
  idem a := R.P.projective _ a
  sum_eq_one := R.P.normalized _

theorem source_commute (hR : R.IsPCC) (w v : Bool) (z : ι → F) (a b : A) :
    Commute (R.P.M (w, (L w).eval z) a) (R.P.M (v, (L v).eval z) b) := by
  by_cases hw : w = v
  · subst v
    by_cases hab : a = b
    · subst b; exact Commute.refl _
    · show _ * _ = _ * _
      rw [R.orthogonal _ hab, R.orthogonal _ (Ne.symm hab)]
  · cases w <;> cases v
    · exact False.elim (hw rfl)
    · exact hR _ _ (source_mu_pos L D z) a b
    · exact (hR _ _ (source_mu_pos L D z) b a).symm
    · exact False.elim (hw rfl)

theorem source_reject_zero (hR : R.IsPCC) (hval : R.value = 1)
    (z : ι → F) (a b : A) (hD : D ((L false).eval z) ((L true).eval z) a b = false) :
    R.P.M (false, (L false).eval z) a * R.P.M (true, (L true).eval z) b = 0 := by
  have hc := source_commute L D R hR false true z a b
  apply R.eq_zero_of_trace_re_eq_zero
  · rw [star_mul, R.P.selfAdjoint, R.P.selfAdjoint]
    exact hc.eq.symm
  · rw [mul_assoc, ← mul_assoc (R.P.M (true, (L true).eval z) b), hc.eq.symm,
      mul_assoc (R.P.M (false, (L false).eval z) a), R.P.projective, ← mul_assoc,
      R.P.projective]
  · exact R.re_eq_zero_of_value_eq_one hval (source_mu_pos L D z) hD

/-- The actual honest register/auxiliary measurement for each of the four core types. -/
def coreOp (t : CoreType) (ya : (ι → F) × A) :
    Matrix ((ι → F) × Fin R.d) ((ι → F) × Fin R.d) ℂ :=
  conditionalReadout (displayed L t) (fun y => R.P.M (t.2, originalQuestion L t y)) ya

theorem coreOp_isPVM (t : CoreType) : IsPVM (coreOp L D R t) :=
  conditionalReadout_isPVM _ _ (fun _ => source_isPVM L D R _ _)

/-- Each seed block contains exactly the original two auxiliary operators.
All impossible claimed labels vanish before any commutation assumption is used. -/
theorem coreOp_mul_apply (t u : CoreType) (ya zb : (ι → F) × A)
    (s s' : ι → F) (i j : Fin R.d) :
    (coreOp L D R t ya * coreOp L D R u zb) (s, i) (s', j) =
      if s = s' ∧ displayed L t s = ya.1 ∧ displayed L u s = zb.1 then
        (R.P.M (t.2, (L t.2).eval s) ya.2 * R.P.M (u.2, (L u.2).eval s) zb.2) i j else 0 := by
  rw [coreOp, coreOp, conditionalReadout, conditionalReadout, ← Matrix.mul_kronecker_mul,
    readout, readout, Matrix.diagonal_mul_diagonal]
  by_cases hs : s = s'
  · subst s'
    by_cases ht : displayed L t s = ya.1 <;> by_cases hu : displayed L u s = zb.1
    · simp only [Matrix.kroneckerMap_apply, Matrix.diagonal_apply, ht, hu,
        if_pos, mul_one, one_mul, and_self]
      rw [← ht, ← hu, originalQuestion_displayed, originalQuestion_displayed]
    all_goals simp [Matrix.kroneckerMap_apply, ht, hu]
  · simp [Matrix.kroneckerMap_apply, hs]

/-- The honest core operators commute for every answer label, even labels not
realizable by a common seed. -/
theorem coreOp_commute (hR : R.IsPCC) (t u : CoreType) (ya zb : (ι → F) × A) :
    Commute (coreOp L D R t ya) (coreOp L D R u zb) := by
  show _ * _ = _ * _
  ext ⟨s, i⟩ ⟨s', j⟩
  rw [coreOp_mul_apply, coreOp_mul_apply]
  by_cases h : s = s' ∧ displayed L t s = ya.1 ∧ displayed L u s = zb.1
  · rw [if_pos h, if_pos ⟨h.1, h.2.2, h.2.1⟩]
    exact congrArg (fun M => M i j) (source_commute L D R hR t.2 u.2 s ya.2 zb.2).eq
  · rw [if_neg h, if_neg (by tauto)]

end MIPRE.Introspection.Honest
