/-
Copyright (c) 2026 the commuting-repetition contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE. Vendored from
https://github.com/vidick/commuting-repetition (commit cfa2f1bf, 2026-09-11) by scripts/vendor-repetition.py;
do not edit by hand. Upstream path: lean/CommutingRepetition/Game/Value.lean
-/
/-
# Correlations, the winning functional, and the commuting value ω^co

Encoding decision D3. Anchors: 02_preliminaries.tex (success probability and
the commuting value as a supremum); audit def `commuting_strategy`; the
sSup packaging pattern follows the ten-proofs artifact's `entangledValue`
(Apache-2.0; see lean/NOTICE).

Universe policy (recorded in the fidelity ledger): the `CommutingStrategy`
structure is universe-polymorphic, but `IsCommutingCorrelation` and
`omegaCO` quantify over universe-0 strategies only. The final contradiction
consumes and produces universe-0 strategies; restricting to the separable
subspace cyclically generated by ψ shows the value is unchanged (not
formalized — see FIDELITY.md / DIFFERENCES.md).
-/
import Mathlib
import MIPRE.Background.Repetition.CommutingRepetition.Game.Basic
import MIPRE.Background.Repetition.CommutingRepetition.Game.Strategy

-- Upstream builds with Lean's default `autoImplicit = true`; this repository turns it
-- off in `lakefile.toml`. Inserted by scripts/vendor-repetition.py.
set_option autoImplicit true

namespace CommutingRepetition

open scoped BigOperators

variable {X Y A B : Type}
variable [Fintype X] [Fintype Y] [Fintype A] [Fintype B]

/-- A correlation table on alphabets `X, Y, A, B`. -/
abbrev Correlation (X Y A B : Type*) := X → Y → A → B → ℝ

/-- Realizability by a commuting-operator strategy at universe 0, per the
universe policy in this file's header (fidelity review #1: the pinning
propagates into `TracialDensityHypothesis`, where it only weakens what is
assumed). -/
def IsCommutingCorrelation (p : Correlation X Y A B) : Prop :=
  ∃ S : CommutingStrategy.{0} X Y A B, S.correlation = p

namespace Game

/-- Expected payoff of a correlation in the game `G`:
`win_G(p) = ∑ μ(x,y) V(a,b|x,y) p(a,b|x,y)` — a linear functional of the
correlation table, as the tracial reduction (03_tracial_reduction.tex)
requires. -/
def win (G : Game X Y A B) (p : Correlation X Y A B) : ℝ :=
  ∑ x : X, ∑ y : Y, ∑ a : A, ∑ b : B,
    G.questionWeight x y * G.payoff x y a b * p x y a b

theorem win_nonneg (G : Game X Y A B) {p : Correlation X Y A B}
    (hp : ∀ x y a b, 0 ≤ p x y a b) : 0 ≤ G.win p := by
  refine Finset.sum_nonneg fun x _ => Finset.sum_nonneg fun y _ =>
    Finset.sum_nonneg fun a _ => Finset.sum_nonneg fun b _ => ?_
  exact mul_nonneg (mul_nonneg (G.weight_nonneg x y)
    (G.payoff_nonneg x y a b)) (hp x y a b)

/-- If a correlation is pointwise nonnegative with answer sums `≤ 1`, the
winning probability is at most one. -/
theorem win_le_one (G : Game X Y A B) {p : Correlation X Y A B}
    (hp : ∀ x y a b, 0 ≤ p x y a b)
    (hsum : ∀ x y, (∑ a : A, ∑ b : B, p x y a b) ≤ 1) :
    G.win p ≤ 1 := by
  have step : ∀ x y, (∑ a : A, ∑ b : B,
      G.questionWeight x y * G.payoff x y a b * p x y a b)
        ≤ G.questionWeight x y := by
    intro x y
    calc
      (∑ a : A, ∑ b : B,
          G.questionWeight x y * G.payoff x y a b * p x y a b)
          ≤ ∑ a : A, ∑ b : B, G.questionWeight x y * p x y a b := by
            refine Finset.sum_le_sum fun a _ => Finset.sum_le_sum fun b _ => ?_
            have step := mul_le_mul_of_nonneg_right
              (mul_le_mul_of_nonneg_left (G.payoff_le_one x y a b)
                (G.weight_nonneg x y)) (hp x y a b)
            simpa using step
      _ = G.questionWeight x y * (∑ a : A, ∑ b : B, p x y a b) := by
            simp [Finset.mul_sum]
      _ ≤ G.questionWeight x y * 1 := by
            exact mul_le_mul_of_nonneg_left (hsum x y) (G.weight_nonneg x y)
      _ = G.questionWeight x y := mul_one _
  calc
    G.win p ≤ ∑ x : X, ∑ y : Y, G.questionWeight x y := by
      refine Finset.sum_le_sum fun x _ => Finset.sum_le_sum fun y _ => ?_
      exact step x y
    _ = 1 := G.weight_normalized

/-- The commuting-operator value `ω^co(G)`: the supremum of winning
probabilities over commuting-operator strategies.
[02_preliminaries.tex, "The supremum of this expression is the commuting
value"; non-attainment is never assumed anywhere downstream.] -/
noncomputable def omegaCO (G : Game X Y A B) : ℝ :=
  sSup (Set.range fun S : CommutingStrategy.{0} X Y A B =>
    G.win S.correlation)

theorem winProbabilities_bddAbove (G : Game X Y A B) :
    BddAbove (Set.range fun S : CommutingStrategy.{0} X Y A B =>
      G.win S.correlation) := by
  refine ⟨1, ?_⟩
  rintro _ ⟨S, rfl⟩
  exact G.win_le_one (fun x y a b => S.correlation_nonneg x y a b)
    (fun x y => (S.correlation_sum x y).le)

theorem omegaCO_le_one (G : Game X Y A B) : G.omegaCO ≤ 1 := by
  unfold omegaCO
  by_cases h : (Set.range fun S : CommutingStrategy.{0} X Y A B =>
      G.win S.correlation).Nonempty
  · refine csSup_le h ?_
    rintro _ ⟨S, rfl⟩
    exact G.win_le_one (fun x y a b => S.correlation_nonneg x y a b)
      (fun x y => (S.correlation_sum x y).le)
  · rw [Set.not_nonempty_iff_eq_empty.mp h, Real.sSup_empty]
    exact zero_le_one

/-- `0 ≤ ω^co(G)`. The `Nonempty` guards mirror the paper's nonempty answer
sets (the statement would also hold vacuously via `sSup ∅ = 0`, but the
guards keep the hypothesis surface paper-faithful). -/
theorem omegaCO_nonneg [Nonempty A] [Nonempty B] (G : Game X Y A B) :
    0 ≤ G.omegaCO := by
  unfold omegaCO
  have hmem : G.win (CommutingStrategy.trivial (X := X) (Y := Y)).correlation ∈
      Set.range fun S : CommutingStrategy.{0} X Y A B =>
        G.win S.correlation := ⟨_, rfl⟩
  refine le_trans ?_ (le_csSup (G.winProbabilities_bddAbove) hmem)
  exact G.win_nonneg fun x y a b =>
    (CommutingStrategy.trivial (X := X) (Y := Y)).correlation_nonneg x y a b

/-- Any single realizable strategy's value lower-bounds `ω^co`. Producing one
legal strategy above a threshold contradicts `ω^co ≤ threshold` — the shape
used by the final contradiction (07_main_theorem.tex, node 1.5.4). -/
theorem le_omegaCO (G : Game X Y A B) (S : CommutingStrategy.{0} X Y A B) :
    G.win S.correlation ≤ G.omegaCO :=
  le_csSup (G.winProbabilities_bddAbove) ⟨S, rfl⟩

/-- The `n`-fold repeated value `ω^co(G^{⊗n})`. -/
noncomputable def repeatedOmegaCO (G : Game X Y A B) (n : ℕ) : ℝ :=
  (G.«repeat» n).omegaCO

end Game

end CommutingRepetition
