/-
Copyright (c) 2026 the commuting-repetition contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE. Vendored from
https://github.com/vidick/commuting-repetition (commit cfa2f1bf, 2026-09-11) by scripts/vendor-repetition.py;
do not edit by hand. Upstream path: lean/CommutingRepetition/VN/Generated.lean
-/
/-
# Von Neumann algebras generated by a set; strong limits (density stage E3.1)

Mathlib's `VonNeumannAlgebra H` is a `*`-subalgebra of `B(H)` equal to its
bicommutant.  Every von Neumann algebra appearing in the proof of Lin's
tracial density theorem is *given* as a bicommutant (the algebra generated by
Alice's effects, the crossed product, the fixed-point algebras of the modular
groups), so the bicommutant *density* theorem is never needed: what is needed
is the elementary calculus of this file — the algebra generated by a set, the
fact that a bicommutant is closed under strong limits, and closure under the
continuous and Borel functional calculi.
-/
import Mathlib
import MIPRE.Background.Repetition.CommutingRepetition.VN.JointSpectral

-- Upstream builds with Lean's default `autoImplicit = true`; this repository turns it
-- off in `lakefile.toml`. Inserted by scripts/vendor-repetition.py.
set_option autoImplicit true

namespace CommutingRepetition

namespace VN

open scoped InnerProductSpace
open Filter Topology

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-! ## The von Neumann algebra generated by a set -/

/-- The von Neumann algebra generated by `S`: the bicommutant of `S ∪ star S`. -/
noncomputable def wstar (S : Set (H →L[ℂ] H)) : VonNeumannAlgebra H where
  toStarSubalgebra :=
    StarSubalgebra.centralizer ℂ (StarSubalgebra.centralizer ℂ S : Set (H →L[ℂ] H))
  centralizer_centralizer' := by
    have h := StarSubalgebra.coe_centralizer_centralizer (R := ℂ) S
    change Set.centralizer (Set.centralizer
      ((StarSubalgebra.centralizer ℂ
        (StarSubalgebra.centralizer ℂ S : Set (H →L[ℂ] H)) : StarSubalgebra ℂ (H →L[ℂ] H)) :
          Set (H →L[ℂ] H))) =
      ((StarSubalgebra.centralizer ℂ
        (StarSubalgebra.centralizer ℂ S : Set (H →L[ℂ] H)) : StarSubalgebra ℂ (H →L[ℂ] H)) :
          Set (H →L[ℂ] H))
    rw [h, Set.centralizer_centralizer_centralizer]

theorem mem_wstar_iff {S : Set (H →L[ℂ] H)} {T : H →L[ℂ] H} :
    T ∈ wstar S ↔ ∀ y ∈ StarSubalgebra.centralizer ℂ S, y * T = T * y := by
  change T ∈ StarSubalgebra.centralizer ℂ (StarSubalgebra.centralizer ℂ S : Set (H →L[ℂ] H)) ↔ _
  rw [StarSubalgebra.mem_centralizer_iff]
  constructor
  · intro h y hy
    exact (h y hy).1
  · intro h y hy
    exact ⟨h y hy, h (star y) (star_mem hy)⟩

theorem subset_wstar {S : Set (H →L[ℂ] H)} {s : H →L[ℂ] H} (hs : s ∈ S) : s ∈ wstar S := by
  rw [mem_wstar_iff]
  intro y hy
  exact ((StarSubalgebra.mem_centralizer_iff (R := ℂ)).mp hy s hs).1.symm

/-- An element commuting with the commutant of `N` lies in `N` (the definition of a von
Neumann algebra). -/
theorem mem_of_commute_commutant (N : VonNeumannAlgebra H) {T : H →L[ℂ] H}
    (h : ∀ y ∈ N.commutant, y * T = T * y) : T ∈ N := by
  rw [← N.commutant_commutant, VonNeumannAlgebra.mem_commutant_iff]
  exact h

theorem commutant_mul_of_mem {N : VonNeumannAlgebra H} {T y : H →L[ℂ] H} (hT : T ∈ N)
    (hy : y ∈ N.commutant) : y * T = T * y :=
  (VonNeumannAlgebra.mem_commutant_iff.mp hy T hT).symm

/-- `wstar S` is the smallest von Neumann algebra containing `S`. -/
theorem wstar_le {S : Set (H →L[ℂ] H)} {N : VonNeumannAlgebra H} (h : S ⊆ N) {T : H →L[ℂ] H}
    (hT : T ∈ wstar S) : T ∈ N := by
  refine mem_of_commute_commutant N fun y hy => ?_
  refine mem_wstar_iff.mp hT y ?_
  rw [StarSubalgebra.mem_centralizer_iff]
  intro s hs
  exact ⟨(VonNeumannAlgebra.mem_commutant_iff.mp hy s (h hs)),
    (VonNeumannAlgebra.mem_commutant_iff.mp hy (star s) (star_mem (h hs)))⟩

/-! ## Closure under strong limits and functional calculi -/

/-- A von Neumann algebra is closed under pointwise (strong) limits of bounded or unbounded
nets: the commutation relations pass to the limit. -/
theorem mem_of_tendsto (N : VonNeumannAlgebra H) {ι : Type*} {l : Filter ι} [l.NeBot]
    {T : ι → H →L[ℂ] H} {L : H →L[ℂ] H} (hT : ∀ i, T i ∈ N)
    (h : ∀ ξ, Tendsto (fun i => T i ξ) l (𝓝 (L ξ))) : L ∈ N := by
  refine mem_of_commute_commutant N fun y hy => ?_
  ext ξ
  rw [mul_apply_eq_comp, mul_apply_eq_comp]
  have h1 : Tendsto (fun i => y (T i ξ)) l (𝓝 (y (L ξ))) := (y.continuous.tendsto _).comp (h ξ)
  have h2 : Tendsto (fun i => y (T i ξ)) l (𝓝 (L (y ξ))) := by
    refine (h (y ξ)).congr fun i => ?_
    rw [← mul_apply_eq_comp, ← commutant_mul_of_mem (hT i) hy,
      mul_apply_eq_comp]
  exact tendsto_nhds_unique h1 h2

theorem cfc_mem (N : VonNeumannAlgebra H) {T : H →L[ℂ] H} (hT : T ∈ N) (f : ℂ → ℂ) :
    cfc f T ∈ N := by
  refine mem_of_commute_commutant N fun y hy => ?_
  have h1 : Commute T y := (commutant_mul_of_mem hT hy).symm
  have h2 : Commute (star T) y := (commutant_mul_of_mem (star_mem hT) hy).symm
  exact (Commute.cfc h1 h2 f).symm

theorem cfc_real_mem (N : VonNeumannAlgebra H) {T : H →L[ℂ] H} (hT : T ∈ N) (f : ℝ → ℝ) :
    cfc f T ∈ N := by
  refine mem_of_commute_commutant N fun y hy => ?_
  have h1 : Commute T y := (commutant_mul_of_mem hT hy).symm
  exact (Commute.cfc_real h1 f).symm

theorem bfc_mem (N : VonNeumannAlgebra H) {E : H →L[ℂ] H} (hE : IsSelfAdjoint E) (hEN : E ∈ N)
    {g : ℝ → ℝ} (hg : BorelCalc.Bdd g) : BorelCalc.bfc E hE g ∈ N := by
  refine mem_of_commute_commutant N fun y hy => ?_
  have h1 : Commute E y := (commutant_mul_of_mem hEN hy).symm
  exact (BorelCalc.commute_bfc E hE h1 hg).symm

/-- Pointwise limits of sequences: the form used for monotone and Cesàro limits. -/
theorem mem_of_tendsto_seq (N : VonNeumannAlgebra H) {T : ℕ → H →L[ℂ] H} {L : H →L[ℂ] H}
    (hT : ∀ n, T n ∈ N) (h : ∀ ξ, Tendsto (fun n => T n ξ) atTop (𝓝 (L ξ))) : L ∈ N :=
  mem_of_tendsto N hT h

end VN

end CommutingRepetition
