/-
Copyright (c) 2026 Thomas Vidick. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Vidick
-/
module
public import MIPRE.Background.Repetition.Commuting
public import MIPRE.Background.Repetition.CommutingRepetition.Tracial.Reduction
public import MIPRE.Background.Repetition.CommutingRepetition.VN.ConcreteVN
public import MIPRE.Background.QLD.PaddedLIDT
public import MIPRE.Foundations.FinitePairExpand
public import MIPRE.Foundations.KrausDilation

@[expose] public section

/-!
# `ω_co` is approached by projective strategies in finite pairs

Phase 6 of `planning/mipco-track.md` (`reports/lidt-co-audit.md`, §3.4): below `ω_co(G)`, and above
`0`, lies the value of a projective strategy for `G` in a finite pair
(`MIPRE.CommutingFinitePairApprox`, `lem:co-value-finite-pair`). The analytic content is Lin's
tracial density, in the form proved by the vendored development:

1. **Strict tracial reduction.** `ω_co(G)` is the commuting-operator value of the vendored
   development (`MIPRE.Repetition.commutingOperatorValue_eq_omegaCO`), and below it lies the
   winning probability of a tracially embeddable strategy `T`
   (`CommutingRepetition.strict_tracial_reduction`): a tracial algebra in standard form
   `L²(𝒜, τ)`, a density `σ`, the first player's POVMs acting on the left and the second player's
   on the right, in the state `ι σ`.
2. **The standard-form pair.** On `L²(𝒜, τ)`, the commutant of the right action
   (`StdTracialAlgebra.vnAlg`) and its commutant are a finite pair: the trace vector `ι 1` is
   tracial on the first (`StdTracialAlgebra.traceState_mul_comm_vn`) and, through the conjugation
   `J`, on the second, and it separates both, being cyclic for the left and for the right
   actions. The left action lies in the first, the right action in the second, so `T` is a POVM
   strategy of this model, of value its winning probability (`BipartiteModel.value_toCommuting`,
   `TracialStrategy.toCommutingStrategy_correlation`).
3. **Projectivity.** Each player's POVMs dilate to projective measurements in the matrices over the
   player's algebra against one fixed basis vector (`MIPRE.exists_pvm_dilation`); in the ancilla
   extension at that basis vector they form a projective strategy of the same value
   (`BipartiteModel.povmValue_expand_basisVec`), and the extension is a finite pair
   (`BipartiteModel.IsFinitePair.expand`).

An empty alphabet makes `ω_co(G) = 0`, below every admissible threshold; otherwise the alphabets
are those of the vendored theorem, which assumes them nonempty.
-/

namespace MIPRE.Repetition

open CommutingRepetition (StdTracialAlgebra TracialStrategy)
open scoped InnerProductSpace

/-! ## The standard-form pair -/

section StdPair

variable (M : StdTracialAlgebra.{0})

/-- The commutant of `StdTracialAlgebra.vnAlg`: the von Neumann algebra `R(𝒜)''` generated by the
right action, in which the second player's operators lie. -/
noncomputable def rightVN : StarSubalgebra ℂ (M.H →L[ℂ] M.H) :=
  StarSubalgebra.centralizer ℂ (M.vnAlg : Set (M.H →L[ℂ] M.H))

instance : StarOrderedRing M.vnAlg := starOrderedRing_centralizer (Set.range M.Rop)

instance : StarOrderedRing (rightVN M) := starOrderedRing_centralizer _

variable {M} in
/-- `R(𝒜)''` is the set of operators commuting with `R(𝒜)'`, which is closed under adjoints. -/
theorem mem_rightVN_iff {y : M.H →L[ℂ] M.H} : y ∈ rightVN M ↔ ∀ g ∈ M.vnAlg, g * y = y * g := by
  rw [rightVN, StarSubalgebra.mem_centralizer_iff]
  exact ⟨fun h g hg => (h g hg).1, fun h g hg => ⟨h g hg, h _ (star_mem hg)⟩⟩

/-- The right action lies in `R(𝒜)''`. -/
theorem Rop_mem_rightVN (a : M.A) : M.Rop a ∈ rightVN M :=
  mem_rightVN_iff.2 fun _ hg => (M.mem_vnAlg_iff.1 hg a).symm

/-- The left action commutes with `R(𝒜)''`. -/
theorem L_mul_eq_of_mem_rightVN {y : M.H →L[ℂ] M.H} (hy : y ∈ rightVN M) (a : M.A) :
    M.L a * y = y * M.L a :=
  mem_rightVN_iff.1 hy _ (M.L_mem_vnAlg a)

theorem L_traceVector (a : M.A) : M.L a M.traceVector = M.ι a := by
  rw [StdTracialAlgebra.traceVector, M.L_apply, mul_one]

/-- The trace vector is a unit vector. -/
theorem norm_traceVector_sq : ‖M.traceVector‖ ^ 2 = 1 := by
  have h := inner_self_eq_norm_sq_to_K (𝕜 := ℂ) M.traceVector
  rw [StdTracialAlgebra.traceVector, M.ι_inner, star_one, one_mul, M.τ_one] at h
  show ‖M.ι 1‖ ^ 2 = 1
  rw [← Complex.ofReal_inj]
  push_cast
  exact h.symm

/-- **The trace vector separates `R(𝒜)'`**, being cyclic for the right action. -/
theorem eq_zero_of_mem_vnAlg {x : M.H →L[ℂ] M.H} (hx : x ∈ M.vnAlg)
    (h0 : x M.traceVector = 0) : x = 0 := by
  ext v
  refine M.ι_induction (p := fun v => x v = 0) (isClosed_eq x.continuous continuous_const)
    (fun a => ?_) v
  rw [← M.Rop_traceVector a, ← mul_apply_eq_comp, ← M.mem_vnAlg_iff.1 hx a,
    mul_apply_eq_comp, h0, map_zero]

/-- **The trace vector separates `R(𝒜)''`**, being cyclic for the left action. -/
theorem eq_zero_of_mem_rightVN {y : M.H →L[ℂ] M.H} (hy : y ∈ rightVN M)
    (h0 : y M.traceVector = 0) : y = 0 := by
  ext v
  refine M.ι_induction (p := fun v => y v = 0) (isClosed_eq y.continuous continuous_const)
    (fun a => ?_) v
  rw [← L_traceVector M a, ← mul_apply_eq_comp, ← L_mul_eq_of_mem_rightVN M hy a,
    mul_apply_eq_comp, h0, map_zero]

/-- Conjugation by `J` is multiplicative. -/
theorem conjJ_mul (G G' : M.H →L[ℂ] M.H) : M.conjJ (G * G') = M.conjJ G * M.conjJ G' := by
  ext v
  rw [mul_apply_eq_comp, M.conjJ_apply, M.conjJ_apply, M.conjJ_apply,
    mul_apply_eq_comp, M.J_J]

/-- The trace-vector state of `J G J` is the conjugate of that of `G`. -/
theorem traceState_conjJ_eq (G : M.H →L[ℂ] M.H) :
    M.traceState (M.conjJ G) = star (M.traceState G) := by
  have h := M.inner_J_J (G M.traceVector) M.traceVector
  rw [M.J_traceVector] at h
  unfold StdTracialAlgebra.traceState
  rw [M.conjJ_apply, M.J_traceVector, ← h, ← inner_conj_symm, starRingEnd_apply]

/-- **The trace-vector state is tracial on `R(𝒜)''`**: conjugation by `J` carries `R(𝒜)''` into
`R(𝒜)'`, where it is (`StdTracialAlgebra.traceState_mul_comm_vn`). -/
theorem traceState_mul_comm_rightVN {y y' : M.H →L[ℂ] M.H} (hy : y ∈ rightVN M)
    (hy' : y' ∈ rightVN M) : M.traceState (y * y') = M.traceState (y' * y) := by
  have hJ : ∀ {G}, G ∈ rightVN M → M.conjJ G ∈ M.vnAlg := fun hG =>
    M.conjJ_mem_vnAlg fun m => (L_mul_eq_of_mem_rightVN M hG m).symm
  rw [← star_star (M.traceState (y * y')), ← traceState_conjJ_eq, conjJ_mul,
    M.traceState_mul_comm_vn (hJ hy) (hJ hy'), ← conjJ_mul, traceState_conjJ_eq, star_star]

/-- **The standard-form model** of a tracial algebra in a state `ψ` of `L²(𝒜, τ)`: the operators
of `L²(𝒜, τ)` represented on it, the commutant `R(𝒜)'` of the right action as the first player's
algebra and its commutant `R(𝒜)''` as the second player's. -/
noncomputable def stdModel (ψ : M.H) :
    BipartiteModel.{0} (M.H →L[ℂ] M.H) M.vnAlg (rightVN M) where
  H := M.H
  ψ := ψ
  π := StarAlgHom.id ℂ _
  πA := M.vnAlg.subtype
  πB := (rightVN M).subtype
  commute a b := mem_rightVN_iff.1 b.2 a a.2

variable {M} in
theorem mem_opsA_stdModel {ψ : M.H} {T : M.H →L[ℂ] M.H} :
    T ∈ (stdModel M ψ).opsA ↔ T ∈ M.vnAlg :=
  ⟨by rintro ⟨a, rfl⟩; exact a.2, fun h => ⟨⟨T, h⟩, rfl⟩⟩

variable {M} in
theorem mem_opsB_stdModel {ψ : M.H} {T : M.H →L[ℂ] M.H} :
    T ∈ (stdModel M ψ).opsB ↔ T ∈ rightVN M :=
  ⟨by rintro ⟨b, rfl⟩; exact b.2, fun h => ⟨⟨T, h⟩, rfl⟩⟩

/-- **The standard-form model is a finite pair**, with the trace vector as the faithful tracial
state of both players' algebras. -/
theorem isFinitePair_stdModel (ψ : M.H) : (stdModel M ψ).IsFinitePair where
  injA _ _ h := Subtype.ext h
  injB _ _ h := Subtype.ext h
  commutantA T hT := mem_opsA_stdModel.2 <| M.mem_vnAlg_iff.2 fun a =>
    (hT ⟨M.Rop a, Rop_mem_rightVN M a⟩).eq.symm
  commutantB T hT := mem_opsB_stdModel.2 <| mem_rightVN_iff.2 fun g hg => (hT ⟨g, hg⟩).eq.symm
  traceA := ⟨{
    n := 1
    g := fun _ => M.traceVector
    norm_sq_sum := by rw [Fin.sum_univ_one]; exact norm_traceVector_sq M
    trace_mul_comm := fun x hx y hy => by
      simp only [Fin.sum_univ_one]
      exact M.traceState_mul_comm_vn (mem_opsA_stdModel.1 hx) (mem_opsA_stdModel.1 hy)
    separating := fun x hx h => eq_zero_of_mem_vnAlg M (mem_opsA_stdModel.1 hx) (h 0) }⟩
  traceB := ⟨{
    n := 1
    g := fun _ => M.traceVector
    norm_sq_sum := by rw [Fin.sum_univ_one]; exact norm_traceVector_sq M
    trace_mul_comm := fun x hx y hy => by
      simp only [Fin.sum_univ_one]
      exact traceState_mul_comm_rightVN M (mem_opsB_stdModel.1 hx) (mem_opsB_stdModel.1 hy)
    separating := fun x hx h => eq_zero_of_mem_rightVN M (mem_opsB_stdModel.1 hx) (h 0) }⟩

end StdPair

/-! ## A tracial strategy in its standard-form model -/

section Tracial

variable {X Y A B : Type} [Fintype X] [Fintype Y] [Fintype A] [Fintype B]
  (T : TracialStrategy.{0} X Y A B)

/-- The first player's measurement of a tracial strategy at a question: the left action of its
POVM, in `R(𝒜)'`. -/
noncomputable def measA (x : X) : POVMIn A T.M.vnAlg where
  mats a := ⟨⟨T.M.L (T.E x a), T.M.L_mem_vnAlg _⟩,
    selfAdjoint.mem_iff.mpr (Subtype.ext (T.M.L_isPositive (T.E_pos x a)).isSelfAdjoint.star_eq)⟩
  nonneg a := Subtype.coe_le_coe.mp (Subtype.coe_le_coe.mp
    (ContinuousLinearMap.nonneg_iff_isPositive.2 (T.M.L_isPositive (T.E_pos x a))))
  normalized := by
    apply Subtype.ext
    rw [AddSubmonoidClass.coe_finsetSum]
    apply Subtype.ext
    rw [AddSubmonoidClass.coe_finsetSum]
    exact T.toCommutingStrategy.E_sum x

/-- The second player's measurement of a tracial strategy at a question: the right action of its
POVM, in `R(𝒜)''`. -/
noncomputable def measB (y : Y) : POVMIn B (rightVN T.M) where
  mats b := ⟨⟨T.M.Rop (T.F y b), Rop_mem_rightVN T.M _⟩,
    selfAdjoint.mem_iff.mpr
      (Subtype.ext (T.M.Rop_isPositive (T.F_pos y b)).isSelfAdjoint.star_eq)⟩
  nonneg b := Subtype.coe_le_coe.mp (Subtype.coe_le_coe.mp
    (ContinuousLinearMap.nonneg_iff_isPositive.2 (T.M.Rop_isPositive (T.F_pos y b))))
  normalized := by
    apply Subtype.ext
    rw [AddSubmonoidClass.coe_finsetSum]
    apply Subtype.ext
    rw [AddSubmonoidClass.coe_finsetSum]
    exact T.toCommutingStrategy.F_sum y

/-- **A tracial strategy is a POVM strategy of its standard-form model**, in the state `ι σ`, of
value its winning probability. -/
theorem povmValue_stdModel (G : Game X Y A B) :
    (stdModel T.M (T.M.ι T.σ)).povmValue G (measA T) (measB T) = (toCR G).win T.correlation := by
  rw [← (stdModel T.M (T.M.ι T.σ)).value_toCommuting T.toCommutingStrategy.ψ_norm,
    ← win_toCRStrategy, ← T.toCommutingStrategy_correlation]
  rfl

end Tracial

/-- **`ω_co` is approached by projective strategies in finite pairs** (`lem:co-value-finite-pair`):
below `ω_co(G)`, and above `0`, lies the value of a projective strategy for `G` in a finite pair
on a Hilbert space of `Type`. -/
theorem commutingFinitePairApprox : CommutingFinitePairApprox := by
  intro X Y A B _ _ _ _ G t ht h
  classical
  -- the alphabets are nonempty, or `ω_co(G) = 0`
  obtain ⟨S⟩ : Nonempty (CommutingOperatorStrategy X Y A B) := by
    rcases isEmpty_or_nonempty (CommutingOperatorStrategy X Y A B) with hE | hne
    · rw [commutingOperatorValue, Real.iSup_of_isEmpty] at h
      exact absurd h (not_lt.2 ht)
    · exact hne
  have : Nonempty X := by
    by_contra hX
    rw [not_nonempty_iff] at hX
    simpa using G.μ_sum_one
  have : Nonempty Y := by
    by_contra hY
    rw [not_nonempty_iff] at hY
    simpa using G.μ_sum_one
  have : Nonempty A := S.nonempty_left (Classical.arbitrary X)
  have : Nonempty B := S.nonempty_right (Classical.arbitrary Y)
  let a₀ := Classical.arbitrary A
  let b₀ := Classical.arbitrary B
  -- strict tracial reduction
  rw [commutingOperatorValue_eq_omegaCO] at h
  obtain ⟨T, hT⟩ := CommutingRepetition.strict_tracial_reduction (toCR G) h
  -- projective dilations in the two players' algebras
  obtain ⟨KA, PA, hPA, hPA₀⟩ := exists_pvm_dilation (measA T) a₀
  obtain ⟨KB, PB, hPB, hPB₀⟩ := exists_pvm_dilation (measB T) b₀
  let N := (stdModel T.M (T.M.ι T.σ)).expand
    (basisVec (Sum.inl (a₀, 0) : DilationAncilla A KA) (Sum.inl (b₀, 0) : DilationAncilla B KB))
  refine ⟨_, _, _, inferInstance, inferInstance, inferInstance, inferInstance, inferInstance,
    inferInstance, inferInstance, inferInstance, inferInstance, inferInstance, inferInstance,
    inferInstance, inferInstance, inferInstance, inferInstance, inferInstance, inferInstance, N,
    (isFinitePair_stdModel _ _).expand _,
    ⟨fun x => (hPA x).toPOVMIn, fun y => (hPB y).toPOVMIn, hPA, hPB, ?_⟩, ?_⟩
  · rw [BipartiteModel.norm_expand_state, norm_basisVec, one_mul]
    exact T.toCommutingStrategy.ψ_norm
  · rw [BipartiteModel.ProjStrat.value, BipartiteModel.povmValue_expand_basisVec _ _ _ G
      (fun x => (hPA x).toPOVMIn) (fun y => (hPB y).toPOVMIn) (measA T) (measB T) hPA₀ hPB₀,
      povmValue_stdModel]
    exact hT

end MIPRE.Repetition

end
