/-
Copyright (c) 2026 Thomas Vidick. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Vidick
-/
import Mathlib.Algebra.Star.Module
import Mathlib.Analysis.Convex.Cone.Extension
import Mathlib.Analysis.InnerProductSpace.Adjoint
import Mathlib.Analysis.InnerProductSpace.Positive
import Mathlib.Tactic.NoncommRing
import MIPRE.Foundations.NCPoly.Basic

/-!
# The quadratic module of a set of relations, Archimedean separation, and the `ℓ¹` norm

Fix a set `R` of noncommutative polynomials in letters `G` (`MIPRE.NCPoly G`), the relations.
The Tsirelson route (`planning/tsirelson-campaign.md`, §3.1) works with one object, the
*quadratic module*
`M = qmod R := PointedCone.hull ℝ ({s⋆ g s : g ∈ {1} ∪ G} ∪ relSpan R ∪ Anti)`,
where `relSpan R` is the complex span of the `u ρ v` with `ρ ∈ R` (the two-sided ideal of the
relations) and `Anti` is the real subspace of anti-hermitian elements `z⋆ = -z`. The letters are
positive (`g = 1⋆ g 1 ∈ M`), and `M` is closed under `m ↦ a⋆ m a`
(`NCPoly.star_mul_mul_mem_qmod_of_mem`).

**Positivity.** If the letters are evaluated at positive operators `f g` on a complex Hilbert
space and the evaluation kills every relation, then every element of `M` has nonnegative
expectation in every vector: `0 ≤ Re ⟪ψ, eval f m ψ⟫` (`NCPoly.re_inner_eval_nonneg`). The
hermitian squares are positive, the ideal evaluates to `0`, and anti-hermitian operators have
purely imaginary expectations.

**Archimedean property.** If `1 - g² ∈ M` for every letter, then every polynomial is bounded
by a multiple of the unit: `∀ y, ∃ N, N • 1 + y ∈ M` (`NCPoly.archimedean_of_gen`). The proof
telescopes `1 - w⋆ w ∈ M` along a word (`NCPoly.one_sub_star_word_mem`), writes a monomial
`c w = α w + (α w)⋆ + (α w - (α w)⋆)` with `α = c/2`, and uses
`(1 + |α|²)·1 + α w + (α w)⋆ = (1 + α w)⋆ (1 + α w) + |α|² (1 - w⋆ w)`
(`NCPoly.herm_add_const_mem`); the anti-hermitian remainder lies in `Anti`. For a letter with
`1 - g ∈ M`, `1 - g² ∈ M` follows from `g - g² = g (1 - g) g + (1 - g) g (1 - g)`
(`NCPoly.one_sub_gen_sq_mem`).

**Separation.** In any real vector space, a pointed cone `M` for which `u` is an order unit
(`∀ y, ∃ N, N • u + y ∈ M`) and which misses `-u` carries a nonnegative linear functional with
`L u = 1` (`MIPRE.exists_nonneg_functional_of_archimedean`, from Mathlib's `riesz_extension`). If
moreover `u ∈ M` and `h ∉ M`, the functional can be chosen with `L h ≤ 0`
(`MIPRE.exists_separating_functional_of_archimedean`), by applying the first statement to
`M ⊔ hull {-h}`. This is the separation step of the Positivstellensatz (§3.4). The two
statements hold in any real vector space, and live in the namespace `MIPRE` rather than
`MIPRE.PointedCone`, which would shadow Mathlib's `PointedCone` inside `namespace MIPRE`.

**The `ℓ¹` norm.** The exact certificates of §3.5 round a real certificate coefficientwise, and
measure the error in the taxicab `ℓ¹` norm `‖z‖₁ = Σ_w (|Re z_w| + |Im z_w|)` (`NCPoly.l1`). It
is subadditive, submultiplicative, invariant under negation and the star, and bounded on complex
multiples by the taxicab norm of the scalar, so no topology on `NCPoly G` is needed.

## Main declarations

* `NCPoly.relSpan R`, `NCPoly.sosGens`, `NCPoly.qmod R`, and the membership lemmas;
* `NCPoly.mul_mem_relSpan`, `NCPoly.star_mul_mul_mem_qmod_of_mem`;
* `NCPoly.eval_eq_zero_of_mem_relSpan`, `NCPoly.re_inner_eq_zero_of_star_eq_neg`,
  `NCPoly.re_inner_eval_nonneg`;
* `NCPoly.one_sub_gen_sq_mem`, `NCPoly.one_sub_star_word_mem`, `NCPoly.herm_add_const_mem`,
  `NCPoly.archimedean_of_gen`;
* `NCPoly.l1`, with `NCPoly.l1_nonneg`, `NCPoly.l1_zero`, `NCPoly.l1_single`,
  `NCPoly.l1_add_le`, `NCPoly.l1_neg`, `NCPoly.l1_sub_le`, `NCPoly.l1_sub_comm`,
  `NCPoly.l1_smul_le`, `NCPoly.l1_sum_le`, `NCPoly.l1_list_sum_le`, `NCPoly.l1_star`,
  `NCPoly.l1_mul_le`, `NCPoly.abs_re_add_abs_im_coeff_le_l1`;
* `MIPRE.exists_nonneg_functional_of_archimedean`,
  `MIPRE.exists_separating_functional_of_archimedean`.
-/

noncomputable section

open ComplexConjugate

namespace MIPRE

namespace NCPoly

variable {G : Type*}

/-! ## The relation span and the quadratic module -/

section Cone

variable (R : Set (NCPoly G))

/-- The two-sided ideal generated by the relations `R`: the complex span of the products
`u * ρ * v` with `ρ ∈ R`. -/
def relSpan : Submodule ℂ (NCPoly G) :=
  Submodule.span ℂ {z | ∃ u ρ v, ρ ∈ R ∧ z = u * ρ * v}

variable (G) in
/-- The hermitian squares `s⋆ g s`, with `g` either `1` (encoded as `none`) or a letter. -/
def sosGens : Set (NCPoly G) :=
  {z | ∃ s : NCPoly G, ∃ g : Option G, z = star s * g.elim 1 gen * s}

/-- The quadratic module `M` of the relations `R`: the real pointed cone generated by the
hermitian squares `s⋆ s` and `s⋆ g s`, the relation ideal `relSpan R`, and the anti-hermitian
elements. -/
def qmod : PointedCone ℝ (NCPoly G) :=
  PointedCone.hull ℝ (sosGens G ∪ (relSpan R : Set (NCPoly G)) ∪
    (skewAdjoint.submodule ℝ (NCPoly G) : Set (NCPoly G)))

variable {R}

/-- Every relation lies in the relation ideal. -/
theorem mem_relSpan_of_mem {ρ : NCPoly G} (h : ρ ∈ R) : ρ ∈ relSpan R :=
  Submodule.subset_span ⟨1, ρ, 1, h, by simp⟩

/-- The relation span is a two-sided ideal. -/
theorem mul_mem_relSpan {z : NCPoly G} (hz : z ∈ relSpan R) (a b : NCPoly G) :
    a * z * b ∈ relSpan R := by
  induction hz using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨u, ρ, v, hρ, rfl⟩ := hx
    exact Submodule.subset_span ⟨a * u, ρ, v * b, hρ, by noncomm_ring⟩
  | zero => simp
  | add x y _ _ hx hy => rw [mul_add, add_mul]; exact Submodule.add_mem _ hx hy
  | smul c x _ hx => rw [mul_smul_comm, smul_mul_assoc]; exact Submodule.smul_mem _ c hx

/-- The unit lies in the quadratic module. -/
theorem one_mem_qmod : (1 : NCPoly G) ∈ qmod R :=
  PointedCone.subset_hull (Or.inl (Or.inl ⟨1, none, by simp⟩))

/-- The hermitian square `s⋆ g s` of a letter lies in the quadratic module. -/
theorem star_mul_mul_mem_qmod (s : NCPoly G) (g : G) : star s * gen g * s ∈ qmod R :=
  PointedCone.subset_hull (Or.inl (Or.inl ⟨s, some g, rfl⟩))

/-- The hermitian square `s⋆ s` lies in the quadratic module. -/
theorem star_mul_self_mem_qmod (s : NCPoly G) : star s * s ∈ qmod R :=
  PointedCone.subset_hull (Or.inl (Or.inl ⟨s, none, by simp⟩))

/-- Every letter lies in the quadratic module. -/
theorem gen_mem_qmod (g : G) : gen g ∈ qmod R := by
  simpa using star_mul_mul_mem_qmod (R := R) 1 g

/-- The relation ideal is contained in the quadratic module. -/
theorem mem_qmod_of_mem_relSpan {z : NCPoly G} (hz : z ∈ relSpan R) : z ∈ qmod R :=
  PointedCone.subset_hull (Or.inl (Or.inr hz))

/-- Every anti-hermitian element lies in the quadratic module. -/
theorem mem_qmod_of_star_eq_neg {z : NCPoly G} (hz : star z = -z) : z ∈ qmod R :=
  PointedCone.subset_hull (Or.inr (skewAdjoint.mem_iff.mpr hz))

/-- The quadratic module is closed under `m ↦ a⋆ m a`. -/
theorem star_mul_mul_mem_qmod_of_mem {m : NCPoly G} (hm : m ∈ qmod R) (a : NCPoly G) :
    star a * m * a ∈ qmod R := by
  induction hm using Submodule.span_induction with
  | mem x hx =>
    rcases hx with (⟨s, g, rfl⟩ | hx) | hx
    · refine PointedCone.subset_hull (Or.inl (Or.inl ⟨s * a, g, ?_⟩))
      rw [star_mul]; noncomm_ring
    · exact mem_qmod_of_mem_relSpan (mul_mem_relSpan hx _ _)
    · refine mem_qmod_of_star_eq_neg ?_
      have hx' : star x = -x := skewAdjoint.mem_iff.mp hx
      rw [star_mul, star_mul, star_star, hx', mul_assoc]; noncomm_ring
  | zero => simp
  | add x y _ _ hx hy => rw [mul_add, add_mul]; exact Submodule.add_mem _ hx hy
  | smul c x _ hx =>
    have hc : ∀ z : NCPoly G, c • z = (c : ℝ) • z := fun _ => rfl
    rw [hc, mul_smul_comm, smul_mul_assoc, ← hc]; exact Submodule.smul_mem _ c hx

end Cone

/-! ## Positivity under Hilbert-space evaluation -/

section Hilbert

open scoped InnerProductSpace

variable {R : Set (NCPoly G)}
variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

omit [CompleteSpace H] in
/-- An evaluation that kills the relations kills the relation ideal. -/
theorem eval_eq_zero_of_mem_relSpan (f : G → H →L[ℂ] H) (hR : ∀ ρ ∈ R, eval f ρ = 0)
    {z : NCPoly G} (hz : z ∈ relSpan R) : eval f z = 0 := by
  induction hz using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨u, ρ, v, hρ, rfl⟩ := hx
    simp [hR ρ hρ]
  | zero => simp
  | add x y _ _ hx hy => simp [hx, hy]
  | smul c x _ hx => simp [hx]

/-- An anti-self-adjoint operator has purely imaginary expectations. -/
theorem re_inner_eq_zero_of_star_eq_neg (T : H →L[ℂ] H) (hT : star T = -T) (ψ : H) :
    (⟪ψ, T ψ⟫_ℂ).re = 0 := by
  have h1 : ⟪ψ, T ψ⟫_ℂ = -⟪T ψ, ψ⟫_ℂ := by
    rw [← ContinuousLinearMap.adjoint_inner_left, ← ContinuousLinearMap.star_eq_adjoint, hT]
    simp [inner_neg_left]
  have h2 : (⟪T ψ, ψ⟫_ℂ).re = (⟪ψ, T ψ⟫_ℂ).re := by rw [← inner_conj_symm, Complex.conj_re]
  have h3 := congrArg Complex.re h1
  rw [Complex.neg_re, h2] at h3
  linarith

/-- **Positivity of the quadratic module.** Under an evaluation of the letters at positive
operators that kills the relations, every element of `qmod R` has nonnegative expectation in
every vector. -/
theorem re_inner_eval_nonneg (f : G → H →L[ℂ] H) (hf : ∀ g, (f g).IsPositive)
    (hR : ∀ ρ ∈ R, eval f ρ = 0) (ψ : H) {m : NCPoly G} (hm : m ∈ qmod R) :
    0 ≤ (⟪ψ, eval f m ψ⟫_ℂ).re := by
  have hsa : ∀ g, IsSelfAdjoint (f g) := fun g => (hf g).isSelfAdjoint
  induction hm using Submodule.span_induction with
  | mem x hx =>
    rcases hx with (⟨s, g, rfl⟩ | hx) | hx
    · rw [map_mul, map_mul, eval_star f hsa, ContinuousLinearMap.star_eq_adjoint]
      simp only [mul_apply_eq_comp, ContinuousLinearMap.adjoint_inner_right]
      cases g with
      | none =>
        simpa [RCLike.re_to_complex] using inner_self_nonneg (𝕜 := ℂ) (x := eval f s ψ)
      | some g =>
        simpa only [Option.elim_some, eval_gen, RCLike.re_to_complex] using
          (hf g).re_inner_nonneg_right _
    · simp [eval_eq_zero_of_mem_relSpan f hR hx]
    · have hx' : star x = -x := skewAdjoint.mem_iff.mp hx
      have hT : star (eval f x) = -eval f x := by rw [← eval_star f hsa, hx', map_neg]
      exact (re_inner_eq_zero_of_star_eq_neg _ hT ψ).ge
  | zero => simp
  | add x y _ _ hx hy =>
    rw [map_add, add_apply, inner_add_right, Complex.add_re]
    exact add_nonneg hx hy
  | smul c x _ hx =>
    have hc : c • x = ((c : ℝ) : ℂ) • x := rfl
    rw [hc, map_smul, _root_.smul_apply, inner_smul_right, Complex.re_ofReal_mul]
    exact mul_nonneg c.2 hx

end Hilbert

/-! ## The Archimedean property -/

section Archimedean

variable {R : Set (NCPoly G)}

/-- If `1 - g ∈ M` for a letter `g`, then `1 - g² ∈ M`: add
`g - g² = g⋆ (1 - g) g + (1 - g)⋆ g (1 - g)` to `1 - g`. -/
theorem one_sub_gen_sq_mem {g : G} (hg : 1 - gen g ∈ qmod R) :
    1 - gen g * gen g ∈ qmod R := by
  have h1 : star (gen g) * (1 - gen g) * gen g ∈ qmod R := star_mul_mul_mem_qmod_of_mem hg _
  have h2 : star (1 - gen g) * gen g * (1 - gen g) ∈ qmod R := star_mul_mul_mem_qmod _ g
  have := Submodule.add_mem _ hg (Submodule.add_mem _ h1 h2)
  convert this using 1
  simp only [star_sub, star_one, star_gen]
  noncomm_ring

/-- If `1 - g² ∈ M` for every letter, then `1 - w⋆ w ∈ M` for every word `w`, by telescoping:
`1 - (g w)⋆ (g w) = (1 - w⋆ w) + w⋆ (1 - g²) w`. -/
theorem one_sub_star_word_mem (hgen : ∀ g, 1 - gen g * gen g ∈ qmod R) (w : FreeMonoid G) :
    1 - star (single w 1 : NCPoly G) * single w 1 ∈ qmod R := by
  induction w using FreeMonoid.inductionOn' with
  | one => simp [← one_def]
  | of_mul g w ih =>
    have := Submodule.add_mem _ ih (star_mul_mul_mem_qmod_of_mem (hgen g) (single w 1))
    convert this using 1
    rw [single_of_mul, star_mul, star_gen]
    noncomm_ring

/-- If `1 - s⋆ s ∈ M`, then `(1 + |α|²)·1 + (α s + (α s)⋆) ∈ M` for every `α : ℂ`: it is
`(1 + α s)⋆ (1 + α s) + |α|² (1 - s⋆ s)`. -/
theorem herm_add_const_mem {s : NCPoly G} (hs : 1 - star s * s ∈ qmod R) (α : ℂ) :
    (1 + Complex.normSq α) • (1 : NCPoly G) + (α • s + star (α • s)) ∈ qmod R := by
  have key : star (α • s) * (α • s) = (Complex.normSq α) • (star s * s) := by
    rw [star_smul, smul_mul_smul_comm]
    change _ = ((Complex.normSq α : ℝ) : ℂ) • (star s * s)
    rw [Complex.normSq_eq_conj_mul_self, Complex.star_def]
  have := Submodule.add_mem _ (star_mul_self_mem_qmod (R := R) (1 + α • s))
    (PointedCone.smul_mem _ (Complex.normSq_nonneg α) hs)
  convert this using 1
  rw [star_add, star_one, add_mul, one_mul, mul_add, mul_one, key, smul_sub, add_smul, one_smul]
  abel

/-- **The Archimedean property.** If `1 - g² ∈ M` for every letter `g`, then every polynomial
is bounded by a multiple of the unit: `N • 1 + y ∈ M` for some real `N`. -/
theorem archimedean_of_gen (hgen : ∀ g, 1 - gen g * gen g ∈ qmod R) (y : NCPoly G) :
    ∃ N : ℝ, N • (1 : NCPoly G) + y ∈ qmod R := by
  induction y using induction_linear with
  | zero => exact ⟨0, by simp⟩
  | add x y hx hy =>
    obtain ⟨N₁, h₁⟩ := hx
    obtain ⟨N₂, h₂⟩ := hy
    refine ⟨N₁ + N₂, ?_⟩
    convert Submodule.add_mem _ h₁ h₂ using 1
    rw [add_smul]; abel
  | single w c =>
    set W : NCPoly G := single w 1
    set α : ℂ := c / 2
    refine ⟨1 + Complex.normSq α, ?_⟩
    have hskew : α • W - star (α • W) ∈ qmod R := by
      apply mem_qmod_of_star_eq_neg
      rw [star_sub, star_star, neg_sub]
    have := Submodule.add_mem _ (herm_add_const_mem (one_sub_star_word_mem hgen w) α) hskew
    convert this using 1
    have hc : single w c = (2 * α) • W := by
      rw [smul_single, mul_one]; congr 1; simp [α]; ring
    rw [hc, mul_smul, two_smul]
    abel

end Archimedean

/-! ## The taxicab `ℓ¹` norm -/

section L1

/-- The taxicab norm of a complex number is subadditive. -/
private theorem taxicab_add_le (a b : ℂ) :
    |(a + b).re| + |(a + b).im| ≤ (|a.re| + |a.im|) + (|b.re| + |b.im|) := by
  rw [Complex.add_re, Complex.add_im]
  linarith [abs_add_le a.re b.re, abs_add_le a.im b.im]

/-- The taxicab norm of a complex number is submultiplicative. -/
private theorem taxicab_mul_le (a b : ℂ) :
    |(a * b).re| + |(a * b).im| ≤ (|a.re| + |a.im|) * (|b.re| + |b.im|) := by
  rw [Complex.mul_re, Complex.mul_im]
  have h1 := abs_sub (a.re * b.re) (a.im * b.im)
  have h2 := abs_add_le (a.re * b.im) (a.im * b.re)
  simp only [abs_mul] at h1 h2
  nlinarith [abs_nonneg a.re, abs_nonneg a.im, abs_nonneg b.re, abs_nonneg b.im]

/-- The **taxicab `ℓ¹` norm** of a polynomial: the sum over words of `|Re c_w| + |Im c_w|`. It
is the norm in which the exact certificates of the Tsirelson route are rounded
(`planning/tsirelson-campaign.md`, §3.5). -/
def l1 (z : NCPoly G) : ℝ :=
  ∑ w ∈ z.coeff.support, (|(z.coeff w).re| + |(z.coeff w).im|)

/-- The `ℓ¹` norm, as a sum over any finite set of words containing the support. -/
theorem l1_eq_sum_of_subset (z : NCPoly G) {s : Finset (FreeMonoid G)}
    (hs : z.coeff.support ⊆ s) : l1 z = ∑ w ∈ s, (|(z.coeff w).re| + |(z.coeff w).im|) :=
  Finset.sum_subset hs fun w _ hw => by simp [Finsupp.notMem_support_iff.mp hw]

/-- The `ℓ¹` norm is nonnegative. -/
theorem l1_nonneg (z : NCPoly G) : 0 ≤ l1 z :=
  Finset.sum_nonneg fun _ _ => add_nonneg (abs_nonneg _) (abs_nonneg _)

/-- The `ℓ¹` norm of `0`. -/
@[simp] theorem l1_zero : l1 (0 : NCPoly G) = 0 := by
  simp [l1]

/-- Each coefficient is bounded by the `ℓ¹` norm, in taxicab norm. -/
theorem abs_re_add_abs_im_coeff_le_l1 (z : NCPoly G) (w : FreeMonoid G) :
    |(z.coeff w).re| + |(z.coeff w).im| ≤ l1 z := by
  by_cases hw : w ∈ z.coeff.support
  · exact Finset.single_le_sum (f := fun w => |(z.coeff w).re| + |(z.coeff w).im|)
      (fun _ _ => add_nonneg (abs_nonneg _) (abs_nonneg _)) hw
  · rw [Finsupp.notMem_support_iff.mp hw]
    simpa using l1_nonneg z

/-- The `ℓ¹` norm of a monomial is the taxicab norm of its coefficient. -/
@[simp] theorem l1_single (w : FreeMonoid G) (c : ℂ) : l1 (single w c) = |c.re| + |c.im| := by
  rw [l1_eq_sum_of_subset _ (s := {w}) (by simpa using Finsupp.support_single_subset),
    Finset.sum_singleton, coeff_single, Finsupp.single_eq_same]

/-- The `ℓ¹` norm is subadditive. -/
theorem l1_add_le (x y : NCPoly G) : l1 (x + y) ≤ l1 x + l1 y := by
  classical
  set s := x.coeff.support ∪ y.coeff.support
  rw [l1_eq_sum_of_subset (x + y) (s := s) (by simpa using Finsupp.support_add),
    l1_eq_sum_of_subset x (s := s) Finset.subset_union_left,
    l1_eq_sum_of_subset y (s := s) Finset.subset_union_right, ← Finset.sum_add_distrib]
  exact Finset.sum_le_sum fun w _ => by simpa using taxicab_add_le (x.coeff w) (y.coeff w)

/-- The `ℓ¹` norm is invariant under negation. -/
@[simp] theorem l1_neg (z : NCPoly G) : l1 (-z) = l1 z := by
  simp [l1, Finsupp.support_neg]

/-- The `ℓ¹` norm of a difference is at most the sum of the norms. -/
theorem l1_sub_le (x y : NCPoly G) : l1 (x - y) ≤ l1 x + l1 y := by
  simpa [sub_eq_add_neg] using l1_add_le x (-y)

/-- The `ℓ¹` distance is symmetric. -/
theorem l1_sub_comm (x y : NCPoly G) : l1 (x - y) = l1 (y - x) := by
  rw [← l1_neg, neg_sub]

/-- The `ℓ¹` norm of a complex multiple is at most the taxicab norm of the scalar times the
`ℓ¹` norm. -/
theorem l1_smul_le (c : ℂ) (z : NCPoly G) : l1 (c • z) ≤ (|c.re| + |c.im|) * l1 z := by
  rw [l1_eq_sum_of_subset (c • z) (s := z.coeff.support) (by simpa using Finsupp.support_smul),
    l1, Finset.mul_sum]
  exact Finset.sum_le_sum fun w _ => by simpa using taxicab_mul_le c (z.coeff w)

/-- The `ℓ¹` norm of a finite sum is at most the sum of the norms. -/
theorem l1_sum_le {ι : Type*} (s : Finset ι) (f : ι → NCPoly G) :
    l1 (∑ i ∈ s, f i) ≤ ∑ i ∈ s, l1 (f i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | insert i s hi ih =>
    rw [Finset.sum_insert hi, Finset.sum_insert hi]
    exact (l1_add_le _ _).trans (add_le_add le_rfl ih)

/-- The `ℓ¹` norm of the sum of a list is at most the sum of the norms. -/
theorem l1_list_sum_le (l : List (NCPoly G)) : l1 l.sum ≤ (l.map l1).sum := by
  induction l with
  | nil => simp
  | cons z l ih =>
    rw [List.sum_cons, List.map_cons, List.sum_cons]
    exact (l1_add_le _ _).trans (add_le_add le_rfl ih)

/-- The `ℓ¹` norm is invariant under the star: it conjugates the coefficients and permutes the
words. -/
@[simp] theorem l1_star (z : NCPoly G) : l1 (star z) = l1 z := by
  refine Finset.sum_nbij' FreeMonoid.reverse FreeMonoid.reverse (fun w hw => ?_)
    (fun w hw => ?_) (fun w _ => FreeMonoid.reverse_reverse) (fun w _ => FreeMonoid.reverse_reverse)
    (fun w _ => ?_)
  · simpa using hw
  · simpa using hw
  · simp

/-- The `ℓ¹` norm is submultiplicative. -/
theorem l1_mul_le (x y : NCPoly G) : l1 (x * y) ≤ l1 x * l1 y := by
  conv_lhs => rw [← sum_support_single x, ← sum_support_single y, Finset.sum_mul_sum]
  refine (l1_sum_le _ _).trans ?_
  rw [l1, l1, Finset.sum_mul_sum]
  refine Finset.sum_le_sum fun w _ => (l1_sum_le _ _).trans (Finset.sum_le_sum fun v _ => ?_)
  rw [single_mul_single, l1_single]
  exact taxicab_mul_le _ _

end L1

end NCPoly

/-! ## Separation by a nonnegative functional -/

section Separation

variable {E : Type*} [AddCommGroup E] [Module ℝ E]

/-- **Riesz extension for an order unit.** If `u` is an order unit of a pointed cone `M` in a
real vector space (`∀ y, ∃ N, N • u + y ∈ M`) and `-u ∉ M`, then some linear functional is
nonnegative on `M` and takes the value `1` at `u`. -/
theorem exists_nonneg_functional_of_archimedean (M : PointedCone ℝ E) (u : E)
    (harch : ∀ y, ∃ N : ℝ, N • u + y ∈ M) (hneg : -u ∉ M) :
    ∃ L : E →ₗ[ℝ] ℝ, L u = 1 ∧ ∀ x ∈ M, 0 ≤ L x := by
  have hu : u ≠ 0 := by rintro rfl; exact hneg (by simp)
  let f : E →ₗ.[ℝ] ℝ := LinearPMap.mkSpanSingleton u (1 : ℝ) hu
  have nonneg : ∀ x : f.domain, (x : E) ∈ M → 0 ≤ f x := by
    rintro ⟨x, hx⟩ hxM
    obtain ⟨c, rfl⟩ := Submodule.mem_span_singleton.mp hx
    have hfx : f ⟨c • u, hx⟩ = c :=
      (LinearPMap.mkSpanSingleton'_apply (σ := RingHom.id ℝ) u (1 : ℝ) _ c hx).trans
        (by simp)
    rw [hfx]
    by_contra hc
    push Not at hc
    apply hneg
    have := M.smul_mem (inv_nonneg.mpr (by linarith : (0 : ℝ) ≤ -c)) hxM
    rw [smul_smul] at this
    have hc' : (-c)⁻¹ * c = -1 := by rw [inv_neg, neg_mul, inv_mul_cancel₀ hc.ne]
    rwa [hc', neg_one_smul] at this
  have dense : ∀ y, ∃ x : f.domain, (x : E) + y ∈ M := by
    intro y
    obtain ⟨N, hN⟩ := harch y
    exact ⟨⟨N • u, Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self u)⟩, hN⟩
  obtain ⟨L, hLf, hLM⟩ := riesz_extension M f nonneg dense
  refine ⟨L, ?_, hLM⟩
  rw [hLf ⟨u, Submodule.mem_span_singleton_self u⟩]
  exact LinearPMap.mkSpanSingleton'_apply_self ..

/-- **Archimedean separation.** If `u ∈ M` is an order unit of a pointed cone `M` in a real
vector space and `h ∉ M`, then some linear functional is nonnegative on `M`, takes the value `1`
at `u`, and is `≤ 0` at `h`. -/
theorem exists_separating_functional_of_archimedean (M : PointedCone ℝ E) (u : E)
    (harch : ∀ y, ∃ N : ℝ, N • u + y ∈ M) (hu : u ∈ M) (h : E) (hh : h ∉ M) :
    ∃ L : E →ₗ[ℝ] ℝ, L u = 1 ∧ (∀ x ∈ M, 0 ≤ L x) ∧ L h ≤ 0 := by
  set M' : PointedCone ℝ E := M ⊔ PointedCone.hull ℝ {-h} with hM'
  have hMM' : M ≤ M' := le_sup_left
  have hnegh : -h ∈ M' := Submodule.mem_sup_right (Submodule.subset_span rfl)
  have hneg : -u ∉ M' := by
    intro hmem
    obtain ⟨m, hm, k, hk, hmk⟩ := Submodule.mem_sup.mp hmem
    obtain ⟨t, rfl⟩ := Submodule.mem_span_singleton.mp hk
    obtain ⟨t, ht⟩ := t
    change m + t • -h = -u at hmk
    apply hh
    rcases ht.eq_or_lt with rfl | htpos
    · rw [zero_smul, add_zero] at hmk
      subst hmk
      obtain ⟨N, hN⟩ := harch h
      rcases le_total 0 N with hN0 | hN0
      · have := M.add_mem hN (M.smul_mem hN0 hm)
        convert this using 1
        rw [smul_neg]; abel
      · have := M.add_mem hN (M.smul_mem (neg_nonneg.mpr hN0) hu)
        convert this using 1
        rw [neg_smul]; abel
    · have h1 : t • h = m + u := by
        rw [smul_neg, ← sub_eq_add_neg, sub_eq_iff_eq_add] at hmk
        rw [hmk]; abel
      have := M.smul_mem (inv_nonneg.mpr htpos.le) (M.add_mem hm hu)
      rwa [← h1, inv_smul_smul₀ htpos.ne'] at this
  obtain ⟨L, hLu, hLM'⟩ := exists_nonneg_functional_of_archimedean M' u
    (fun y => (harch y).imp fun _ hN => hMM' hN) hneg
  refine ⟨L, hLu, fun x hx => hLM' x (hMM' hx), ?_⟩
  have := hLM' _ hnegh
  rw [map_neg] at this
  linarith

end Separation

end MIPRE
