/-
Copyright (c) 2026 Sean Perazzolo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sean Perazzolo
-/
import MIPRE.LCS.Basic
import Mathlib.Data.Finset.Sort
import Mathlib.GroupTheory.FreeGroup.Reduce
import Mathlib.GroupTheory.PresentedGroup


/-!
# Solution Groups for Binary Linear Systems

This module defines the solution group attached to a binary linear system.  For a
system with variables `g_j` and distinguished generator `J`, the presentation is
generated by the four standard families of relations:

* every `g_j` and `J` is an involution;
* each `g_j` commutes with `J`;
* variables that occur in a common equation commute;
* each equation imposes the product relation
  `∏_{j ∈ support(i)} g_j = J ^ b_i`.

The main construction is `SolutionGroup S`, together with quotient elements
`SolutionGroup.var` and `SolutionGroup.J` and lemmas showing that the four
families of defining constraints hold in the presented group.
-/

namespace MIPRE.LCS

section Generators

/-- Generators for the solution group of a binary linear system. -/
inductive SolutionGen (S : LinearSystem) where
  | var : Fin S.layout.s → SolutionGen S
  | J : SolutionGen S
deriving DecidableEq

end Generators

section DefiningRelators
/-!
## Defining Constraint Relators

The next definitions collect the free-group words used to impose the four
families of constraints in the solution-group presentation.
-/

/-- The free-group generator attached to variable `j`. -/
def genVar {S : LinearSystem} (j : Fin S.layout.s) : FreeGroup (SolutionGen S) :=
  FreeGroup.of (SolutionGen.var j)

/-- The distinguished central free-group generator. -/
def genJ {S : LinearSystem} : FreeGroup (SolutionGen S) :=
  FreeGroup.of SolutionGen.J

/-- The relator forcing `x` to be an involution. -/
def involutionRel {α : Type*} (x : FreeGroup α) : FreeGroup α :=
  x ^ 2

/-- The commutator relator forcing `x` and `y` to commute. -/
def commuteRel {α : Type*} (x y : FreeGroup α) : FreeGroup α :=
  x * y * x⁻¹ * y⁻¹




/-!
### `∏_{j ∈ support(i)} g_j = J ^ b_i`

The next helper lemmas work towards  the product for equation `i` equals `J^(b_i)`

-/

/-- The support of equation `i`, extracted from the coefficient matrix. -/
def eqSupport (S : LinearSystem) (i : Fin S.layout.r) : Finset (Fin S.layout.s) :=
  Finset.univ.filter fun j ↦ S.A i j = 1

/-- The left-hand-side word of equation `i`, ordered by the `Finset` order. -/
def equationWord (S : LinearSystem) (i : Fin S.layout.r) : FreeGroup (SolutionGen S) :=
  ((eqSupport S i).sort (· ≤ ·)).map (genVar (S := S)) |>.prod

/-- The relator encoding equation `i` as `equationWord = J^(b i)`. -/
def equationRelator (S : LinearSystem) (i : Fin S.layout.r) : FreeGroup (SolutionGen S) :=
  equationWord S i * (genJ (S := S) ^ (S.b i).val)⁻¹

/-- Two variables are related when they appear together in some equation. -/
def SameEquation (S : LinearSystem) (j k : Fin S.layout.s) : Prop :=
  ∃ i : Fin S.layout.r, S.A i j = 1 ∧ S.A i k = 1

/-- Computable test for `SameEquation`, used to build an inspectable relator list. -/
def sameEquationBool (S : LinearSystem) (j k : Fin S.layout.s) : Bool :=
  (List.finRange S.layout.r).any fun i ↦
    decide (S.A i j = 1 ∧ S.A i k = 1)

/-- List of the defining relators of the solution group of `S`. -/
def solutionRelatorsList (S : LinearSystem) : List (FreeGroup (SolutionGen S)) :=
  let vars := List.finRange S.layout.s
  let eqs := List.finRange S.layout.r
  -- Relation 1: involutions.
  let varInvolutions := vars.map fun j ↦ involutionRel (genVar (S := S) j)
  let jInvolution := [involutionRel (genJ (S := S))]
  -- Relation 2: each variable generator commutes with `J`.
  let jCentrality := vars.map fun j ↦ commuteRel (genVar (S := S) j) (genJ (S := S))
  -- Relation 3: variables appearing together in some equation commute.
  let varCommutation := vars.flatMap fun j ↦
    vars.filterMap fun k ↦
      if j < k && sameEquationBool S j k then
        some (commuteRel (genVar (S := S) j) (genVar (S := S) k))
      else
        none
  -- Relation 4: the product for equation `i` equals `J^(b_i)`.
  let equationRels := eqs.map fun i ↦ equationRelator S i
  varInvolutions ++ jInvolution ++ jCentrality ++ varCommutation ++ equationRels



/-!
### Defining the relations as a set

-/

/-- The defining relators of the solution group of `S`. -/
def solutionRelators (S : LinearSystem) : Set (FreeGroup (SolutionGen S)) :=
  fun w ↦
    -- Membership test: `w` is in this set iff it is one of the following relator words.
    -- Relation 1 for variables: `g_j^2 = 1`.
    (∃ j, w = involutionRel (genVar (S := S) j)) ∨
    -- Relation 1 for the distinguished generator: `J^2 = 1`.
    w = involutionRel (genJ (S := S)) ∨
    -- Relation 2: each variable generator commutes with `J`.
    (∃ j, w = commuteRel (genVar (S := S) j) (genJ (S := S))) ∨
    -- Relation 3: variables appearing together in some equation commute.
    (∃ j k, j < k ∧ SameEquation S j k ∧
      w = commuteRel (genVar (S := S) j) (genVar (S := S) k)) ∨
    -- Relation 4: the product for equation `i` equals `J^(b_i)`.
    (∃ i, w = equationRelator S i)

/-- The computable same-equation test agrees with the propositional predicate. -/
lemma sameEquationBool_iff (S : LinearSystem) (j k : Fin S.layout.s) :
    sameEquationBool S j k = true ↔ SameEquation S j k := by
  unfold sameEquationBool SameEquation
  constructor
  · intro h
    rcases (List.any_eq_true.mp h) with ⟨i, _hi, hdec⟩
    exact ⟨i, of_decide_eq_true hdec⟩
  · rintro ⟨i, hi⟩
    exact List.any_eq_true.mpr ⟨i, List.mem_finRange i, decide_eq_true hi⟩

/-- The list presentation has the same membership as the direct set presentation. -/
lemma mem_solutionRelatorsList_iff {S : LinearSystem} {w : FreeGroup (SolutionGen S)} :
    w ∈ solutionRelatorsList S ↔ w ∈ solutionRelators S := by
  unfold solutionRelators
  constructor
  · intro hw
    simp only [solutionRelatorsList, List.append_assoc, List.cons_append, List.nil_append,
      Bool.and_eq_true, decide_eq_true_eq, sameEquationBool_iff, List.mem_append,
      List.mem_map, List.mem_finRange, true_and, List.mem_cons, List.mem_flatMap,
      List.mem_filterMap, Option.ite_none_right_eq_some, Option.some.injEq] at hw
    rcases hw with h | h | h | h | h
    · rcases h with ⟨j, hj⟩
      exact Or.inl ⟨j, hj.symm⟩
    · exact Or.inr (Or.inl h)
    · rcases h with ⟨j, hj⟩
      exact Or.inr (Or.inr (Or.inl ⟨j, hj.symm⟩))
    · rcases h with ⟨j, k, hcond, hw⟩
      exact Or.inr (Or.inr (Or.inr (Or.inl ⟨j, k, hcond.1, hcond.2, hw.symm⟩)))
    · rcases h with ⟨i, hi⟩
      exact Or.inr (Or.inr (Or.inr (Or.inr ⟨i, hi.symm⟩)))
  · intro hw
    simp only [solutionRelatorsList, List.append_assoc, List.cons_append, List.nil_append,
      Bool.and_eq_true, decide_eq_true_eq, sameEquationBool_iff, List.mem_append,
      List.mem_map, List.mem_finRange, true_and, List.mem_cons, List.mem_flatMap,
      List.mem_filterMap, Option.ite_none_right_eq_some, Option.some.injEq]
    rcases hw with h | h | h | h | h
    · rcases h with ⟨j, hj⟩
      exact Or.inl ⟨j, hj.symm⟩
    · exact Or.inr (Or.inl h)
    · rcases h with ⟨j, hj⟩
      exact Or.inr (Or.inr (Or.inl ⟨j, hj.symm⟩))
    · rcases h with ⟨j, k, hjk, hsame, hw⟩
      exact Or.inr (Or.inr (Or.inr (Or.inl ⟨j, k, ⟨hjk, hsame⟩, hw.symm⟩)))
    · rcases h with ⟨i, hi⟩
      exact Or.inr (Or.inr (Or.inr (Or.inr ⟨i, hi.symm⟩)))

end DefiningRelators

section PresentedSolutionGroup

/-- The solution group of a binary linear system: the group presented by the defining
relators of `solutionRelators`. -/
abbrev SolutionGroup (S : LinearSystem) :=
  PresentedGroup (solutionRelators S)

namespace SolutionGroup

/-- The distinguished quotient element attached to variable `j`. -/
def var {S : LinearSystem} (j : Fin S.layout.s) : SolutionGroup S :=
  PresentedGroup.of (rels := solutionRelators S) (SolutionGen.var j)

/-- The distinguished quotient element `J`. -/
def J {S : LinearSystem} : SolutionGroup S :=
  PresentedGroup.of (rels := solutionRelators S) SolutionGen.J

@[simp] lemma var_sq {S : LinearSystem} (j : Fin S.layout.s) : var (S := S) j ^ 2 = 1 := by
  simpa [var, genVar, involutionRel, PresentedGroup.of] using
    (PresentedGroup.one_of_mem
      (rels := solutionRelators S)
      (x := involutionRel (genVar (S := S) j))
      (Or.inl ⟨j, rfl⟩))

@[simp] lemma J_sq {S : LinearSystem} : J (S := S) ^ 2 = 1 := by
  simpa [J, genJ, involutionRel, PresentedGroup.of] using
    (PresentedGroup.one_of_mem
      (rels := solutionRelators S)
      (x := involutionRel (genJ (S := S)))
      (Or.inr (Or.inl rfl)))

lemma var_comm_J {S : LinearSystem} (j : Fin S.layout.s) :
    var (S := S) j * J (S := S) = J (S := S) * var (S := S) j := by
  have h :
      var (S := S) j * J (S := S) * (var (S := S) j)⁻¹ * (J (S := S))⁻¹ = 1 := by
    simpa [var, J, genVar, genJ, commuteRel, PresentedGroup.of] using
      (PresentedGroup.one_of_mem
        (rels := solutionRelators S)
        (x := commuteRel (genVar (S := S) j) (genJ (S := S)))
        (Or.inr (Or.inr (Or.inl ⟨j, rfl⟩))))
  have h' := congrArg (fun z ↦ z * J (S := S) * var (S := S) j) h
  simpa [mul_assoc] using h'

lemma var_comm_of_sameEquation {S : LinearSystem} {j k : Fin S.layout.s}
    (hjk : SameEquation S j k) :
    var (S := S) j * var (S := S) k = var (S := S) k * var (S := S) j := by
  rcases lt_trichotomy j k with hjk_lt | hjk_eq | hkj_lt
  · have h :
        var (S := S) j * var (S := S) k * (var (S := S) j)⁻¹ * (var (S := S) k)⁻¹ = 1 := by
      simpa [var, genVar, commuteRel, PresentedGroup.of] using
        (PresentedGroup.one_of_mem
          (rels := solutionRelators S)
          (x := commuteRel (genVar (S := S) j) (genVar (S := S) k))
          (Or.inr (Or.inr (Or.inr (Or.inl ⟨j, k, hjk_lt, hjk, rfl⟩)))))
    have h' := congrArg (fun z ↦ z * var (S := S) k * var (S := S) j) h
    simpa [mul_assoc] using h'
  · subst k
    simp
  · have hkj : SameEquation S k j := by
      rcases hjk with ⟨i, hij, hik⟩
      exact ⟨i, hik, hij⟩
    have h :
        var (S := S) k * var (S := S) j * (var (S := S) k)⁻¹ * (var (S := S) j)⁻¹ = 1 := by
      simpa [var, genVar, commuteRel, PresentedGroup.of] using
        (PresentedGroup.one_of_mem
          (rels := solutionRelators S)
          (x := commuteRel (genVar (S := S) k) (genVar (S := S) j))
          (Or.inr (Or.inr (Or.inr (Or.inl ⟨k, j, hkj_lt, hkj, rfl⟩)))))
    have h' := congrArg (fun z ↦ z * var (S := S) j * var (S := S) k) h
    simpa [mul_assoc] using h'.symm

lemma equation_holds {S : LinearSystem} (i : Fin S.layout.r) :
    PresentedGroup.mk (solutionRelators S) (equationWord S i) = J (S := S) ^ (S.b i).val := by
  have h :
      PresentedGroup.mk (solutionRelators S) (equationWord S i) *
          (J (S := S) ^ (S.b i).val)⁻¹ = 1 := by
    simpa [equationRelator, J, genJ, PresentedGroup.of] using
      (PresentedGroup.one_of_mem
        (rels := solutionRelators S)
        (x := equationRelator S i)
        (Or.inr (Or.inr (Or.inr (Or.inr ⟨i, rfl⟩)))))
  calc
    PresentedGroup.mk (solutionRelators S) (equationWord S i)
        = PresentedGroup.mk (solutionRelators S) (equationWord S i) *
            (J (S := S) ^ (S.b i).val)⁻¹ * (J (S := S) ^ (S.b i).val) := by
          simp [mul_assoc]
    _ = J (S := S) ^ (S.b i).val := by
          rw [h]
          simp

end SolutionGroup

end PresentedSolutionGroup

end MIPRE.LCS
