/-
Copyright (c) 2026 the commuting-repetition contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE. Vendored from
https://github.com/vidick/commuting-repetition (commit cfa2f1bf, 2026-09-11) by scripts/vendor-repetition.py;
do not edit by hand. Upstream path: lean/CommutingRepetition/OTQCS/JointMeasure.lean
-/
/-
# OTQCS: the joint left–right spectral measure (node 1.3.2) and the
modulus family root (nodes 1.3.1 + 1.3.2)

Anchors: 06_otqcs.tex, eqs joint-measure, joint-moments,
modulus-stability, Dbar-Delta.

The joint distribution `ν_{h,k}` of the strongly commuting left action
of `h` and right action of `k` in the trace vector is consumed only
through: rectangles (eq joint-measure, = the `cross` field), its
marginals, and the second cross moment (eq joint-moments, third
identity — genuine joint-PVM content, not derivable from rectangles).
`exists_modulusFamily` is the single sorried root carrying ALL von
Neumann content of Section 6 (work package B7): it produces a tracial
extension (the generated von Neumann algebra on the same L², see
OTQCS/Modulus.lean) and, over it, the per-vector spectral packages,
the pairwise couplings, and the modulus stability bound of eq
modulus-stability.
-/
import Mathlib
import MIPRE.Background.Repetition.CommutingRepetition.OTQCS.Modulus
import MIPRE.Background.Repetition.CommutingRepetition.VN.JointModulus

-- Upstream builds with Lean's default `autoImplicit = true`; this repository turns it
-- off in `lakefile.toml`. Inserted by scripts/vendor-repetition.py.
set_option autoImplicit true

namespace CommutingRepetition

open MeasureTheory
open scoped BigOperators InnerProductSpace

universe u v w

/-- **Joint left–right spectral coupling** of two modulus packages
(node 1.3.2; 06_otqcs.tex, eqs joint-measure + joint-moments): a
probability measure on `ℝ × ℝ` whose marginals are the two spectral
distributions, whose rectangle masses are the traces
`τ(1_I(h) 1_J(k))` (eq joint-measure — in particular those traces are
nonnegative), and whose second cross moment is `‖h − k‖₂²` (eq
joint-moments; the coordinate second moments come from the marginals
and `SpectralData.moment2`). No joint PVM for `h, k` inside the
algebra is asserted. -/
structure JointSpectralData {N : StdTracialAlgebra.{u}} {x y : N.H}
    (dA : SpectralData N x) (dB : SpectralData N y) where
  ν : Measure (ℝ × ℝ)
  ν_prob : IsProbabilityMeasure ν
  margA : ν.map Prod.fst = dA.μ
  margB : ν.map Prod.snd = dB.μ
  cross : ∀ I J : Set ℝ, MeasurableSet I → MeasurableSet J →
    N.τ (dA.proj I * dB.proj J) = ((ν (I ×ˢ J)).toReal : ℂ)
  crossMoment : (∫ p : ℝ × ℝ, (p.1 - p.2) ^ 2 ∂ν) = ‖dA.hvec - dB.hvec‖ ^ 2

/-- **Modulus family** over label families of vectors (nodes 1.3.1 +
1.3.2): per-vector spectral packages for Alice's `x_s` and Bob's
`y_t`, a joint coupling for every pair, and the modulus stability
bound `‖h_s − k_t‖₂² ≤ 2 ‖x_s − y_t‖₂²` (node 1.3.1; 06_otqcs.tex,
lem otqcs-modulus, eq modulus-stability — stated pairwise, which is
how eq Dbar-Delta consumes it). -/
structure ModulusFamily (N : StdTracialAlgebra.{u}) {S : Type v}
    {T : Type w} (x : S → N.H) (y : T → N.H) where
  dataA : ∀ s, SpectralData N (x s)
  dataB : ∀ t, SpectralData N (y t)
  joint : ∀ s t, JointSpectralData (dataA s) (dataB t)
  stability : ∀ s t,
    ‖(dataA s).hvec - (dataB t).hvec‖ ^ 2 ≤ 2 * ‖x s - y t‖ ^ 2

/-- **Existence of the modulus family over a tracial extension**
(nodes 1.3.1 + 1.3.2; 06_otqcs.tex, §"Left moduli and a joint
left–right spectral measure"): every finite-vector family over a
standard-form algebra admits, after passing to a tracial extension
(the von Neumann algebra generated by the left action, acting on the
unitarily identified L² — OTQCS/Modulus.lean), left-modulus spectral
packages, pairwise joint couplings, and the stability bound. The
single von Neumann root of Section 6 (work package B7: polar
decomposition, Borel functional calculus, the joint PVM of strongly
commuting actions, and the L²-Lipschitz bound of appendix
otqcs-absolute-value). -/
theorem exists_modulusFamily (N : StdTracialAlgebra.{u}) {S : Type v}
    {T : Type w} (x : S → N.H) (y : T → N.H) :
    ∃ ext : TracialExtension N,
      Nonempty (ModulusFamily ext.N' (fun s => ext.U (x s))
        (fun t => ext.U (y t))) := by
  -- The extension is the concrete von Neumann model `R(N)′` on the same `L²(N)`
  -- (`VN/ConcreteVN`, `VN/Commutation`); the per-vector packages are the left
  -- moduli of `VN/LeftModulusData`, the couplings the joint spectral measures of
  -- `VN/JointModulus`, and the stability bound is `VN/ModulusStability`.
  refine ⟨N.vnExtension, ⟨?_⟩⟩
  show ModulusFamily N.vnModel x y
  exact
    { dataA := fun s => GraphMod.spectralData N (x s)
      dataB := fun t => GraphMod.spectralData N (y t)
      joint := fun s t =>
        { ν := GraphMod.νψ N (x s) (y t)
          ν_prob := GraphMod.νψ_prob N (x s) (y t)
          margA := GraphMod.νψ_map_fst N (x s) (y t)
          margB := GraphMod.νψ_map_snd N (x s) (y t)
          cross := fun _ _ hI hJ => GraphMod.cross N (x s) (y t) hI hJ
          crossMoment := GraphMod.crossMoment N (x s) (y t) }
      stability := fun s t => GraphMod.stability N (x s) (y t) }

end CommutingRepetition
