/-
Copyright (c) 2026 the commuting-repetition contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE. Vendored from
https://github.com/vidick/commuting-repetition (commit cfa2f1bf, 2026-09-11) by scripts/vendor-repetition.py;
do not edit by hand. Upstream path: lean/CommutingRepetition/OTQCS/Modulus.lean
-/
/-
# OTQCS: left moduli in consumed form (node 1.3.1, interface half)

Anchors: 06_otqcs.tex, eqs left-polar, modulus-stability, and the
consumption sites rounded-y, rounding-tails, w-norm, polar-initial.

Encoding decisions (DIFFERENCES.md D17):

* The left modulus `h_x = (x x*)^{1/2}` of an L² vector may be
  unbounded and affiliated; Mathlib has no affiliated operators. It is
  therefore consumed, never constructed: `SpectralData` bundles exactly
  the finitely many facts Section 6 uses about `h_x` — its spectral
  distribution in the trace, itself as an L² *vector*, the polar
  partial isometry, and the band spectral projections `1_I(h_x)` with
  their trace, support, and pairing identities. The projections are
  algebra elements, so they live where von Neumann closure puts them:
  not in the original carrier but in an enlarged one. `TracialExtension`
  packages that enlargement — a second standard-form algebra acting on
  a unitarily identified L² space (the manuscript's passage to the
  generated von Neumann algebra, which has the same L²) — and the
  existence root (`exists_modulusFamily`, OTQCS/JointMeasure.lean)
  produces the extension and the data together. Work package B7 proves
  it; nothing downstream sees an unbounded operator.
-/
import Mathlib
import MIPRE.Background.Repetition.CommutingRepetition.Tracial.Interface

-- Upstream builds with Lean's default `autoImplicit = true`; this repository turns it
-- off in `lakefile.toml`. Inserted by scripts/vendor-repetition.py.
set_option autoImplicit true

namespace CommutingRepetition

open MeasureTheory
open scoped BigOperators InnerProductSpace

universe u v

/-- A tracial extension of a standard-form algebra: a second
standard-form algebra `N'` together with a unital ∗-homomorphism of
carriers and a unitary identification of the L² spaces intertwining
the embeddings and both actions. The intended instance is the von
Neumann algebra generated by the left action — acting on the *same*
L² space (the extension of the trace is spatial), which is why a
single unitary `U` carries all Section 6 comparisons back to the
original data. [06_otqcs.tex, standing assumptions: "finite von
Neumann algebra with faithful normal normalized trace", reached from
the tracial ∗-algebra of the Section 5 output by closure] -/
structure TracialExtension (N : StdTracialAlgebra.{u}) where
  N' : StdTracialAlgebra.{u}
  emb : N.A →⋆ₐ[ℂ] N'.A
  U : N.H ≃ₗᵢ[ℂ] N'.H
  U_ι : ∀ a : N.A, U (N.ι a) = N'.ι (emb a)
  L_emb : ∀ (a : N.A) (ξ : N.H), N'.L (emb a) (U ξ) = U (N.L a ξ)
  R_emb : ∀ (a : N.A) (ξ : N.H), N'.Rop (emb a) (U ξ) = U (N.Rop a ξ)

/-- **Left-modulus spectral package** for a vector `x` (node 1.3.1;
06_otqcs.tex, eq left-polar): the consumed form of the left polar
decomposition `x = h_x v_x`, `h_x = (x x*)^{1/2}`,
`v_x v_x* = s(h_x)`. Carries: the spectral distribution `μ` of `h_x`
in the trace (a probability measure on `ℝ`, supported on `[0, ∞)`,
with the kernel atom at `0`); the modulus as an L² vector `hvec`
(`‖h_x‖₂ = ‖x‖₂`, second moment `∫ b² dμ = ‖x‖²`); the polar partial
isometry `v` with `h_x · v = x` and `h_x · (v v*) = h_x`; and the band
spectral projections `proj I = 1_I(h_x)` with their ∗-lattice
identities, trace masses, support absorption above `0`, and the two
moment pairings against `hvec` that the rounding estimates of eqs
rounded-y/rounding-tails consume. -/
structure SpectralData (N : StdTracialAlgebra.{u}) (x : N.H) where
  μ : Measure ℝ
  μ_prob : IsProbabilityMeasure μ
  μ_nonneg : μ (Set.Iio 0) = 0
  hvec : N.H
  hvec_norm : ‖hvec‖ = ‖x‖
  moment2 : (∫ b, b ^ 2 ∂μ) = ‖x‖ ^ 2
  v : N.A
  polar : N.Rop v hvec = x
  supp_vec : N.Rop (v * star v) hvec = hvec
  proj : Set ℝ → N.A
  proj_star : ∀ I : Set ℝ, star (proj I) = proj I
  proj_empty : proj ∅ = 0
  proj_inter : ∀ I J : Set ℝ, MeasurableSet I → MeasurableSet J →
    proj I * proj J = proj (I ∩ J)
  proj_union : ∀ I J : Set ℝ, MeasurableSet I → MeasurableSet J →
    Disjoint I J → proj (I ∪ J) = proj I + proj J
  proj_trace : ∀ I : Set ℝ, MeasurableSet I →
    N.τ (proj I) = ((μ I).toReal : ℂ)
  absorb : ∀ I : Set ℝ, MeasurableSet I → I ⊆ Set.Ioi 0 →
    (v * star v) * proj I = proj I
  pairing1 : ∀ I : Set ℝ, MeasurableSet I →
    ⟪N.ι (proj I), hvec⟫_ℂ = ((∫ b in I, b ∂μ : ℝ) : ℂ)
  pairing2 : ∀ I : Set ℝ, MeasurableSet I →
    ⟪hvec, N.Rop (proj I) hvec⟫_ℂ = ((∫ b in I, b ^ 2 ∂μ : ℝ) : ℂ)

end CommutingRepetition
